//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <TFNUI/TFNViewController.h>

#import <T1Twitter/T1AltTextViewControllerDelegate-Protocol.h>
#import <T1Twitter/T1AutocompleteViewControllerDelegate-Protocol.h>
#import <T1Twitter/T1NewsCameraColorPickerDelegate-Protocol.h>
#import <T1Twitter/T1NewsCameraEventHashtagsViewControllerDelegate-Protocol.h>
#import <T1Twitter/T1NewsCameraGeoPickerControllerDelegate-Protocol.h>
#import <T1Twitter/T1NewsCameraThreadObserverDelegate-Protocol.h>
#import <T1Twitter/T1NewsCameraTweetTextEditViewDelegate-Protocol.h>
#import <T1Twitter/TFNCircularCountProgressDataSource-Protocol.h>
#import <T1Twitter/TFNKeyboardDismissalContainerViewDelegate-Protocol.h>
#import <T1Twitter/TFNModalHitTestViewDelegate-Protocol.h>
#import <T1Twitter/TFNTooltipDelegate-Protocol.h>
#import <T1Twitter/UIGestureRecognizerDelegate-Protocol.h>
#import <T1Twitter/UITextViewDelegate-Protocol.h>

@class NSArray, NSLayoutConstraint, NSString, T1AutocompleteViewController, T1ComposeAccountAvatarImageView, T1NewsCameraCaptureChyronView, T1NewsCameraCaptureOutput, T1NewsCameraCapturePreviewView, T1NewsCameraColorPicker, T1NewsCameraComposition, T1NewsCameraControlButton, T1NewsCameraEventHashtagsViewController, T1NewsCameraFetchResult, T1NewsCameraGeoPickerButton, T1NewsCameraGeoPickerController, T1NewsCameraThreadButton, T1NewsCameraThreadObserver, T1NewsCameraThreadPreviewViewController, T1NewsCameraTweetTextEditView, TFNCircularCountProgressView, TFNKeyboardDismissalContainerView, TFNModalHitTestView, TFNTwitterAccount, TFSTwitterScribeContext, UIButton, UILayoutGuide, UILongPressGestureRecognizer, UIPanGestureRecognizer, UITapGestureRecognizer, UIView;
@protocol T1NewsCameraCaptureCameraModeEditViewControllerDelegate;

@interface T1NewsCameraCaptureCameraModeEditViewController : TFNViewController <T1AltTextViewControllerDelegate, T1AutocompleteViewControllerDelegate, T1NewsCameraColorPickerDelegate, T1NewsCameraEventHashtagsViewControllerDelegate, T1NewsCameraGeoPickerControllerDelegate, T1NewsCameraThreadObserverDelegate, T1NewsCameraTweetTextEditViewDelegate, TFNCircularCountProgressDataSource, TFNKeyboardDismissalContainerViewDelegate, TFNModalHitTestViewDelegate, TFNTooltipDelegate, UIGestureRecognizerDelegate, UITextViewDelegate>
{
    _Bool _threadPreviewingEnabled;
    _Bool _viewFullyLoaded;
    _Bool _fullyPresented;
    _Bool _chyronViewExpanded;
    _Bool _cancelButtonLayoutTopmost;
    id <T1NewsCameraCaptureCameraModeEditViewControllerDelegate> _delegate;
    TFNTwitterAccount *_account;
    T1NewsCameraComposition *_composition;
    T1NewsCameraCaptureOutput *_captureOutput;
    T1NewsCameraFetchResult *_currentPlacesFetchResult;
    T1NewsCameraFetchResult *_currentEventHashtagsFetchResult;
    TFSTwitterScribeContext *_scribeContext;
    unsigned long long _state;
    T1NewsCameraThreadObserver *_threadObserver;
    UILayoutGuide *_viewLayoutMarginsGuide;
    UIView *_previewContainerView;
    UILayoutGuide *_previewContainerViewLayoutMarginsGuide;
    NSLayoutConstraint *_previewContainerViewLeadingAnchorConstraint;
    NSLayoutConstraint *_previewContainerViewThreadPreviewingLeadingAnchorConstraint;
    UIPanGestureRecognizer *_previewContainerViewPanGestureRecognizer;
    UIView *_threadPreviewContainerView;
    UILayoutGuide *_threadPreviewContainerViewLayoutMarginsGuide;
    UIPanGestureRecognizer *_threadPreviewContainerViewPanGestureRecognizer;
    T1NewsCameraThreadPreviewViewController *_threadPreviewViewController;
    T1NewsCameraCapturePreviewView *_previewView;
    UILayoutGuide *_previewViewLayoutMarginsGuide;
    UILayoutGuide *_controlButtonsLayoutGuide;
    TFNKeyboardDismissalContainerView *_keyboardDismissalContainerView;
    UILongPressGestureRecognizer *_contentViewLongPressGestureRecognizer;
    UIView *_chyronBackgroundView;
    UITapGestureRecognizer *_chyronBackgroundViewTapGestureRecognizer;
    UILayoutGuide *_chyronViewLayoutGuide;
    NSLayoutConstraint *_chyronViewLayoutGuideTopAnchorConstraint;
    UILayoutGuide *_expandedChyronViewLayoutGuide;
    T1NewsCameraCaptureChyronView *_chyronView;
    NSLayoutConstraint *_chyronViewTopAnchorConstraint;
    NSArray *_chyronViewPercentageTransitionLayoutConstraints;
    UITapGestureRecognizer *_chyronViewTapGestureRecognizer;
    double _chyronViewPositionPercentage;
    double _chyronViewTransitionPercentage;
    UILayoutGuide *_chyronViewContentLayoutGuide;
    NSLayoutConstraint *_chyronViewContentLayoutGuideTopAnchorConstraint;
    T1NewsCameraGeoPickerButton *_geoPickerButton;
    NSLayoutConstraint *_geoPickerButtonLeadingAnchorConstraint;
    T1NewsCameraGeoPickerController *_currentGeoPickerViewController;
    T1ComposeAccountAvatarImageView *_avatarImageView;
    T1NewsCameraTweetTextEditView *_tweetTextEditView;
    T1NewsCameraEventHashtagsViewController *_eventHashtagsViewController;
    UIView *_controlsView;
    UIView *_controlsBackgroundView;
    UIButton *_tweetButton;
    TFNCircularCountProgressView *_tweetTextCountProgressView;
    T1NewsCameraColorPicker *_colorPickerViewController;
    NSLayoutConstraint *_colorPickerViewControllerLeadingAnchorConstraint;
    NSLayoutConstraint *_colorPickerViewControllerAddToThreadButtonLeadingAnchorConstraint;
    NSLayoutConstraint *_colorPickerViewControllerExpandedLeadingAnchorConstraint;
    NSLayoutConstraint *_colorPickerViewControllerTrailingAnchorConstraint;
    NSLayoutConstraint *_colorPickerViewControllerExpandedTrailingAnchorConstraint;
    NSLayoutConstraint *_colorPickerViewControllerColorWheelLayoutGuideLeadingAnchorConstraint;
    NSLayoutConstraint *_colorPickerViewControllerColorWheelLayoutGuideAddToThreadButtonLeadingAnchorConstraint;
    T1NewsCameraThreadButton *_addToThreadButton;
    NSLayoutConstraint *_addToThreadButtonLeadingAnchorConstraint;
    NSLayoutConstraint *_addToThreadButtonTrailingAnchorConstraint;
    T1AutocompleteViewController *_autocompleteViewController;
    NSLayoutConstraint *_autocompleteViewControllerHeightAnchorConstraint;
    NSLayoutConstraint *_autocompleteViewControllerHiddenHeightAnchorConstraint;
    T1NewsCameraControlButton *_cancelButton;
    NSArray *_cancelButtonLayoutConstraints;
    NSArray *_cancelButtonTopmostLayoutConstraints;
    UIButton *_muteButton;
    UIButton *_addDescriptionButton;
    NSLayoutConstraint *_addDescriptionButtonTrailingAnchorConstraint;
    NSLayoutConstraint *_addDescriptionButtonWithMuteButtonTrailingAnchorConstraint;
    struct CGPoint _lastDraggingTranslation;
}

@property(retain, nonatomic) NSLayoutConstraint *addDescriptionButtonWithMuteButtonTrailingAnchorConstraint; // @synthesize addDescriptionButtonWithMuteButtonTrailingAnchorConstraint=_addDescriptionButtonWithMuteButtonTrailingAnchorConstraint;
@property(retain, nonatomic) NSLayoutConstraint *addDescriptionButtonTrailingAnchorConstraint; // @synthesize addDescriptionButtonTrailingAnchorConstraint=_addDescriptionButtonTrailingAnchorConstraint;
@property(retain, nonatomic) UIButton *addDescriptionButton; // @synthesize addDescriptionButton=_addDescriptionButton;
@property(retain, nonatomic) UIButton *muteButton; // @synthesize muteButton=_muteButton;
@property(nonatomic, getter=isCancelButtonLayoutTopmost) _Bool cancelButtonLayoutTopmost; // @synthesize cancelButtonLayoutTopmost=_cancelButtonLayoutTopmost;
@property(copy, nonatomic) NSArray *cancelButtonTopmostLayoutConstraints; // @synthesize cancelButtonTopmostLayoutConstraints=_cancelButtonTopmostLayoutConstraints;
@property(copy, nonatomic) NSArray *cancelButtonLayoutConstraints; // @synthesize cancelButtonLayoutConstraints=_cancelButtonLayoutConstraints;
@property(retain, nonatomic) T1NewsCameraControlButton *cancelButton; // @synthesize cancelButton=_cancelButton;
@property(retain, nonatomic) NSLayoutConstraint *autocompleteViewControllerHiddenHeightAnchorConstraint; // @synthesize autocompleteViewControllerHiddenHeightAnchorConstraint=_autocompleteViewControllerHiddenHeightAnchorConstraint;
@property(retain, nonatomic) NSLayoutConstraint *autocompleteViewControllerHeightAnchorConstraint; // @synthesize autocompleteViewControllerHeightAnchorConstraint=_autocompleteViewControllerHeightAnchorConstraint;
@property(retain, nonatomic) T1AutocompleteViewController *autocompleteViewController; // @synthesize autocompleteViewController=_autocompleteViewController;
@property(retain, nonatomic) NSLayoutConstraint *addToThreadButtonTrailingAnchorConstraint; // @synthesize addToThreadButtonTrailingAnchorConstraint=_addToThreadButtonTrailingAnchorConstraint;
@property(retain, nonatomic) NSLayoutConstraint *addToThreadButtonLeadingAnchorConstraint; // @synthesize addToThreadButtonLeadingAnchorConstraint=_addToThreadButtonLeadingAnchorConstraint;
@property(retain, nonatomic) T1NewsCameraThreadButton *addToThreadButton; // @synthesize addToThreadButton=_addToThreadButton;
@property(retain, nonatomic) NSLayoutConstraint *colorPickerViewControllerColorWheelLayoutGuideAddToThreadButtonLeadingAnchorConstraint; // @synthesize colorPickerViewControllerColorWheelLayoutGuideAddToThreadButtonLeadingAnchorConstraint=_colorPickerViewControllerColorWheelLayoutGuideAddToThreadButtonLeadingAnchorConstraint;
@property(retain, nonatomic) NSLayoutConstraint *colorPickerViewControllerColorWheelLayoutGuideLeadingAnchorConstraint; // @synthesize colorPickerViewControllerColorWheelLayoutGuideLeadingAnchorConstraint=_colorPickerViewControllerColorWheelLayoutGuideLeadingAnchorConstraint;
@property(retain, nonatomic) NSLayoutConstraint *colorPickerViewControllerExpandedTrailingAnchorConstraint; // @synthesize colorPickerViewControllerExpandedTrailingAnchorConstraint=_colorPickerViewControllerExpandedTrailingAnchorConstraint;
@property(retain, nonatomic) NSLayoutConstraint *colorPickerViewControllerTrailingAnchorConstraint; // @synthesize colorPickerViewControllerTrailingAnchorConstraint=_colorPickerViewControllerTrailingAnchorConstraint;
@property(retain, nonatomic) NSLayoutConstraint *colorPickerViewControllerExpandedLeadingAnchorConstraint; // @synthesize colorPickerViewControllerExpandedLeadingAnchorConstraint=_colorPickerViewControllerExpandedLeadingAnchorConstraint;
@property(retain, nonatomic) NSLayoutConstraint *colorPickerViewControllerAddToThreadButtonLeadingAnchorConstraint; // @synthesize colorPickerViewControllerAddToThreadButtonLeadingAnchorConstraint=_colorPickerViewControllerAddToThreadButtonLeadingAnchorConstraint;
@property(retain, nonatomic) NSLayoutConstraint *colorPickerViewControllerLeadingAnchorConstraint; // @synthesize colorPickerViewControllerLeadingAnchorConstraint=_colorPickerViewControllerLeadingAnchorConstraint;
@property(retain, nonatomic) T1NewsCameraColorPicker *colorPickerViewController; // @synthesize colorPickerViewController=_colorPickerViewController;
@property(retain, nonatomic) TFNCircularCountProgressView *tweetTextCountProgressView; // @synthesize tweetTextCountProgressView=_tweetTextCountProgressView;
@property(retain, nonatomic) UIButton *tweetButton; // @synthesize tweetButton=_tweetButton;
@property(retain, nonatomic) UIView *controlsBackgroundView; // @synthesize controlsBackgroundView=_controlsBackgroundView;
@property(retain, nonatomic) UIView *controlsView; // @synthesize controlsView=_controlsView;
@property(retain, nonatomic) T1NewsCameraEventHashtagsViewController *eventHashtagsViewController; // @synthesize eventHashtagsViewController=_eventHashtagsViewController;
@property(retain, nonatomic) T1NewsCameraTweetTextEditView *tweetTextEditView; // @synthesize tweetTextEditView=_tweetTextEditView;
@property(retain, nonatomic) T1ComposeAccountAvatarImageView *avatarImageView; // @synthesize avatarImageView=_avatarImageView;
@property(nonatomic) __weak T1NewsCameraGeoPickerController *currentGeoPickerViewController; // @synthesize currentGeoPickerViewController=_currentGeoPickerViewController;
@property(retain, nonatomic) NSLayoutConstraint *geoPickerButtonLeadingAnchorConstraint; // @synthesize geoPickerButtonLeadingAnchorConstraint=_geoPickerButtonLeadingAnchorConstraint;
@property(retain, nonatomic) T1NewsCameraGeoPickerButton *geoPickerButton; // @synthesize geoPickerButton=_geoPickerButton;
@property(retain, nonatomic) NSLayoutConstraint *chyronViewContentLayoutGuideTopAnchorConstraint; // @synthesize chyronViewContentLayoutGuideTopAnchorConstraint=_chyronViewContentLayoutGuideTopAnchorConstraint;
@property(retain, nonatomic) UILayoutGuide *chyronViewContentLayoutGuide; // @synthesize chyronViewContentLayoutGuide=_chyronViewContentLayoutGuide;
@property(nonatomic, getter=isChyronViewExpanded) _Bool chyronViewExpanded; // @synthesize chyronViewExpanded=_chyronViewExpanded;
@property(nonatomic) double chyronViewTransitionPercentage; // @synthesize chyronViewTransitionPercentage=_chyronViewTransitionPercentage;
@property(nonatomic) double chyronViewPositionPercentage; // @synthesize chyronViewPositionPercentage=_chyronViewPositionPercentage;
@property(retain, nonatomic) UITapGestureRecognizer *chyronViewTapGestureRecognizer; // @synthesize chyronViewTapGestureRecognizer=_chyronViewTapGestureRecognizer;
@property(copy, nonatomic) NSArray *chyronViewPercentageTransitionLayoutConstraints; // @synthesize chyronViewPercentageTransitionLayoutConstraints=_chyronViewPercentageTransitionLayoutConstraints;
@property(retain, nonatomic) NSLayoutConstraint *chyronViewTopAnchorConstraint; // @synthesize chyronViewTopAnchorConstraint=_chyronViewTopAnchorConstraint;
@property(retain, nonatomic) T1NewsCameraCaptureChyronView *chyronView; // @synthesize chyronView=_chyronView;
@property(retain, nonatomic) UILayoutGuide *expandedChyronViewLayoutGuide; // @synthesize expandedChyronViewLayoutGuide=_expandedChyronViewLayoutGuide;
@property(retain, nonatomic) NSLayoutConstraint *chyronViewLayoutGuideTopAnchorConstraint; // @synthesize chyronViewLayoutGuideTopAnchorConstraint=_chyronViewLayoutGuideTopAnchorConstraint;
@property(retain, nonatomic) UILayoutGuide *chyronViewLayoutGuide; // @synthesize chyronViewLayoutGuide=_chyronViewLayoutGuide;
@property(retain, nonatomic) UITapGestureRecognizer *chyronBackgroundViewTapGestureRecognizer; // @synthesize chyronBackgroundViewTapGestureRecognizer=_chyronBackgroundViewTapGestureRecognizer;
@property(retain, nonatomic) UIView *chyronBackgroundView; // @synthesize chyronBackgroundView=_chyronBackgroundView;
@property(nonatomic) struct CGPoint lastDraggingTranslation; // @synthesize lastDraggingTranslation=_lastDraggingTranslation;
@property(retain, nonatomic) UILongPressGestureRecognizer *contentViewLongPressGestureRecognizer; // @synthesize contentViewLongPressGestureRecognizer=_contentViewLongPressGestureRecognizer;
@property(retain, nonatomic) TFNKeyboardDismissalContainerView *keyboardDismissalContainerView; // @synthesize keyboardDismissalContainerView=_keyboardDismissalContainerView;
@property(retain, nonatomic) UILayoutGuide *controlButtonsLayoutGuide; // @synthesize controlButtonsLayoutGuide=_controlButtonsLayoutGuide;
@property(retain, nonatomic) UILayoutGuide *previewViewLayoutMarginsGuide; // @synthesize previewViewLayoutMarginsGuide=_previewViewLayoutMarginsGuide;
@property(retain, nonatomic) T1NewsCameraCapturePreviewView *previewView; // @synthesize previewView=_previewView;
@property(retain, nonatomic) T1NewsCameraThreadPreviewViewController *threadPreviewViewController; // @synthesize threadPreviewViewController=_threadPreviewViewController;
@property(retain, nonatomic) UIPanGestureRecognizer *threadPreviewContainerViewPanGestureRecognizer; // @synthesize threadPreviewContainerViewPanGestureRecognizer=_threadPreviewContainerViewPanGestureRecognizer;
@property(retain, nonatomic) UILayoutGuide *threadPreviewContainerViewLayoutMarginsGuide; // @synthesize threadPreviewContainerViewLayoutMarginsGuide=_threadPreviewContainerViewLayoutMarginsGuide;
@property(retain, nonatomic) UIView *threadPreviewContainerView; // @synthesize threadPreviewContainerView=_threadPreviewContainerView;
@property(retain, nonatomic) UIPanGestureRecognizer *previewContainerViewPanGestureRecognizer; // @synthesize previewContainerViewPanGestureRecognizer=_previewContainerViewPanGestureRecognizer;
@property(retain, nonatomic) NSLayoutConstraint *previewContainerViewThreadPreviewingLeadingAnchorConstraint; // @synthesize previewContainerViewThreadPreviewingLeadingAnchorConstraint=_previewContainerViewThreadPreviewingLeadingAnchorConstraint;
@property(retain, nonatomic) NSLayoutConstraint *previewContainerViewLeadingAnchorConstraint; // @synthesize previewContainerViewLeadingAnchorConstraint=_previewContainerViewLeadingAnchorConstraint;
@property(retain, nonatomic) UILayoutGuide *previewContainerViewLayoutMarginsGuide; // @synthesize previewContainerViewLayoutMarginsGuide=_previewContainerViewLayoutMarginsGuide;
@property(retain, nonatomic) UIView *previewContainerView; // @synthesize previewContainerView=_previewContainerView;
@property(retain, nonatomic) UILayoutGuide *viewLayoutMarginsGuide; // @synthesize viewLayoutMarginsGuide=_viewLayoutMarginsGuide;
@property(retain, nonatomic) T1NewsCameraThreadObserver *threadObserver; // @synthesize threadObserver=_threadObserver;
@property(nonatomic) unsigned long long state; // @synthesize state=_state;
@property(nonatomic, getter=isFullyPresented) _Bool fullyPresented; // @synthesize fullyPresented=_fullyPresented;
@property(nonatomic, getter=isViewFullyLoaded) _Bool viewFullyLoaded; // @synthesize viewFullyLoaded=_viewFullyLoaded;
@property(copy, nonatomic) TFSTwitterScribeContext *scribeContext; // @synthesize scribeContext=_scribeContext;
@property(nonatomic, getter=isThreadPreviewingEnabled) _Bool threadPreviewingEnabled; // @synthesize threadPreviewingEnabled=_threadPreviewingEnabled;
@property(retain, nonatomic) T1NewsCameraFetchResult *currentEventHashtagsFetchResult; // @synthesize currentEventHashtagsFetchResult=_currentEventHashtagsFetchResult;
@property(retain, nonatomic) T1NewsCameraFetchResult *currentPlacesFetchResult; // @synthesize currentPlacesFetchResult=_currentPlacesFetchResult;
@property(retain, nonatomic) T1NewsCameraCaptureOutput *captureOutput; // @synthesize captureOutput=_captureOutput;
@property(copy, nonatomic) T1NewsCameraComposition *composition; // @synthesize composition=_composition;
@property(retain, nonatomic) TFNTwitterAccount *account; // @synthesize account=_account;
@property(nonatomic) __weak id <T1NewsCameraCaptureCameraModeEditViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)tooltipDidTap:(id)arg1;
- (void)altTextViewController:(id)arg1 didCompleteWithAltText:(id)arg2;
- (void)altTextViewControllerDidCancel:(id)arg1;
- (void)newsCameraEventHashtagsViewController:(id)arg1 didChangeSelectedIndex:(long long)arg2;
- (void)geoPickerDidSelectPlaceWithPlace:(id)arg1 preciseLocation:(id)arg2;
- (void)geoPickerRequestedLocationRetry;
- (void)geoPickerRequestedDismiss;
- (void)geoPickerRequestedPresentation;
- (void)_t1_main_updateModalHitTestView;
- (void)colorPicker:(id)arg1 didSelectItemWithIdentifier:(id)arg2;
- (void)colorPickerWillSelect:(id)arg1;
- (void)modalHitTestViewDidTapModalBackgroundView:(id)arg1;
- (void)keyboardDismissalContainerView:(id)arg1 didEndDraggingWithVelocity:(struct CGPoint)arg2 state:(unsigned long long)arg3;
- (void)keyboardDismissalContainerView:(id)arg1 didChangeDraggingWithTranslation:(struct CGPoint)arg2;
- (void)keyboardDismissalContainerViewDidBeginDragging:(id)arg1;
- (_Bool)keyboardDismissalContainerView:(id)arg1 shouldBeginDraggingAtLocation:(struct CGPoint)arg2 velocity:(struct CGPoint)arg3;
- (void)keyboardDismissalContainerView:(id)arg1 keyboardDidChangeFrameInView:(struct CGRect)arg2;
- (long long)remainingCountForWarningDisplayInProgressView:(id)arg1;
- (long long)remainingCountForProgressView:(id)arg1;
- (long long)currentCountForProgressView:(id)arg1;
- (void)autocompleteViewController:(id)arg1 didSelectItem:(id)arg2;
- (void)_t1_main_updateAutocompleteViewAnimated:(_Bool)arg1;
- (void)newsCameraTweetTextEditView:(id)arg1 didUpdateAutocompleteResult:(id)arg2;
- (void)newsCameraTweetTextEditViewDidEndAutocomplete:(id)arg1;
- (void)newsCameraTweetTextEditViewDidBeginAutocomplete:(id)arg1;
- (void)_t1_main_reloadTweetTextCountProgressView;
- (void)newsCameraTweetTextEditView:(id)arg1 didChangeInputLocalIdentifier:(id)arg2;
- (void)_t1_main_updateChyronViewLayoutGuideHeight;
- (void)newsCameraTweetTextEditView:(id)arg1 didChangeText:(id)arg2;
- (void)newsCameraTweetTextEditViewDidEndEditing:(id)arg1;
- (void)newsCameraTweetTextEditViewDidBeginEditing:(id)arg1;
- (_Bool)newsCameraTweetTextEditViewShouldBeginEditing:(id)arg1;
- (void)newsCameraThreadObserver:(id)arg1 didUpdateLatestThread:(id)arg2;
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (void)_t1_gesture_chyronViewDidTap:(id)arg1;
- (void)_t1_gesture_contentViewDidLongPress:(id)arg1;
- (void)_t1_gesture_contentViewDidTap:(id)arg1;
- (void)_t1_main_updateThreadPreviewViewControllerPlayingVideo;
- (void)_t1_gesture_threadPreviewContainerViewDidPan:(id)arg1;
- (void)_t1_gesture_previewContainerViewDidPan:(id)arg1;
- (void)_t1_main_sendNewsCameraComposition:(id)arg1 withAttachment:(id)arg2 cameraScribeValue:(id)arg3 fromAccount:(id)arg4;
- (void)_t1_main_sendNewsCameraComposition;
- (void)_t1_main_peekPreviewContainerView;
- (void)_t1_action_addToThreadButtonDidTouchUpInside:(id)arg1;
- (void)_t1_action_tweetButtonDidTouchUpInside:(id)arg1;
- (void)_t1_action_addDescriptionButtonDidTouchUpInside:(id)arg1;
- (void)_t1_action_muteButtonDidTouchUpInside:(id)arg1;
- (void)_t1_action_cancelButtonDidTouchUpInside:(id)arg1;
- (void)_t1_main_updateCurrentGeoPickerViewController;
- (void)_t1_main_presentGeoPickerViewController;
- (void)_t1_main_requestsUpdateCurrentLocationWithCompletion:(CDUnknownBlockType)arg1;
- (void)_t1_action_geoPickerButtonDidTouchUpInside:(id)arg1;
- (void)_t1_main_reset;
- (void)viewControllerDidDismissAnimated:(_Bool)arg1;
- (void)viewControllerWillDismissAnimated:(_Bool)arg1;
- (void)viewControllerDidPresentAnimated:(_Bool)arg1;
- (double)lengthOfLayoutGuide:(long long)arg1 forEnvironment:(id)arg2;
- (id)scribeComponent;
- (id)scribeSection;
- (id)scribePage;
- (id)scribe;
- (void)tfn_viewControllerWillSwapWithTransitionCoordinator:(id)arg1;
- (void)tfn_addDirectlyOwnedViewControllersToMutableArray:(id)arg1;
- (void)viewDidLayoutSubviews;
- (void)_t1_main_loadEventHashtagsViewControllerWithConstraints:(id)arg1;
- (void)_t1_main_loadAvatarImageViewWithConstraints:(id)arg1;
- (void)_t1_main_loadTweetTextEditViewWithConstraints:(id)arg1;
- (void)_t1_main_loadGeoPickerButtonWithConstraints:(id)arg1;
- (void)_t1_main_updateChyronViewPercentageTransitionLayoutConstraints;
- (void)_t1_main_updateChyronViewTopAnchorConstraint;
- (void)_t1_main_loadChyronViewWithConstraints:(id)arg1;
- (void)_t1_main_loadChyronViewLayoutGuidesWithConstraints:(id)arg1;
- (void)_t1_main_loadChyronBackgroundViewWithConstraints:(id)arg1;
- (void)_t1_main_loadAutocompleteViewControllerWithConstraints:(id)arg1;
- (void)_t1_main_updateAddToThreadButtonAnimated:(_Bool)arg1;
- (void)_t1_main_loadAddToThreadButtonWithConstraints:(id)arg1;
- (void)_t1_main_loadColorPickerViewControllerWithConstraints:(id)arg1;
- (void)_t1_main_loadTweetTextCountProgressViewWithConstraints:(id)arg1;
- (void)_t1_main_loadTweetButtonWithConstraints:(id)arg1;
- (void)_t1_main_loadControlsViewWithConstraints:(id)arg1;
- (void)_t1_main_loadAddDescriptionButtonWithConstraints:(id)arg1;
- (void)_t1_main_loadMuteButtonWithConstraints:(id)arg1;
- (void)_t1_main_loadCancelButtonWithConstraints:(id)arg1;
- (void)_t1_main_loadKeyboardDismissalContainerViewWithConstraints:(id)arg1;
- (void)_t1_main_loadControlButtonsLayoutGuideWithConstraints:(id)arg1;
- (void)_t1_main_loadPreviewViewWithConstraints:(id)arg1;
- (void)_t1_main_updateThreadPreviewViewController;
- (void)_t1_main_loadThreadPreviewViewControllerWithConstraints:(id)arg1;
- (void)_t1_main_loadThreadPreviewContainerViewWithConstraints:(id)arg1;
- (void)_t1_main_updatePreviewContainerViewPanGestureRecognizer;
- (void)_t1_main_loadPreviewContainerViewWithConstraints:(id)arg1;
- (void)_t1_main_loadViewLayoutMarginsGuideWithConstraints:(id)arg1;
- (void)viewDidLoad;
- (void)loadView;
- (void)_t1_main_updateCancelButtonLayout;
- (void)_t1_main_updatePreviewContainerViewForTransitionPercentage:(double)arg1;
- (void)setPreviewContainerViewTransitionPosition:(double)arg1 animated:(_Bool)arg2 withVelocity:(double)arg3;
@property(nonatomic) double previewContainerViewTransitionPosition;
- (void)_t1_main_updateTweetTextCountProgressViewAnimated:(_Bool)arg1;
- (void)_t1_main_updateControlsAnimated:(_Bool)arg1;
- (void)_t1_main_updateTweetTextEditViewBorders;
- (void)_t1_main_updateChyronViewPercentageTransition;
- (void)_t1_main_updateChyronViewPercentagePosition;
- (void)setChyronViewPositionPercentage:(double)arg1 animated:(_Bool)arg2;
- (void)_t1_main_updateForEventHashtagsAnimated:(_Bool)arg1;
- (void)_t1_main_updateEventHashtagsViewAnimated:(_Bool)arg1;
- (void)_t1_main_updateAddDescriptionButton;
- (void)_t1_main_updateMuteButton;
- (void)_t1_main_updateCancelButton;
- (void)_t1_main_updateTweetButton;
- (void)_t1_main_updateThreadPreviewViewControllerControlsArea;
- (void)_t1_main_updatePreviewView;
- (void)_t1_main_updateForEventHashtag;
- (void)_t1_main_updateForPlace;
- (void)_t1_main_updateForThread;
- (void)_t1_main_updateForCameraPaletteID;
- (void)_t1_main_updateForText;
- (void)_t1_main_storeLastSelectedCameraPaletteID:(id)arg1;
- (void)_t1_main_restoreLastSelectedCameraPaletteID;
- (void)_t1_main_updateThreadObserverDisabled;
- (void)_t1_main_updateThreadObserver;
- (void)_t1_main_updateAutocompleteViewController;
- (void)_t1_main_updateTweetTextEditView;
- (void)_t1_main_updateAvatarImageView;
- (void)_t1_main_triggerMuteButtonTooltip;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(retain, nonatomic) TFNModalHitTestView *view; // @dynamic view;

@end

