//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <T1Twitter/T1OnboardingSubtaskController.h>

#import <T1Twitter/T1UsernameViewControllerDelegate-Protocol.h>

@class NSString, T1UpdateUsernameViewController, TFNOnboardingEnterUsernameSubtask, TFNOnboardingEnterUsernameSubtaskState, TFNOnboardingRichText;
@protocol T1OnboardingSubtaskControllerDelegate;

@interface T1OnboardingEnterUsernameSubtaskController : T1OnboardingSubtaskController <T1UsernameViewControllerDelegate>
{
    TFNOnboardingEnterUsernameSubtask *_subtask;
    TFNOnboardingEnterUsernameSubtaskState *_state;
    id <T1OnboardingSubtaskControllerDelegate> _delegate;
    T1UpdateUsernameViewController *_updateUsernameViewController;
    long long _detailTextIndex;
}

- (void).cxx_destruct;
- (void)usernameViewController:(id)arg1 didTapActiveTextRange:(id)arg2 inRect:(struct CGRect)arg3;
- (void)usernameViewControllerDidTapCancel:(id)arg1;
- (void)usernameViewControllerDidTapSubmit:(id)arg1;
@property(readonly, nonatomic) TFNOnboardingRichText *currentDetailRichText;
- (void)restartWithNavigationContext:(id)arg1 navigationLink:(id)arg2;
- (void)startWithNavigationContext:(id)arg1 navigationLink:(id)arg2;
- (id)initWithSubtask:(id)arg1 delegate:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

