//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import <T1Twitter/UIScrollViewDelegate-Protocol.h>

@class NSString, T1CustomPhotoEditViewController, T1PhotoEditGuideView, UIImage, UIImageView, UIScrollView;

@interface T1PhotoEditView : UIView <UIScrollViewDelegate>
{
    T1PhotoEditGuideView *_guideView;
    UIImageView *_imageView;
    UIScrollView *_scrollView;
    UIImage *_image;
    T1CustomPhotoEditViewController *_editController;
    double _maxWidth;
    struct CGSize _previewCropSize;
}

@property(readonly, nonatomic) double maxWidth; // @synthesize maxWidth=_maxWidth;
@property(nonatomic) struct CGSize previewCropSize; // @synthesize previewCropSize=_previewCropSize;
@property(nonatomic) __weak T1CustomPhotoEditViewController *editController; // @synthesize editController=_editController;
@property(retain, nonatomic) UIImage *image; // @synthesize image=_image;
- (void).cxx_destruct;
- (double)_calculateMinimumZoomScale:(struct CGSize)arg1;
- (void)_centerContent;
- (id)viewForZoomingInScrollView:(id)arg1;
- (id)scaledImage;
- (void)layoutSubviews;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1 image:(id)arg2 previewCropSize:(struct CGSize)arg3 purpose:(unsigned long long)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

