//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewHeaderFooterView.h>

@class UIButton, UILabel, UITableView, UIView;
@protocol T1SuggestsModuleHeaderViewDelegate;

@interface T1SuggestsModuleHeaderView : UITableViewHeaderFooterView
{
    UITableView *_tableView;
    UIButton *_caretButton;
    UILabel *_headerTextLabel;
    UILabel *_detailHeaderTextLabel;
    UIView *_topSeparator;
    UIView *_bottomSeparator;
    id <T1SuggestsModuleHeaderViewDelegate> _delegate;
}

+ (double)heightWithViewMode:(long long)arg1;
+ (id)reuseIdentifier;
@property(nonatomic) __weak id <T1SuggestsModuleHeaderViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) UIView *bottomSeparator; // @synthesize bottomSeparator=_bottomSeparator;
@property(readonly, nonatomic) UIView *topSeparator; // @synthesize topSeparator=_topSeparator;
@property(readonly, nonatomic) UILabel *detailHeaderTextLabel; // @synthesize detailHeaderTextLabel=_detailHeaderTextLabel;
@property(readonly, nonatomic) UILabel *headerTextLabel; // @synthesize headerTextLabel=_headerTextLabel;
@property(readonly, nonatomic) UIButton *caretButton; // @synthesize caretButton=_caretButton;
- (void).cxx_destruct;
- (id)calculatedLayoutMetrics;
- (void)_caretButtonWasPressed:(id)arg1;
- (void)layoutSubviews;
- (void)didMoveToSuperview;
- (id)initWithReuseIdentifier:(id)arg1;

@end

