//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <TFNUI/TFNAttributedTextView.h>

@class T1TweetDetailsFooterItem, T1TweetDetailsFooterItemPlaceRange, T1TweetDetailsFooterItemSourceRange, T1TweetDetailsFooterItemTimestampRange;

@interface T1TweetDetailsFooterTextView : TFNAttributedTextView
{
    T1TweetDetailsFooterItem *_footerItem;
    T1TweetDetailsFooterItemTimestampRange *_activeTimestampRange;
    T1TweetDetailsFooterItemPlaceRange *_activePlaceRange;
    T1TweetDetailsFooterItemSourceRange *_activeSourceRange;
}

@property(retain, nonatomic) T1TweetDetailsFooterItemSourceRange *activeSourceRange; // @synthesize activeSourceRange=_activeSourceRange;
@property(retain, nonatomic) T1TweetDetailsFooterItemPlaceRange *activePlaceRange; // @synthesize activePlaceRange=_activePlaceRange;
@property(retain, nonatomic) T1TweetDetailsFooterItemTimestampRange *activeTimestampRange; // @synthesize activeTimestampRange=_activeTimestampRange;
@property(retain, nonatomic) T1TweetDetailsFooterItem *footerItem; // @synthesize footerItem=_footerItem;
- (void).cxx_destruct;
- (id)_t1_joinerAttributedString;
- (id)_t1_sourceAttributedString;
- (id)_t1_locationAttributedString;
- (id)_t1_timestampAttributedString;
- (void)_t1_updateFooterTextView;
- (void)layoutMetricsDidChange:(id)arg1;
- (void)updateFontSize;

@end

