//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <TFSUtilities/TFSConcurrentOperation.h>

@class TSPSession, TSPSignedPreKey;
@protocol TFNDirectMessageCommitSignedPreKeyOperationDelegate;

@interface TFNDirectMessageCommitSignedPreKeyOperation : TFSConcurrentOperation
{
    TSPSignedPreKey *_signedPreKey;
    TSPSession *_session;
    id <TFNDirectMessageCommitSignedPreKeyOperationDelegate> _delegate;
}

@property __weak id <TFNDirectMessageCommitSignedPreKeyOperationDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) TSPSession *session; // @synthesize session=_session;
@property(retain) TSPSignedPreKey *signedPreKey; // @synthesize signedPreKey=_signedPreKey;
- (void).cxx_destruct;
- (void)run;
- (id)initWithSignalProtocolSession:(id)arg1;

@end

