//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <T1Twitter/NSCoding-Protocol.h>
#import <T1Twitter/TFNDirectMessageCryptographyServiceObserver-Protocol.h>
#import <T1Twitter/TFNDirectMessageInboxActions-Protocol.h>

@class NSNumber, NSOperationQueue, NSString, TFNDirectMessageContext, TFNDirectMessageCryptographyService, TFNDirectMessageInboxPageOperation, TFNDirectMessageInboxTimeline, TFNDirectMessageKeyRegistryState, TFNDirectMessageModel, TFNDirectMessageRefreshOperation, TFSCoalescingUpdater;
@protocol TFNDirectMessageInbox;

@interface TFNDirectMessageInbox : NSObject <TFNDirectMessageCryptographyServiceObserver, NSCoding, TFNDirectMessageInboxActions>
{
    _Bool _keyRegistryServiceEnabled;
    TFNDirectMessageContext *_context;
    NSOperationQueue *_directMessageOperationQueue;
    TFNDirectMessageCryptographyService *_cryptographyService;
    TFNDirectMessageModel *_directMessageModel;
    NSNumber *_lastLowQualityFilterState;
    long long _lastSeenEventID;
    NSString *_cursor;
    TFNDirectMessageInboxTimeline *_trustedConversationsTimeline;
    TFNDirectMessageInboxTimeline *_untrustedConversationsTimeline;
    TFSCoalescingUpdater *_markAsSeenUpdater;
    long long _localLastSeenEventID;
    unsigned long long _countOfUnseenConversations;
    TFNDirectMessageKeyRegistryState *_remoteKeyRegistryState;
    TFNDirectMessageRefreshOperation *_currentRefreshOperation;
    TFNDirectMessageInboxPageOperation *_currentTrustedConversationsPageOperation;
    TFNDirectMessageInboxPageOperation *_currentUntrustedConversationsPageOperation;
}

@property(nonatomic) __weak TFNDirectMessageInboxPageOperation *currentUntrustedConversationsPageOperation; // @synthesize currentUntrustedConversationsPageOperation=_currentUntrustedConversationsPageOperation;
@property(nonatomic) __weak TFNDirectMessageInboxPageOperation *currentTrustedConversationsPageOperation; // @synthesize currentTrustedConversationsPageOperation=_currentTrustedConversationsPageOperation;
@property(nonatomic) __weak TFNDirectMessageRefreshOperation *currentRefreshOperation; // @synthesize currentRefreshOperation=_currentRefreshOperation;
@property(retain, nonatomic) TFNDirectMessageKeyRegistryState *remoteKeyRegistryState; // @synthesize remoteKeyRegistryState=_remoteKeyRegistryState;
@property(nonatomic) unsigned long long countOfUnseenConversations; // @synthesize countOfUnseenConversations=_countOfUnseenConversations;
@property(nonatomic) long long localLastSeenEventID; // @synthesize localLastSeenEventID=_localLastSeenEventID;
@property(readonly, nonatomic) TFSCoalescingUpdater *markAsSeenUpdater; // @synthesize markAsSeenUpdater=_markAsSeenUpdater;
@property(retain, nonatomic) TFNDirectMessageInboxTimeline *untrustedConversationsTimeline; // @synthesize untrustedConversationsTimeline=_untrustedConversationsTimeline;
@property(retain, nonatomic) TFNDirectMessageInboxTimeline *trustedConversationsTimeline; // @synthesize trustedConversationsTimeline=_trustedConversationsTimeline;
@property(copy, nonatomic) NSString *cursor; // @synthesize cursor=_cursor;
@property(nonatomic) long long lastSeenEventID; // @synthesize lastSeenEventID=_lastSeenEventID;
@property(retain, nonatomic) NSNumber *lastLowQualityFilterState; // @synthesize lastLowQualityFilterState=_lastLowQualityFilterState;
@property(nonatomic) _Bool keyRegistryServiceEnabled; // @synthesize keyRegistryServiceEnabled=_keyRegistryServiceEnabled;
@property(retain, nonatomic) TFNDirectMessageModel *directMessageModel; // @synthesize directMessageModel=_directMessageModel;
@property(retain, nonatomic) NSOperationQueue *directMessageOperationQueue; // @synthesize directMessageOperationQueue=_directMessageOperationQueue;
@property(readonly, nonatomic) TFNDirectMessageContext *context; // @synthesize context=_context;
- (void).cxx_destruct;
- (void)_enqueueMetadataUpdateNotification;
- (void)_enqueueTimelineUpdateNotification;
- (void)deleteConversation:(id)arg1;
- (void)recalculateConversationCounts;
- (void)updateConversationPosition:(id)arg1;
- (void)slotConversationInTimeline:(id)arg1;
- (void)addConversation:(id)arg1;
- (id)_validateConversationIsDefinitive:(id)arg1;
- (void)_addConversation:(id)arg1;
- (void)cryptographyService:(id)arg1 updatedRemoteKeyRegistryState:(id)arg2;
- (void)registerForEncryptedDMsWithCompletion:(CDUnknownBlockType)arg1;
- (void)pruneOldConversations;
- (void)fetchPermissionForUsername:(id)arg1 encryptedDM:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (void)fetchPermissionForUserID:(long long)arg1 encryptedDM:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (void)_markAsSeen;
- (void)markAsSeenThroughConversation:(id)arg1;
- (void)markAsSeen;
- (void)loadMoreConversationsWithCursor:(id)arg1;
- (void)refresh:(long long)arg1 activeConversationID:(id)arg2 keyRegistryServiceEnabled:(_Bool)arg3 filterLowQuality:(id)arg4 completion:(CDUnknownBlockType)arg5;
@property(readonly, nonatomic, getter=isRefreshing) _Bool refreshing;
@property(readonly, nonatomic) id <TFNDirectMessageInbox> inbox;
- (void)setKeyRegistryState:(id)arg1;
@property(readonly, nonatomic) TFNDirectMessageKeyRegistryState *keyRegistryState;
@property(readonly, nonatomic) unsigned long long keyRegistryStatus;
- (id)conversationByID:(id)arg1;
@property(readonly, nonatomic) long long maxSortEventID;
@property(readonly, nonatomic, getter=isEmpty) _Bool empty;
@property(readonly, nonatomic, getter=isLoaded) _Bool loaded;
@property(readonly, nonatomic) _Bool filtersLowQualityConversations;
- (id)internalUntrustedConversationsTimeline;
- (id)internalTrustedConversationsTimeline;
@property(readonly, nonatomic) TFNDirectMessageCryptographyService *cryptographyService; // @synthesize cryptographyService=_cryptographyService;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)schedulePendingActions;
- (void)clear;
- (id)initWithContext:(id)arg1 cursor:(id)arg2 lastSeenEventID:(long long)arg3 trustedConversationsTimeline:(id)arg4 untrustedConversationsTimeline:(id)arg5 keyRegistryServiceEnabled:(_Bool)arg6 lastLowQualityFilterState:(id)arg7 keyRegistryState:(id)arg8;
- (id)initWithContext:(id)arg1;
- (void)flushMarkAsSeen;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

