//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface TFNOnboardingSubtask : NSObject
{
    _Bool _suppressClientEvents;
    NSString *_subtaskID;
    long long _backNavigationType;
    NSString *_typeName;
}

+ (long long)version;
+ (id)typeNames;
@property(readonly, nonatomic) _Bool suppressClientEvents; // @synthesize suppressClientEvents=_suppressClientEvents;
@property(readonly, nonatomic) NSString *typeName; // @synthesize typeName=_typeName;
@property(readonly, nonatomic) long long backNavigationType; // @synthesize backNavigationType=_backNavigationType;
@property(readonly, nonatomic) NSString *subtaskID; // @synthesize subtaskID=_subtaskID;
- (void).cxx_destruct;
@property(readonly, nonatomic) long long preferredPresentationType;
- (id)initWithJSONDictionary:(id)arg1 subtaskID:(id)arg2 typeName:(id)arg3 backNavigationType:(long long)arg4 error:(id *)arg5;

@end

