//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <T1Twitter/TFNOnboardingSubtask.h>

@class NSArray, NSString, TFNOnboardingNavigationLink, TFNOnboardingRichText;

@interface TFNOnboardingInterestPickerSubtask : TFNOnboardingSubtask
{
    _Bool _hideSearch;
    TFNOnboardingRichText *_primaryText;
    TFNOnboardingRichText *_secondaryText;
    TFNOnboardingRichText *_searchHeaderText;
    NSString *_searchHint;
    NSString *_customInterestsHeader;
    NSArray *_groups;
    NSArray *_selectedItems;
    TFNOnboardingNavigationLink *_nextLink;
    TFNOnboardingNavigationLink *_skipLink;
}

+ (long long)version;
+ (id)typeNames;
@property(readonly, nonatomic) TFNOnboardingNavigationLink *skipLink; // @synthesize skipLink=_skipLink;
@property(readonly, nonatomic) TFNOnboardingNavigationLink *nextLink; // @synthesize nextLink=_nextLink;
@property(copy, nonatomic) NSArray *selectedItems; // @synthesize selectedItems=_selectedItems;
@property(readonly, nonatomic) NSArray *groups; // @synthesize groups=_groups;
@property(readonly, nonatomic) NSString *customInterestsHeader; // @synthesize customInterestsHeader=_customInterestsHeader;
@property(readonly, nonatomic) _Bool hideSearch; // @synthesize hideSearch=_hideSearch;
@property(readonly, nonatomic) NSString *searchHint; // @synthesize searchHint=_searchHint;
@property(readonly, nonatomic) TFNOnboardingRichText *searchHeaderText; // @synthesize searchHeaderText=_searchHeaderText;
@property(readonly, nonatomic) TFNOnboardingRichText *secondaryText; // @synthesize secondaryText=_secondaryText;
@property(readonly, nonatomic) TFNOnboardingRichText *primaryText; // @synthesize primaryText=_primaryText;
- (void).cxx_destruct;
- (id)initWithJSONDictionary:(id)arg1 subtaskID:(id)arg2 typeName:(id)arg3 backNavigationType:(long long)arg4 error:(id *)arg5;

@end

