//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSCache, NSDate;

@interface TFNTwitterStickerManager : NSObject
{
    NSCache *_cachedStickersByID;
    NSDate *_dateOfLastInvalidStickerCheck;
}

+ (id)sharedStickerManager;
@property(retain, nonatomic) NSDate *dateOfLastInvalidStickerCheck; // @synthesize dateOfLastInvalidStickerCheck=_dateOfLastInvalidStickerCheck;
@property(readonly, nonatomic) NSCache *cachedStickersByID; // @synthesize cachedStickersByID=_cachedStickersByID;
- (void).cxx_destruct;
- (void)_fetchInvalidStickerIDsWithAccountID:(id)arg1 invalidatedSinceDate:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)fetchAndRemoveInvalidStickersFromStickerCacheIfOlderThanLastInvalidatedDate:(id)arg1 accountID:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)_removeStickerIDFromCache:(id)arg1;
- (void)_cacheSticker:(id)arg1;
- (void)fetchPlacedStickersForStickerAssets:(id)arg1 accountID:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)_fetchStickersForStickerAssets:(id)arg1 accountID:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)fetchStickerForStickerID:(id)arg1 accountID:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (id)init;

@end

