//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <T1Twitter/NSObject-Protocol.h>

@class NSError, TFNTwitterGapItem;

@protocol TFNTwitterLoadableStream <NSObject>
@property(readonly, nonatomic) _Bool isAtEnd;
@property(readonly, nonatomic) _Bool isIdle;
- (_Bool)retryForError:(NSError *)arg1 withSource:(long long)arg2;
- (NSError *)errorForPosition:(unsigned long long)arg1;
- (_Bool)isLoadingPosition:(unsigned long long)arg1;
- (_Bool)loadPosition:(unsigned long long)arg1 source:(long long)arg2 gapItem:(TFNTwitterGapItem *)arg3;
- (_Bool)loadPosition:(unsigned long long)arg1 source:(long long)arg2;
@end

