//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class TFNTwitterAccount, TFNTwitterNewsCameraThread, TFNTwitterStatus;

@interface TFNTwitterNewsCameraMoments : NSObject
{
    _Bool _latestNewsCameraTweetUpdated;
    _Bool _latestNewsCameraThreadUpdated;
    TFNTwitterAccount *_account;
    TFNTwitterStatus *_latestNewsCameraTweet;
    TFNTwitterNewsCameraThread *_latestNewsCameraThread;
}

@property(nonatomic, getter=isLatestNewsCameraThreadUpdated) _Bool latestNewsCameraThreadUpdated; // @synthesize latestNewsCameraThreadUpdated=_latestNewsCameraThreadUpdated;
@property(retain, nonatomic) TFNTwitterNewsCameraThread *latestNewsCameraThread; // @synthesize latestNewsCameraThread=_latestNewsCameraThread;
@property(nonatomic, getter=isLatestNewsCameraTweetUpdated) _Bool latestNewsCameraTweetUpdated; // @synthesize latestNewsCameraTweetUpdated=_latestNewsCameraTweetUpdated;
@property(retain, nonatomic) TFNTwitterStatus *latestNewsCameraTweet; // @synthesize latestNewsCameraTweet=_latestNewsCameraTweet;
@property(readonly, nonatomic) __weak TFNTwitterAccount *account; // @synthesize account=_account;
- (void).cxx_destruct;
- (void)_ftn_main_updateWithCompositionPersistenceManagerChangedNotification:(id)arg1;
- (void)_tfn_notification_compositionPersistenceManagerDidRemoveOutboxComposition:(id)arg1;
- (void)_tfn_notification_compositionPersistenceManagerDidAddOutboxComposition:(id)arg1;
- (void)_tfn_notification_compositionPersistenceManagerDidRemoveDraftComposition:(id)arg1;
- (void)_tfn_notification_compositionPersistenceManagerDidAddDraftComposition:(id)arg1;
- (void)latestNewsCameraThreadWithCompletion:(CDUnknownBlockType)arg1;
- (void)_tfn_main_postChangeNotification;
- (void)_tfn_main_addCompositionPersistenceManagerObservers;
- (void)_tfn_main_updateLatestNewsCameraThread;
- (void)_tfn_main_lastKnownLatestNewsCameraTweetWithCompletion:(CDUnknownBlockType)arg1;
- (void)_tfn_main_latestNewsCameraTweetWithCompletion:(CDUnknownBlockType)arg1;
- (void)updateWithLatestNewsCameraTweet:(id)arg1;
- (void)syncLatestNewsCameraMoment;
- (id)initWithAccount:(id)arg1;
- (id)init;

@end

