//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class T1DashSplitViewController;

@interface UIViewController (T1DashSplitViewController)
- (void)t1_dashContainerWillResignActive;
- (void)t1_dashContainerWillBecomeActive;
- (void)t1_dashContainerActivateTransitionEnded:(_Bool)arg1;
- (void)t1_dashContainerActivateTransitionBegan;
@property(readonly, nonatomic) _Bool t1_statusBarAppearanceEnabledWhenTransitionBegan;
@property(readonly, nonatomic) T1DashSplitViewController *t1_dashSplitViewController;
@end

