//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <T1Twitter/_TtC9T1Twitter28SurveyCardPageLayoutableView.h>

__attribute__((visibility("hidden")))
@interface _TtC9T1Twitter26SurveyCardQuestionPageView : _TtC9T1Twitter28SurveyCardPageLayoutableView
{
    // Error parsing type: , name: titleLabel.storage
    // Error parsing type: , name: questionIndexLabel.storage
    // Error parsing type: , name: choicesStackView.storage
    // Error parsing type: , name: selectedChoices
    // Error parsing type: , name: pageInfo
    // Error parsing type: , name: question
    // Error parsing type: , name: fullScreen
    // Error parsing type: , name: randomSeed
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

