//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

__attribute__((visibility("hidden")))
@interface _TtC9T1Twitter34URTMomentCoverFollowableMomentView : UIView
{
    // Error parsing type: , name: coverViewModel
    // Error parsing type: , name: capsuleDataManager
    // Error parsing type: , name: followableMomentLabel
    // Error parsing type: , name: scribeDelegate
    // Error parsing type: , name: viewIdentifier
    // Error parsing type: , name: followableMomentButton
}

- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)didPressFollowButton;
- (void)momentSubcriptionStatusUpdated:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

