//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <TFNUI/TFNItemsDataViewController.h>

@class TFNTwitterAccount;

__attribute__((visibility("hidden")))
@interface _TtC9T1Twitter47DirectMessageConversationSettingsViewController : TFNItemsDataViewController
{
    // Error parsing type: , name: account
    // Error parsing type: , name: conversation
    // Error parsing type: , name: adminTwitterUser
    // Error parsing type: , name: shouldShowAdminItem
    // Error parsing type: , name: addPeopleBehavior.storage
    // Error parsing type: , name: encryptedConversationBanner.storage
    // Error parsing type: , name: activeDevicePromptManager
    // Error parsing type: , name: canEncryptedDMRecipient
    // Error parsing type: , name: isRegisteringDevice
    // Error parsing type: , name: isFetchingEncryptedConversationPermissions
    // Error parsing type: , name: encryptedConversationButtonIndexPath
    // Error parsing type: , name: startEncryptedConversationLabel
    // Error parsing type: , name: cannotStartEncryptedConversationLabel
}

- (void).cxx_destruct;
- (id)initWithCollectionViewLayout:(id)arg1;
- (id)scribeSection;
- (id)scribePage;
- (void)blockStatusUpdated:(id)arg1;
- (void)editGroupInfoWithSender:(id)arg1;
- (id)tableViewCellForItem:(id)arg1 atIndexPath:(id)arg2;
- (_Bool)shouldSelectItem:(id)arg1 atIndexPath:(id)arg2;
- (void)update:(_Bool)arg1;
- (void)tfn_fontSizeChanged;
- (void)viewDidLayoutSubviews;
- (void)viewWillFullyDisappear:(_Bool)arg1;
- (void)viewWillFullyAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)setEditing:(_Bool)arg1 animated:(_Bool)arg2;
@property(nonatomic, readonly) TFNTwitterAccount *account; // @synthesize account;

@end

