//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSBlockOperation.h>

@interface NSBlockOperation (TFNPrefetching)
+ (id)mainQueuePrefetchingOperationWithBlock:(CDUnknownBlockType)arg1;
+ (id)prefetchingOperationOnQueue:(id)arg1 withBlock:(CDUnknownBlockType)arg2;
@end

