//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <T1Twitter/NSObject-Protocol.h>

@class NSSet, NSString, NSURL, PTVAPIResponseErrorInfo, PTVBroadcast, PTVMergeParticipantUser, UIImage, UIView, UIViewController;

@protocol PTVTwitterCameraLiveDelegate <NSObject>
- (NSURL *)twitterCameraLiveCopyrightViolationLearnMoreURL;

@optional
- (_Bool)twitterCameraLiveIsGuestBroadcastingCreationEnabled;
- (double)twitterCameraLiveGuestViewsTopMargin;
- (void)twitterCameraLiveDidDismissCopyrightViewController;
- (void)twitterCameraLiveDidObserveAuthErrorWithInfo:(PTVAPIResponseErrorInfo *)arg1;
- (void)twitterCameraLiveDidDetectCopyrightViolation;
- (_Bool)twitterCameraLiveCopyrightViolationMatchingEnabled;
- (UIViewController *)twitterCameraLiveViewControllerForProfileFollow:(NSString *)arg1;
- (void)twitterCameraLiveDeleteBroadcast:(PTVBroadcast *)arg1;
- (void)twitterCameraLiveDidStopBroadcast:(PTVBroadcast *)arg1;
- (void)twitterCameraLiveDidStartBroadcast:(PTVBroadcast *)arg1;
- (NSSet *)twitterCameraLiveBlockedTwitterIDs;
- (void)twitterCameraLiveDidUnblockUser:(PTVMergeParticipantUser *)arg1;
- (void)twitterCameraLiveDidBlockUser:(PTVMergeParticipantUser *)arg1;
- (void)twitterCameraLiveRetweetBroadcast:(PTVBroadcast *)arg1 withCompletion:(void (^)(_Bool, NSError *))arg2;
- (_Bool)twitterCameraLiveCanRetweetBroadcast:(PTVBroadcast *)arg1;
- (void)twitterCameraLiveReportBroadcast:(PTVBroadcast *)arg1;
- (void)twitterCameraLiveShareScreenshot:(UIImage *)arg1 forBroadcast:(PTVBroadcast *)arg2;
- (void)twitterCameraLiveShareURLOfBroadcast:(PTVBroadcast *)arg1 atTimecode:(double)arg2 initialTimecode:(double)arg3 fromRect:(struct CGRect)arg4 inView:(UIView *)arg5 withCompletion:(void (^)(_Bool, NSError *))arg6;
- (void)twitterCameraLiveComposeDirectMessageForBroadcast:(PTVBroadcast *)arg1 atTimecode:(double)arg2 initialTimecode:(double)arg3 fromRect:(struct CGRect)arg4 inView:(UIView *)arg5 withCompletion:(void (^)(_Bool, NSError *))arg6;
- (void)twitterCameraLiveComposeTweetForBroadcast:(PTVBroadcast *)arg1 atTimecode:(double)arg2 initialTimecode:(double)arg3 fromRect:(struct CGRect)arg4 inView:(UIView *)arg5 withCompletion:(void (^)(_Bool, NSError *))arg6;
- (_Bool)twitterCameraLiveCanShareBroadcast;
- (void)twitterCameraLiveBroadcastCapabilityChanged:(long long)arg1;
@end

