//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import <T1Twitter/T1CampaignMetadataFieldViewDelegate-Protocol.h>

@class NSString, T1CampaignMetadataFieldView;
@protocol T1CampaignMetadataViewDelegate;

@interface T1CampaignMetadataView : UIView <T1CampaignMetadataFieldViewDelegate>
{
    id <T1CampaignMetadataViewDelegate> _delegate;
    T1CampaignMetadataFieldView *_impressionsView;
    T1CampaignMetadataFieldView *_engagementsView;
    UIView *_verticalDividerView;
    UIView *_horizontalDividerView;
}

+ (struct UIEdgeInsets)baselineEdgeInsetsForDefaultFont:(id)arg1;
+ (double)desiredHeight;
@property(retain, nonatomic) UIView *horizontalDividerView; // @synthesize horizontalDividerView=_horizontalDividerView;
@property(retain, nonatomic) UIView *verticalDividerView; // @synthesize verticalDividerView=_verticalDividerView;
@property(retain, nonatomic) T1CampaignMetadataFieldView *engagementsView; // @synthesize engagementsView=_engagementsView;
@property(retain, nonatomic) T1CampaignMetadataFieldView *impressionsView; // @synthesize impressionsView=_impressionsView;
@property(nonatomic) __weak id <T1CampaignMetadataViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)campaignMetadataFieldViewDidTap:(id)arg1;
- (void)updateWithCampaignMetadata:(id)arg1;
- (void)layoutSubviews;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

