//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSString, TFNTwitterAccount, TFNTwitterComposition;

@interface T1ComposeSessionConfig : NSObject
{
    _Bool _didOpenComposer;
    _Bool _didShowFoundMediaTooltip;
    _Bool _didRequestCameraAuthorization;
    long long _cameraAuthorizationStatus;
    _Bool _didOpenCamera;
    _Bool _cameraDidCancel;
    _Bool _didOpenPeriscopeBroadcast;
    _Bool _wantPoll;
    _Bool _wantStartFromCamera;
    _Bool _wantStartFromVideo;
    _Bool _wantFoundMediaTooltip;
    _Bool _wantStartFromPeriscopeBroadcast;
    _Bool _wantPresentOverModal;
    NSArray *_initialCompositions;
    NSString *_scribePage;
    CDUnknownBlockType _dismissCompletionBlock;
    TFNTwitterAccount *_account;
}

@property(nonatomic) _Bool wantPresentOverModal; // @synthesize wantPresentOverModal=_wantPresentOverModal;
@property(nonatomic) _Bool wantStartFromPeriscopeBroadcast; // @synthesize wantStartFromPeriscopeBroadcast=_wantStartFromPeriscopeBroadcast;
@property(nonatomic) _Bool wantFoundMediaTooltip; // @synthesize wantFoundMediaTooltip=_wantFoundMediaTooltip;
@property(nonatomic) _Bool wantStartFromVideo; // @synthesize wantStartFromVideo=_wantStartFromVideo;
@property(nonatomic) _Bool wantStartFromCamera; // @synthesize wantStartFromCamera=_wantStartFromCamera;
@property(nonatomic) _Bool wantPoll; // @synthesize wantPoll=_wantPoll;
@property(retain, nonatomic) TFNTwitterAccount *account; // @synthesize account=_account;
@property(copy, nonatomic) CDUnknownBlockType dismissCompletionBlock; // @synthesize dismissCompletionBlock=_dismissCompletionBlock;
@property(retain, nonatomic) NSString *scribePage; // @synthesize scribePage=_scribePage;
@property(copy, nonatomic) NSArray *initialCompositions; // @synthesize initialCompositions=_initialCompositions;
- (void).cxx_destruct;
- (void)didOpenPeriscopeBroadcast;
- (_Bool)_shouldEnterPeriscopeMode;
@property(readonly, nonatomic) _Bool shouldOpenPeriscopeBroadcast;
- (void)cameraDidCancel;
- (void)cameraDidSelectAttachment:(id)arg1;
@property(readonly, nonatomic) long long cameraModeForCustomCamera;
@property(readonly, nonatomic) _Bool shouldOpenNativeCamera;
@property(readonly, nonatomic) _Bool shouldOpenCustomCamera;
- (_Bool)_shouldOpenCamera;
- (void)didRequestCameraAuthorization:(long long)arg1;
@property(readonly, nonatomic) _Bool shouldRequestCameraAuthorization;
- (_Bool)_isCameraAuthorized;
- (_Bool)_shouldEnterVideoMode;
- (_Bool)_shouldEnterCameraMode;
- (_Bool)_deviceHasCamera;
- (void)didShowFoundMediaTooltip;
@property(readonly, nonatomic) _Bool shouldShowFoundMediaTooltip;
@property(readonly, nonatomic) _Bool shouldDismissModal;
- (void)didOpenComposer;
@property(readonly, nonatomic) _Bool shouldOpenComposer;
@property(readonly, nonatomic) _Bool shouldAddPoll;
@property(readonly, nonatomic) TFNTwitterComposition *initialComposition;
- (id)init;

@end

