//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@protocol T1DirectMessageActiveDevicePromptDelegate;

@interface T1DirectMessageActiveDevicePromptManager : NSObject
{
    // Error parsing type: , name: isDisplayingPrompt
    // Error parsing type: , name: account
    // Error parsing type: , name: delegate
}

- (void).cxx_destruct;
- (id)init;
- (void)displayPrompt;
- (void)displayPromptIfNeeded;
- (id)initWithAccount:(id)arg1;
@property(nonatomic) __weak id <T1DirectMessageActiveDevicePromptDelegate> delegate; // @synthesize delegate;

@end

