//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <T1Twitter/T1PushNotificationAmbientNotificationStrategy-Protocol.h>
#import <T1Twitter/TFNDirectMessageServiceRefreshObserver-Protocol.h>

@class NSMutableArray, NSString, TFNDirectMessageService, TFNTwitterAccount;
@protocol TFNDirectMessageConversation;

@interface T1DirectMessageRefreshController : NSObject <TFNDirectMessageServiceRefreshObserver, T1PushNotificationAmbientNotificationStrategy>
{
    _Bool _updateRefreshIntervalSucceeded;
    TFNTwitterAccount *_activeAccount;
    NSMutableArray *_pendingAmbientNotifications;
    unsigned long long _activeViewState;
    id <TFNDirectMessageConversation> _activeConversation;
}

+ (id)sharedDirectMessageRefreshController;
+ (void)load;
@property(nonatomic) _Bool updateRefreshIntervalSucceeded; // @synthesize updateRefreshIntervalSucceeded=_updateRefreshIntervalSucceeded;
@property(retain, nonatomic) id <TFNDirectMessageConversation> activeConversation; // @synthesize activeConversation=_activeConversation;
@property(nonatomic) unsigned long long activeViewState; // @synthesize activeViewState=_activeViewState;
@property(retain, nonatomic) NSMutableArray *pendingAmbientNotifications; // @synthesize pendingAmbientNotifications=_pendingAmbientNotifications;
@property(retain, nonatomic) TFNTwitterAccount *activeAccount; // @synthesize activeAccount=_activeAccount;
- (void).cxx_destruct;
- (_Bool)_inActiveApplicationState;
- (void)_inboxDidRefresh:(id)arg1;
- (void)_processPendingAmbientNotifications;
- (void)_clearPendingAmbientNotifications;
- (void)_activeAccountDidChange:(id)arg1;
- (void)_updateRefreshInterval;
- (void)setActiveViewState:(unsigned long long)arg1 activeConversation:(id)arg2;
@property(readonly, nonatomic, getter=isRefreshing) _Bool refreshing;
@property(readonly, nonatomic) TFNDirectMessageService *service;
- (void)enqueueAmbientPushNotification:(id)arg1 tapHandler:(CDUnknownBlockType)arg2 account:(id)arg3;
- (void)refreshWithService:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)start;
- (void)refreshWithLoadSource:(long long)arg1 completion:(CDUnknownBlockType)arg2;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

