//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <TFNUI/TFNViewController.h>

#import <T1Twitter/T1DirectMessageComposeTextViewDelegate-Protocol.h>

@class NSArray, NSString, T1DirectMessageConversationQuickReplyPresentationBehavior, TFNDirectMessageComposition, TFNTwitterAccount, _TtC9T1Twitter37DirectMessageComposerInterstitialView;

@interface T1DirectMessageComposeViewController : TFNViewController <T1DirectMessageComposeTextViewDelegate>
{
    // Error parsing type: , name: delegate
    // Error parsing type: , name: attachmentDelegate
    // Error parsing type: , name: quickReplyDelegate
    // Error parsing type: , name: account
    // Error parsing type: , name: scribeContext
    // Error parsing type: , name: autocompleteBehavior
    // Error parsing type: , name: quickReplyPresentationBehavior
    // Error parsing type: , name: quotedStatusPreviewEnabled
    // Error parsing type: , name: attachmentsDisabled
    // Error parsing type: , name: copyLocally
    // Error parsing type: , name: disableAutocorrection
    // Error parsing type: , name: untrustedInterstitial
    // Error parsing type: , name: interstitialContainer
    // Error parsing type: , name: interstitialContainerHeightConstraint
    // Error parsing type: , name: interstitialContainerBottomConstraint
    // Error parsing type: , name: composeBarMaxHeight
    // Error parsing type: , name: _composeBarHidden
    // Error parsing type: , name: supportedComponents
    // Error parsing type: , name: composition
    // Error parsing type: , name: state
    // Error parsing type: , name: dismissKeyboardOnScroll
    // Error parsing type: , name: quotedStatusPreviewController
    // Error parsing type: , name: cardPreviewController
    // Error parsing type: , name: attachmentsViewController
    // Error parsing type: , name: customKeyboardViewController
    // Error parsing type: , name: foundMediaController
    // Error parsing type: , name: fullScreenPhotoGallery
    // Error parsing type: , name: quickReplyOptionsPickerViewController
    // Error parsing type: , name: userDismissedQuickReplyID
    // Error parsing type: , name: quickReplyOptionsPickerAutoDismissTimer
    // Error parsing type: , name: composeToolbarTopConstraint
    // Error parsing type: , name: composeToolbar
    // Error parsing type: , name: leftConstraint
    // Error parsing type: , name: containerStackViewTopConstraint
    // Error parsing type: , name: customKeyboardContainerView
    // Error parsing type: , name: customKeyboardHeightConstraint
    // Error parsing type: , name: backgroundView
    // Error parsing type: , name: ambientNotificationPlaceholderView
    // Error parsing type: , name: composeBarHeightConstraint
    // Error parsing type: , name: composeBarBottomConstraint
    // Error parsing type: , name: animatingKeyboardFrame
    // Error parsing type: , name: lockComposeBarPosition
    // Error parsing type: , name: lockComposeBarPositionConstraint
}

- (void).cxx_destruct;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)preferredContentSizeDidChangeForChildContentContainer:(id)arg1;
- (void)presentFoundMediaChooserTapped;
- (void)mediaAttachButtonLongPressed;
- (void)presentMediaGalleryTapped;
- (void)quickReplyButtonTapped:(id)arg1;
- (void)sendButtonTapped:(id)arg1;
- (void)keyboardDidShowWithNotification:(id)arg1;
- (void)keyboardDidHideWithNotification:(id)arg1;
- (void)keyboardWillChangeWithNotification:(id)arg1;
- (id)scribeSection;
- (id)scribePage;
- (void)swipeToDismissKeyboard;
- (void)focus;
- (void)dismissWithCompletion:(CDUnknownBlockType)arg1;
- (void)setComposeBarHidden:(_Bool)arg1 force:(_Bool)arg2;
- (void)enableAutoDismissalWithDataViewController:(id)arg1;
@property(nonatomic, readonly) _Bool tfn_prefersTabBarShadowHidden;
- (void)tfn_addDirectlyOwnedViewControllersToMutableArray:(id)arg1;
- (void)layoutGuidesDidChange:(long long)arg1;
- (void)viewDidLayoutSubviews;
- (void)updateViewConstraints;
- (void)viewDidFullyAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)dealloc;
- (void)viewDidLoad;
- (void)loadView;
- (id)initWithCoder:(id)arg1;
- (id)initWithAccount:(id)arg1;
@property(nonatomic, readonly) double composeBarHeight;
@property(nonatomic, copy) NSString *placeholderText;
@property(nonatomic, readonly) _Bool stateIsQuickReply;
@property(nonatomic, retain) TFNDirectMessageComposition *composition; // @synthesize composition;
@property(nonatomic) unsigned long long supportedComponents; // @synthesize supportedComponents;
@property(nonatomic) _Bool composeBarHidden;
@property(nonatomic, retain) _TtC9T1Twitter37DirectMessageComposerInterstitialView *untrustedInterstitial; // @synthesize untrustedInterstitial;
@property(nonatomic) _Bool attachmentsDisabled; // @synthesize attachmentsDisabled;
@property(nonatomic, retain) T1DirectMessageConversationQuickReplyPresentationBehavior *quickReplyPresentationBehavior; // @synthesize quickReplyPresentationBehavior;
@property(nonatomic, readonly) TFNTwitterAccount *account; // @synthesize account;
- (void)cameraContainerViewController:(id)arg1 didAttachVideoAsset:(id)arg2;
- (void)cameraContainerViewController:(id)arg1 didAttachPhotoAsset:(id)arg2;
- (void)cameraContainerViewControllerDidCancel:(id)arg1;
- (void)attachmentsViewControllerDidTapBackground:(id)arg1;
- (void)attachmentsViewController:(id)arg1 didTapRemoveAttachment:(id)arg2;
- (void)attachmentsViewController:(id)arg1 didTapAttachment:(id)arg2;
- (double)visibleLowerBoundForAttachmentsViewController:(id)arg1;
- (_Bool)attachmentsViewController:(id)arg1 shouldShowLivePhotoToggleButtonForAttachment:(id)arg2;
- (_Bool)attachmentsViewController:(id)arg1 shouldShowAltTextButtonForAttachment:(id)arg2;
- (_Bool)attachmentsViewController:(id)arg1 shouldShowStickerButtonForAttachment:(id)arg2;
- (_Bool)attachmentsViewController:(id)arg1 shouldShowEditButtonForAttachment:(id)arg2;
- (id)scribeSectionForFiltersViewController:(id)arg1;
- (void)filtersViewControllerDidCancel:(id)arg1;
- (void)filtersViewController:(id)arg1 didEditImage:(id)arg2;
- (void)photoGalleryViewController:(id)arg1 didEndSessionWithAttachments:(id)arg2;
- (void)photoGalleryViewControllerDidCancelSession:(id)arg1;
- (void)foundMediaController:(id)arg1 viewControllerDidCancel:(id)arg2;
- (void)foundMediaController:(id)arg1 viewController:(id)arg2 didSelectFoundMediaItem:(id)arg3;
- (void)videoTrimmerViewControllerDidCancel:(id)arg1;
- (void)videoTrimmerViewController:(id)arg1 didTrimVideo:(id)arg2;
@property(nonatomic, readonly) unsigned long long composeViewState;
- (_Bool)handlePasteImageForComposeTextView:(id)arg1;
- (_Bool)imagePasteEnabledForComposeTextView:(id)arg1;
- (_Bool)textViewShouldBeginEditing:(id)arg1;
- (void)textViewDidEndEditing:(id)arg1;
- (void)textViewDidBeginEditing:(id)arg1;
- (void)textViewDidChange:(id)arg1;
- (void)quickReplyPresentationBehaviorHideQuickReply:(id)arg1;
- (void)quickReplyPresentationBehavior:(id)arg1 presentOptionsQuickReplyWithID:(id)arg2 options:(id)arg3 selectedOption:(id)arg4 shouldFocus:(_Bool)arg5;
- (void)handleSendMessageKeyCommand;
- (void)handleReplyToMessageKeyCommand;
@property(nonatomic, readonly) NSArray *keyCommands;
@property(nonatomic, readonly) _Bool canBecomeFirstResponder;
- (long long)cardPreviewDisplayMode:(id)arg1;
- (_Bool)areMultipleCardURLsAllowed;
- (_Bool)isCardPreviewAllowed;
- (void)cardPreviewControllerDidStartFetching:(id)arg1;
- (void)cardPreviewController:(id)arg1 didShowCardPreviewWithCardData:(id)arg2;
- (void)cardPreviewController:(id)arg1 didRemoveCardPreviewForReason:(unsigned long long)arg2 withCardData:(id)arg3;

@end

