//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <T1Twitter/NSObject-Protocol.h>

@class T1DirectMessageAutocompleteController;

@protocol T1DirectMessageAutocompleteControllerDelegate <NSObject>
- (void)directMessageAutocompleteControllerDidUpdate:(T1DirectMessageAutocompleteController *)arg1;
- (void)directMessageAutocompleteControllerDidEnd:(T1DirectMessageAutocompleteController *)arg1;
- (void)directMessageAutocompleteControllerDidBegin:(T1DirectMessageAutocompleteController *)arg1;
@end

