//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <T1Twitter/T1DirectMessageAutocompleteControllerDataSource-Protocol.h>

@class NSMutableDictionary, NSString, TFNTwitterSearchTypeaheadStore;

@interface T1DirectMessageTypeaheadStoreAutocompleteControllerDataSource : NSObject <T1DirectMessageAutocompleteControllerDataSource>
{
    TFNTwitterSearchTypeaheadStore *_typeaheadStore;
    NSMutableDictionary *_resultsCache;
}

@property(readonly, nonatomic) NSMutableDictionary *resultsCache; // @synthesize resultsCache=_resultsCache;
@property(readonly, nonatomic) TFNTwitterSearchTypeaheadStore *typeaheadStore; // @synthesize typeaheadStore=_typeaheadStore;
- (void).cxx_destruct;
- (id)_visibleResultsForTypeaheadResults:(id)arg1 prefetchResults:(id)arg2 autocompleteType:(long long)arg3 typeaheadString:(id)arg4;
- (void)directMessageAutocompleteController:(id)arg1 sectionsForAutocompleteResultType:(long long)arg2 query:(id)arg3 source:(unsigned long long)arg4 completion:(CDUnknownBlockType)arg5;
- (id)initWithTypeaheadStore:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

