//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <TwitterLifecycleTools/TLTGenericBackgroundFetchTask.h>

@interface T1HomeTimelineUpdateBackgroundFetchTask : TLTGenericBackgroundFetchTask
{
    // Error parsing type: , name: completion
    // Error parsing type: , name: result
}

- (void).cxx_destruct;
- (id)initWithIdentifier:(id)arg1;
- (void)cancel;
- (void)startWithCompletion:(CDUnknownBlockType)arg1;
- (id)init;

@end

