//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <T1Twitter/T1InlineMediaViewModel-Protocol.h>

@class NSString, T1PlayerSessionProducer;
@protocol TFNTwitterAVPlayerSessionSource;

@interface T1InlineMediaViewModel : NSObject <T1InlineMediaViewModel>
{
    _Bool _watchAgainButtonEnabled;
    _Bool _shouldShowAdCountdownForQuotedTweet;
    T1PlayerSessionProducer *_playerSessionProducer;
    id <TFNTwitterAVPlayerSessionSource> _playerSessionSource;
    unsigned long long _mediaType;
    unsigned long long _playerIconViewType;
    double _pillViewTimeInterval;
    unsigned long long _viewCount;
}

@property(readonly, nonatomic) _Bool shouldShowAdCountdownForQuotedTweet; // @synthesize shouldShowAdCountdownForQuotedTweet=_shouldShowAdCountdownForQuotedTweet;
@property(readonly, nonatomic) _Bool watchAgainButtonEnabled; // @synthesize watchAgainButtonEnabled=_watchAgainButtonEnabled;
@property(readonly, nonatomic) unsigned long long viewCount; // @synthesize viewCount=_viewCount;
@property(readonly, nonatomic) double pillViewTimeInterval; // @synthesize pillViewTimeInterval=_pillViewTimeInterval;
@property(readonly, nonatomic) unsigned long long playerIconViewType; // @synthesize playerIconViewType=_playerIconViewType;
@property(readonly, nonatomic) unsigned long long mediaType; // @synthesize mediaType=_mediaType;
@property(readonly, nonatomic) id <TFNTwitterAVPlayerSessionSource> playerSessionSource; // @synthesize playerSessionSource=_playerSessionSource;
@property(readonly, nonatomic) T1PlayerSessionProducer *playerSessionProducer; // @synthesize playerSessionProducer=_playerSessionProducer;
- (void).cxx_destruct;
- (id)init;
- (id)initWithPlayerSessionProducer:(id)arg1 playerSessionSource:(id)arg2 mediaType:(unsigned long long)arg3 playerIconViewType:(unsigned long long)arg4 pillViewTimeInterval:(double)arg5 viewCount:(unsigned long long)arg6 watchAgainButtonEnabled:(_Bool)arg7 shouldShowAdCountdownForQuotedTweet:(_Bool)arg8;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

