//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import <T1Twitter/TAVPlaybackObserver-Protocol.h>

@class TAVPlayer, TFNBatteryMonitorHandle, UIImage, UIImageView;

@interface T1LiveEventPlayerObservingBlurView : UIView <TAVPlaybackObserver>
{
    UIImageView *_backgroundImageView;
    UIImageView *_backgroundTransitionImageView;
    TFNBatteryMonitorHandle *_batteryMonitorHandle;
    struct {
        unsigned int isLowPowerModeEnabled:1;
        unsigned int isCaptureOccurring:1;
        unsigned int isTransitionAnimating:1;
    } _flags;
    _Bool _isPlayerChangingOrUpdating;
    UIImage *_previewImage;
    TAVPlayer *_capturingPlayer;
}

@property(nonatomic) _Bool isPlayerChangingOrUpdating; // @synthesize isPlayerChangingOrUpdating=_isPlayerChangingOrUpdating;
@property(nonatomic) __weak TAVPlayer *capturingPlayer; // @synthesize capturingPlayer=_capturingPlayer;
@property(retain, nonatomic) UIImage *previewImage; // @synthesize previewImage=_previewImage;
- (void).cxx_destruct;
- (void)player:(id)arg1 didUpdatePlaybackState:(id)arg2;
- (void)_t1_resetBlurredVideoBackgroundImageView;
- (void)_t1_completeTransition:(id)arg1;
- (void)_t1_transitionBackgroundImage:(id)arg1 animated:(_Bool)arg2;
- (void)_t1_captureAndDisplayImageWithPlayer:(id)arg1;
- (void)_t1_captureSnapshotAndDisplay:(id)arg1;
- (void)_t1_scheduleCaptureWithPlayer:(id)arg1 afterDelay:(double)arg2;
- (void)_t1_beginCapturingSnapshotsWithPlayer:(id)arg1;
- (void)_t1_stopCapturingSnapshots;
- (void)_t1_updateLowPowerModeStatus;
- (void)_t1_stopObservingPowerNotifications;
- (void)_t1_startObservingPowerNotifications;
- (void)reset;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

