//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import <T1Twitter/TFNAnimatedGifImageViewDelegate-Protocol.h>

@class NSString, T1AnimatedGIFImageView, T1MediaAttachmentBadgeView, T1MediaAttachmentProgressView, TFNTwitterMediaAsset, UIImageView;
@protocol T1MediaAttachmentViewDelegate;

@interface T1MediaAttachmentView : UIView <TFNAnimatedGifImageViewDelegate>
{
    _Bool _playIconHidden;
    _Bool _progressViewHidden;
    _Bool _animatedContentEnabled;
    _Bool _showsAttachmentProgressView;
    _Bool _attachmentProgressFailed;
    int _requestID;
    NSString *_accountID;
    TFNTwitterMediaAsset *_attachment;
    id <T1MediaAttachmentViewDelegate> _delegate;
    double _badgeMarginLength;
    UIImageView *_imageView;
    T1AnimatedGIFImageView *_gifView;
    T1MediaAttachmentProgressView *_attachmentProgressView;
    double _attachmentProgress;
    UIImageView *_playIconView;
    T1MediaAttachmentBadgeView *_attachmentBadgeView;
}

@property(nonatomic) int requestID; // @synthesize requestID=_requestID;
@property(readonly, nonatomic) T1MediaAttachmentBadgeView *attachmentBadgeView; // @synthesize attachmentBadgeView=_attachmentBadgeView;
@property(readonly, nonatomic) UIImageView *playIconView; // @synthesize playIconView=_playIconView;
@property(nonatomic) _Bool attachmentProgressFailed; // @synthesize attachmentProgressFailed=_attachmentProgressFailed;
@property(nonatomic) double attachmentProgress; // @synthesize attachmentProgress=_attachmentProgress;
@property(nonatomic) _Bool showsAttachmentProgressView; // @synthesize showsAttachmentProgressView=_showsAttachmentProgressView;
@property(readonly, nonatomic) T1MediaAttachmentProgressView *attachmentProgressView; // @synthesize attachmentProgressView=_attachmentProgressView;
@property(readonly, nonatomic) T1AnimatedGIFImageView *gifView; // @synthesize gifView=_gifView;
@property(readonly, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
@property(nonatomic, getter=isAnimatedContentEnabled) _Bool animatedContentEnabled; // @synthesize animatedContentEnabled=_animatedContentEnabled;
@property(nonatomic, getter=isProgressViewHidden) _Bool progressViewHidden; // @synthesize progressViewHidden=_progressViewHidden;
@property(nonatomic, getter=isPlayIconHidden) _Bool playIconHidden; // @synthesize playIconHidden=_playIconHidden;
@property(nonatomic) double badgeMarginLength; // @synthesize badgeMarginLength=_badgeMarginLength;
@property(nonatomic) __weak id <T1MediaAttachmentViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) TFNTwitterMediaAsset *attachment; // @synthesize attachment=_attachment;
@property(copy, nonatomic) NSString *accountID; // @synthesize accountID=_accountID;
- (void).cxx_destruct;
- (void)animatedGifImageViewDidFinishLooping:(id)arg1;
- (void)_updateAnimatedGIFImageView;
- (void)_setAnimatedGIFImage:(id)arg1;
- (void)_setFullAnimatedGIFImage:(id)arg1;
- (void)_setPreviewAnimatedGIFImage:(id)arg1;
- (void)_setImage:(id)arg1;
- (void)_updateDurationBadge;
- (void)_setProgressWithRequestID:(int)arg1 progress:(double)arg2 error:(id)arg3;
- (void)_updateImageWithAttachment:(id)arg1;
- (void)_updateImageWithAnimatedImageAttachment:(id)arg1;
- (void)_updateImage;
- (void)_updatePlayIconView;
- (void)_updateAttachmentProgressView;
- (void)_updateAttachment;
- (void)_updateAttachmentProgressViewState;
- (void)stopUpdating;
- (void)stopAnimatingAtEndOfLoop;
- (void)stopAnimating;
- (void)startAnimating;
@property(readonly, nonatomic, getter=isAnimating) _Bool animating;
@property(nonatomic, getter=isBadgeHidden) _Bool badgeHidden;
- (void)layoutSubviews;
- (void)_t1_mediaAttachmentView_initialize;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

