//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <TFNUI/TFNViewController.h>

#import <T1Twitter/T1MediaAttachmentsViewCellDelegate-Protocol.h>
#import <T1Twitter/T1MediaAttachmentsViewDelegateLayout-Protocol.h>
#import <T1Twitter/UICollectionViewDataSource-Protocol.h>
#import <T1Twitter/UICollectionViewDelegate-Protocol.h>

@class NSArray, NSMutableArray, NSString, T1MediaAttachmentsViewLayout, TFNTwitterAccount, UICollectionView, UITapGestureRecognizer;
@protocol T1MediaAttachmentsViewControllerDelegate;

@interface T1MediaAttachmentsViewController : TFNViewController <UICollectionViewDataSource, UICollectionViewDelegate, T1MediaAttachmentsViewDelegateLayout, T1MediaAttachmentsViewCellDelegate>
{
    NSMutableArray *_attachments;
    NSArray *_items;
    T1MediaAttachmentsViewLayout *_layout;
    struct CGPoint _targetContentOffset;
    _Bool _estimatedContentSizeCached;
    struct CGSize _estimatedContentSize;
    _Bool _marginAroundCellsCached;
    struct UIEdgeInsets _marginAroundCells;
    UITapGestureRecognizer *_backgroundTapGestureRecognizer;
    _Bool _alwaysUseSameAttachmentsViewHeight;
    _Bool _showsRemoveButton;
    TFNTwitterAccount *_account;
    id <T1MediaAttachmentsViewControllerDelegate> _delegate;
    double _preferredAttachmentsViewHeight;
    UICollectionView *_collectionView;
    struct UIEdgeInsets _contentInsets;
}

@property(readonly, nonatomic) UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
@property(nonatomic) _Bool showsRemoveButton; // @synthesize showsRemoveButton=_showsRemoveButton;
@property(nonatomic) double preferredAttachmentsViewHeight; // @synthesize preferredAttachmentsViewHeight=_preferredAttachmentsViewHeight;
@property(nonatomic) _Bool alwaysUseSameAttachmentsViewHeight; // @synthesize alwaysUseSameAttachmentsViewHeight=_alwaysUseSameAttachmentsViewHeight;
@property(nonatomic) struct UIEdgeInsets contentInsets; // @synthesize contentInsets=_contentInsets;
@property(nonatomic) __weak id <T1MediaAttachmentsViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) TFNTwitterAccount *account; // @synthesize account=_account;
- (void).cxx_destruct;
- (void)attachmentsViewCellDidDisableLivePhotoToggleButton:(id)arg1;
- (id)attachmentsViewCellAccessibilityLabelString:(id)arg1;
- (void)attachmentsViewCellDidTapLivePhotoToggleButton:(id)arg1;
- (void)attachmentsViewCellDidTapAltTextButton:(id)arg1;
- (void)attachmentsViewCellDidTapStickerButton:(id)arg1;
- (void)attachmentsViewCellDidTapEditButton:(id)arg1;
- (void)attachmentsViewCellDidTapRemoveButton:(id)arg1;
- (void)attachmentsViewCellDidTap:(id)arg1;
- (_Bool)attachmentsViewCellShouldShowLivePhotoToggleButton:(id)arg1;
- (_Bool)attachmentsViewCellShouldShowAltTextButton:(id)arg1;
- (_Bool)attachmentsViewCellShouldShowStickerButton:(id)arg1;
- (_Bool)attachmentsViewCellShouldShowEditButton:(id)arg1;
- (void)collectionView:(id)arg1 willInsertItemAtIndexPath:(id)arg2;
- (struct CGSize)_preferredSizeForAttachment:(id)arg1 constrainedToSize:(struct CGSize)arg2;
- (struct UIEdgeInsets)_marginAroundCells;
- (struct CGSize)_sizeForAttachment:(id)arg1;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewWillEndDragging:(id)arg1 withVelocity:(struct CGPoint)arg2 targetContentOffset:(inout struct CGPoint *)arg3;
- (void)collectionView:(id)arg1 willDisplayCell:(id)arg2 forItemAtIndexPath:(id)arg3;
- (void)collectionView:(id)arg1 didEndDisplayingCell:(id)arg2 forItemAtIndexPath:(id)arg3;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (void)viewDidLoad;
- (void)_attachmentDidUpdatePreviewImage:(id)arg1;
- (void)_didTapBackgroundView:(id)arg1;
- (void)updateToVisibleLowerBound;
- (void)stopAnimatingAttachmentPreviews;
- (double)preferredHeightFittingWidth:(double)arg1;
- (void)_updatePreferredContentSizeWithPreferredWidth:(double)arg1;
- (void)_updatePreferredContentSize;
- (void)_updateItems;
- (void)removeAllAttachments;
- (struct CGSize)_estimatedContentSize;
- (void)_performBatchUpdates:(CDUnknownBlockType)arg1 completion:(CDUnknownBlockType)arg2;
- (void)_reloadData;
- (void)_updateScrollEnabled;
- (void)removeAttachment:(id)arg1;
- (void)replaceAttachment:(id)arg1 withAttachment:(id)arg2;
- (struct CGPoint)_estimatedContentOffsetForInsertingItemAtIndexPath:(id)arg1;
- (void)addAttachment:(id)arg1;
- (void)setAttachments:(id)arg1;
- (void)dealloc;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

