//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <TFNUI/TFNViewController.h>

@interface T1MomentCapsuleViewControllerFactory : TFNViewController
{
}

+ (id)createMomentCapsuleWithMomentID:(id)arg1 impressionID:(id)arg2 account:(id)arg3 navigationContext:(id)arg4;
+ (id)createMomentCapsuleWithMomentID:(id)arg1 account:(id)arg2 navigationContext:(id)arg3;
+ (id)createMomentCapsuleWithDataManager:(id)arg1 account:(id)arg2 scribeDelegate:(id)arg3 navigationContext:(id)arg4 momentID:(id)arg5 impressionID:(id)arg6;
+ (id)createMomentCapsuleWithDataManager:(id)arg1 account:(id)arg2 scribeDelegate:(id)arg3 navigationContext:(id)arg4 momentID:(id)arg5;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

