//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface T1NewsCameraCapturePreviewControlsOverlayView : UIView
{
    double _cornerRadius;
}

+ (Class)layerClass;
@property(nonatomic) double cornerRadius; // @synthesize cornerRadius=_cornerRadius;
- (void)setCornerRadius:(double)arg1 animated:(_Bool)arg2;

@end

