//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <T1Twitter/NSObject-Protocol.h>

@class NSArray, TFNOnboardingMutableSettingsValue, TFNOnboardingNavigationLink;
@protocol T1OnboardingSettingsValueViewModel;

@protocol T1OnboardingSettingsValueViewModelDelegate <NSObject>
- (void)onboardingSettingsValueViewModel:(id <T1OnboardingSettingsValueViewModel>)arg1 didChangeForSettingsValue:(TFNOnboardingMutableSettingsValue *)arg2;

@optional
- (void)onboardingSettingsValueViewModel:(id <T1OnboardingSettingsValueViewModel>)arg1 didSelectBooleanWithSettingsValue:(TFNOnboardingMutableSettingsValue *)arg2 booleanData:(_Bool)arg3;
- (void)onboardingSettingsValueViewModel:(id <T1OnboardingSettingsValueViewModel>)arg1 didSelectSettingsGroupWithSettingsValues:(NSArray *)arg2 forSettingsValue:(TFNOnboardingMutableSettingsValue *)arg3;
- (void)onboardingSettingsValueViewModel:(id <T1OnboardingSettingsValueViewModel>)arg1 didSelectNavigationLinkWithLink:(TFNOnboardingNavigationLink *)arg2;
@end

