//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <T1Twitter/T1OnboardingHeaderViewModel-Protocol.h>

@class NSString, T1OnboardingSubtaskController, T1PromptImageSpec, T1PromptTextSpec, TFNOnboardingHeaderImage, TFNOnboardingRichText, TFNTwitterAccount, UIColor;
@protocol TFNOnboardingSubtaskDataProvider;

@interface T1OnboardingHeaderViewModel : NSObject <T1OnboardingHeaderViewModel>
{
    id <TFNOnboardingSubtaskDataProvider> _subtaskDataProvider;
    long long _style;
    T1OnboardingSubtaskController *_subtaskController;
    TFNOnboardingHeaderImage *_headerImage;
    TFNOnboardingRichText *_subtitle;
    TFNOnboardingRichText *_title;
    TFNTwitterAccount *_account;
    T1PromptImageSpec *_imageSpec;
    T1PromptTextSpec *_subtitleTextSpec;
    T1PromptTextSpec *_titleTextSpec;
}

- (void).cxx_destruct;
- (id)private_overrideFontForSubtitle;
- (id)private_overrideFontForTitle;
- (double)private_titleToSubtitleSpacingForLayoutMetrics:(id)arg1 subtitleFont:(id)arg2;
- (struct UIEdgeInsets)private_contentInsetsForHeaderView:(id)arg1 layoutMetrics:(id)arg2;
- (id)private_subtitleColor;
- (struct UIEdgeInsets)edgeSpacingForSubtitleView:(id)arg1 layoutMetrics:(id)arg2;
- (struct UIEdgeInsets)edgeSpacingForTitleView:(id)arg1 layoutMetrics:(id)arg2;
- (struct UIEdgeInsets)edgeSpacingForImageView:(id)arg1 layoutMetrics:(id)arg2;
- (struct UIEdgeInsets)edgeSpacingForHeaderView:(id)arg1 layoutMetrics:(id)arg2;
@property(readonly, nonatomic) UIColor *subtitleColor;
@property(readonly, nonatomic) UIColor *titleColor;
@property(readonly, nonatomic) long long subtitleAlignment;
@property(readonly, nonatomic) long long titleAlignment;
@property(readonly, nonatomic) long long imageAlignment;
@property(readonly, nonatomic) T1PromptTextSpec *subtitleTextSpec; // @synthesize subtitleTextSpec=_subtitleTextSpec;
@property(readonly, nonatomic) T1PromptTextSpec *titleTextSpec; // @synthesize titleTextSpec=_titleTextSpec;
@property(readonly, nonatomic) T1PromptImageSpec *imageSpec; // @synthesize imageSpec=_imageSpec;
- (id)initWithStyle:(long long)arg1 title:(id)arg2 subtitle:(id)arg3;
- (id)initWithStyle:(long long)arg1 account:(id)arg2 subtaskController:(id)arg3 subtaskDataProvider:(id)arg4 headerImage:(id)arg5 title:(id)arg6 subtitle:(id)arg7;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

