//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary, NSString, TFNOnboardingSubtaskState;
@protocol T1OnboardingSubtaskControllerDelegate;

@interface T1OnboardingSubtaskController : NSObject
{
    id <T1OnboardingSubtaskControllerDelegate> _controllerDelegate;
    NSString *_subtaskID;
    long long _subtaskBackNavigationType;
    TFNOnboardingSubtaskState *_subtaskState;
}

@property(readonly, nonatomic) TFNOnboardingSubtaskState *subtaskState; // @synthesize subtaskState=_subtaskState;
@property(readonly, nonatomic) long long subtaskBackNavigationType; // @synthesize subtaskBackNavigationType=_subtaskBackNavigationType;
@property(readonly, nonatomic) NSString *subtaskID; // @synthesize subtaskID=_subtaskID;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSDictionary *subtaskData;
- (void)didActivateNavigationLink:(id)arg1;
- (void)restartWithNavigationContext:(id)arg1 navigationLink:(id)arg2;
- (void)startWithNavigationContext:(id)arg1 navigationLink:(id)arg2;
@property(readonly, nonatomic) _Bool canRestartForErrors;
- (id)initWithSubtask:(id)arg1 state:(id)arg2 delegate:(id)arg3;

@end

