//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface T1ProfileViewControllerFactory : NSObject
{
}

+ (id)editableProfileViewControllerForAccount:(id)arg1;
+ (id)modalProfileViewControllerForUserReference:(id)arg1 account:(id)arg2 sourceView:(id)arg3 sourceRect:(struct CGRect)arg4;
+ (id)profileViewControllerForUserReference:(id)arg1 account:(id)arg2;
+ (id)modalProfileViewControllerForUserDataSource:(id)arg1 context:(id)arg2 account:(id)arg3 sourceView:(id)arg4 sourceRect:(struct CGRect)arg5;
+ (id)profileViewControllerForUserDataSource:(id)arg1 context:(id)arg2 account:(id)arg3;
+ (id)modalProfileViewControllerForUser:(id)arg1 account:(id)arg2 sourceView:(id)arg3 sourceRect:(struct CGRect)arg4 isPreview:(_Bool)arg5;
+ (id)modalProfileViewControllerForUser:(id)arg1 account:(id)arg2 sourceView:(id)arg3 sourceRect:(struct CGRect)arg4;
+ (id)profileViewControllerForUser:(id)arg1 account:(id)arg2;

@end

