//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <T1Twitter/T1AuthenticationForm.h>

@class NSArray, NSString, T1SingleSignOnConnectHeader, TFNTwitterAccount, TFNTwitterOAuthRequestTokenResponse, TFSTwitterAuthSingleSignOn;

@interface T1SingleSignOnForm : T1AuthenticationForm
{
    // Error parsing type: , name: oauthCallbackURLString
    // Error parsing type: , name: sourceAppBundleID
    // Error parsing type: , name: singleSignOn
    // Error parsing type: , name: account
    // Error parsing type: , name: state
    // Error parsing type: , name: hitBottom
    // Error parsing type: , name: requestToken
    // Error parsing type: , name: connectHeader
    // Error parsing type: , name: activityIndicatorItem
    // Error parsing type: , name: permissionsText.storage
    // Error parsing type: , name: appPrivacyText.storage
    // Error parsing type: , name: revokeAccessText.storage
    // Error parsing type: , name: privacyText.storage
}

- (void).cxx_destruct;
@property(nonatomic, readonly) NSArray *sections;
- (id)init;
- (id)initWithCredential:(id)arg1 oauthCallbackURLString:(id)arg2 sourceAppBundleID:(id)arg3;
@property(nonatomic, readonly) T1SingleSignOnConnectHeader *connectHeader; // @synthesize connectHeader;
@property(nonatomic, retain) TFNTwitterOAuthRequestTokenResponse *requestToken; // @synthesize requestToken;
- (_Bool)isSubmittable;
@property(nonatomic) _Bool hitBottom; // @synthesize hitBottom;
@property(nonatomic) long long state; // @synthesize state;
@property(nonatomic, retain) TFNTwitterAccount *account; // @synthesize account;
@property(nonatomic, readonly) TFSTwitterAuthSingleSignOn *singleSignOn; // @synthesize singleSignOn;
@property(nonatomic, readonly) NSString *sourceAppBundleID; // @synthesize sourceAppBundleID;
@property(nonatomic, readonly) NSString *oauthCallbackURLString; // @synthesize oauthCallbackURLString;

// Remaining properties
@property(nonatomic, readonly) _Bool submittable;

@end

