//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <T1Twitter/T1ResizableHeaderView.h>

@class UIButton, UIImageView, UIView;
@protocol T1StickerTimelineHeaderViewDelegate;

@interface T1StickerTimelineHeaderView : T1ResizableHeaderView
{
    id <T1StickerTimelineHeaderViewDelegate> _stickerTimelineHeaderViewDelegate;
    UIView *_stickerHostView;
    UIImageView *_stickerImageView;
    UIButton *_creatorButton;
}

@property(retain, nonatomic) UIButton *creatorButton; // @synthesize creatorButton=_creatorButton;
@property(retain, nonatomic) UIImageView *stickerImageView; // @synthesize stickerImageView=_stickerImageView;
@property(retain, nonatomic) UIView *stickerHostView; // @synthesize stickerHostView=_stickerHostView;
@property(nonatomic) __weak id <T1StickerTimelineHeaderViewDelegate> stickerTimelineHeaderViewDelegate; // @synthesize stickerTimelineHeaderViewDelegate=_stickerTimelineHeaderViewDelegate;
- (void).cxx_destruct;
- (id)_backgroundColorSuitableForWhiteContentFromSticker:(id)arg1;
- (void)_creatorButtonTapped:(id)arg1;
- (void)updateAuthor:(id)arg1;
- (void)updateSticker:(id)arg1 image:(id)arg2;
- (struct CGSize)stickerImageViewSize;
- (void)layoutSubviews;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (struct CGSize)preferredSize;
- (id)initWithFrame:(struct CGRect)arg1;

@end

