//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <TFNUI/TFNItemsTableRowAdapter.h>

#import <T1Twitter/T1TwitterAuthenticated-Protocol.h>

@class NSString, T1SULCategoryUserLoader, TFNTwitterAccount;

@interface T1SULCategoryTableRowAdapter : TFNItemsTableRowAdapter <T1TwitterAuthenticated>
{
    TFNTwitterAccount *_account;
    T1SULCategoryUserLoader *_userLoader;
}

@property(retain, nonatomic) T1SULCategoryUserLoader *userLoader; // @synthesize userLoader=_userLoader;
@property(retain, nonatomic) TFNTwitterAccount *account; // @synthesize account=_account;
- (void).cxx_destruct;
- (void)_loadUsersForCategory:(id)arg1;
- (void)dataViewController:(id)arg1 didSelectItem:(id)arg2 withOptions:(id)arg3 atIndexPath:(id)arg4;
- (id)dataViewController:(id)arg1 tableViewCellForItem:(id)arg2 withOptions:(id)arg3 atIndexPath:(id)arg4;
- (double)dataViewController:(id)arg1 tableViewHeightForItem:(id)arg2 withOptions:(id)arg3 atIndexPath:(id)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

