//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <TFNUI/TFNViewController.h>

#import <T1Twitter/T1TwitterAuthenticated-Protocol.h>
#import <T1Twitter/TFNModalSheetViewControllerDelegate-Protocol.h>
#import <T1Twitter/TFNModalSheetViewControllerLayoutDelegate-Protocol.h>
#import <T1Twitter/TFNTokenFieldDelegate-Protocol.h>
#import <T1Twitter/UIScrollViewDelegate-Protocol.h>
#import <T1Twitter/UITableViewDataSource-Protocol.h>
#import <T1Twitter/UITableViewDelegate-Protocol.h>

@class NSArray, NSMutableArray, NSString, T1AutocompleteResultsController, T1TaggingTableHeaderView, T1TaggingTableView, TFNTwitterAccount, TFNTwitterComposition, TFSTimer, UIBarButtonItem;
@protocol T1TaggingViewControllerDelegate;

@interface T1TaggingViewController : TFNViewController <TFNTokenFieldDelegate, UIScrollViewDelegate, UITableViewDelegate, UITableViewDataSource, T1TwitterAuthenticated, TFNModalSheetViewControllerDelegate, TFNModalSheetViewControllerLayoutDelegate>
{
    T1TaggingTableView *_tableView;
    UIBarButtonItem *_cancelBarButtonItem;
    struct UIEdgeInsets _tableViewInsets;
    T1AutocompleteResultsController *_autocompleteResultsController;
    TFSTimer *_autocompleteTimer;
    NSString *_partialText;
    NSArray *_autocompleteResults;
    NSArray *_suggestedUserItems;
    NSMutableArray *_tags;
    TFNTwitterAccount *_account;
    id <T1TaggingViewControllerDelegate> _delegate;
    TFNTwitterComposition *_composition;
    T1TaggingTableHeaderView *_headerView;
}

@property(readonly, nonatomic) T1TaggingTableHeaderView *headerView; // @synthesize headerView=_headerView;
@property(retain, nonatomic) TFNTwitterComposition *composition; // @synthesize composition=_composition;
@property(nonatomic) __weak id <T1TaggingViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) TFNTwitterAccount *account; // @synthesize account=_account;
- (void).cxx_destruct;
- (id)tfn_contentScrollView;
- (id)_suggestedUserItems;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (double)_t1_sectionHeaderHeight;
- (_Bool)_t1_showSectionHeader;
- (id)tableView:(id)arg1 titleForHeaderInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)_t1_setRemainingCountLabelHidden:(_Bool)arg1;
- (void)_t1_updateRemainingCount;
- (void)tokenField:(id)arg1 didRemoveToken:(id)arg2 atIndex:(unsigned long long)arg3;
- (void)tokenField:(id)arg1 didAddToken:(id)arg2 atIndex:(unsigned long long)arg3;
- (_Bool)tokenField:(id)arg1 shouldReturnFromEditing:(id)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (double)preferredHeightForModalSheetViewController:(id)arg1 modalContentViewVisibleEdgeInsets:(struct UIEdgeInsets)arg2;
- (void)modalSheetViewControllerDidDismiss:(id)arg1 fromGesture:(_Bool)arg2;
- (void)modalSheetViewController:(id)arg1 willTransitionToLayoutMode:(long long)arg2 withTransitionCoordinator:(id)arg3;
- (void)_t1_adjustScrollViewInsetsForKeyboardSize:(struct CGSize)arg1;
- (void)_t1_keyboardWillShow:(id)arg1;
- (void)_t1_keyboardWillHide:(id)arg1;
- (void)_t1_scrollToTokenFieldEditingCursorAnimated:(_Bool)arg1;
- (void)_t1_updateAutocompleteResultsByPartialText:(id)arg1;
- (void)_t1_updateAutocompleteResultsOnTime:(id)arg1;
- (void)_t1_tokenFieldEditingChanged:(id)arg1;
- (void)_t1_tokenFieldEditingDidBegin:(id)arg1;
- (void)_t1_done:(id)arg1;
- (void)_t1_cancel:(id)arg1;
- (void)_t1_scribeResultsImpression;
- (id)scribeComponent;
- (id)scribePage;
- (id)scribe;
- (void)_t1_layoutHeaderView;
- (void)_t1_sizeToFitHeaderView;
- (void)viewDidLayoutSubviews;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)loadView;
- (void)dealloc;
- (void)_t1_reloadTableViewData;
- (void)_t1_updateAutocompleteResults:(id)arg1 forPartialText:(id)arg2;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

