//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <TFNUI/TFNItemsTableRowAdapter.h>

@class T1StatusMediaHandler, TFNTwitterAccount, TFSTwitterScribeContext, TIPImagePipeline;
@protocol T1UnifiedCardComponentViewRegistry;

@interface T1UnifiedCardItemTableRowAdapter : TFNItemsTableRowAdapter
{
    TFNTwitterAccount *_account;
    TFSTwitterScribeContext *_scribeContext;
    id <T1UnifiedCardComponentViewRegistry> _componentRegistry;
    T1StatusMediaHandler *_statusMediaHandler;
    TIPImagePipeline *_imagePipeline;
}

@property(readonly, nonatomic) TIPImagePipeline *imagePipeline; // @synthesize imagePipeline=_imagePipeline;
@property(readonly, nonatomic) T1StatusMediaHandler *statusMediaHandler; // @synthesize statusMediaHandler=_statusMediaHandler;
@property(readonly, nonatomic) id <T1UnifiedCardComponentViewRegistry> componentRegistry; // @synthesize componentRegistry=_componentRegistry;
@property(readonly, copy, nonatomic) TFSTwitterScribeContext *scribeContext; // @synthesize scribeContext=_scribeContext;
@property(readonly, nonatomic) TFNTwitterAccount *account; // @synthesize account=_account;
- (void).cxx_destruct;
- (id)dataViewController:(id)arg1 tableViewCellForItem:(id)arg2 withOptions:(id)arg3 atIndexPath:(id)arg4;
- (id)dataViewController:(id)arg1 calculatedLayoutMetricsForItem:(id)arg2 withOptions:(id)arg3 atIndexPath:(id)arg4;
- (double)dataViewController:(id)arg1 tableViewHeightForItem:(id)arg2 withOptions:(id)arg3 atIndexPath:(id)arg4;
- (id)initWithAccount:(id)arg1 statusMediaHandler:(id)arg2 componentRegistry:(id)arg3 imagePipeline:(id)arg4 scribeContext:(id)arg5;
- (id)init;

@end

