//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <T1Twitter/TFNFormViewController.h>

#import <T1Twitter/TFNAttributedTextViewDelegate-Protocol.h>

@class NSDictionary, NSString, T1OnboardingFormFooterItem, T1SignUpFormFooterView, T1UpdateEmailForm, TFNTwitterAccount;

@interface T1UpdateEmailViewController : TFNFormViewController <TFNAttributedTextViewDelegate>
{
    NSDictionary *_legalURLs;
    T1UpdateEmailForm *_form;
    TFNTwitterAccount *_account;
    T1SignUpFormFooterView *_legalFooterView;
    T1OnboardingFormFooterItem *_footerItem;
    NSString *_scribePage;
}

@property(copy, nonatomic) NSString *scribePage; // @synthesize scribePage=_scribePage;
@property(retain, nonatomic) T1OnboardingFormFooterItem *footerItem; // @synthesize footerItem=_footerItem;
@property(retain, nonatomic) T1SignUpFormFooterView *legalFooterView; // @synthesize legalFooterView=_legalFooterView;
@property(readonly, nonatomic) TFNTwitterAccount *account; // @synthesize account=_account;
@property(retain, nonatomic) T1UpdateEmailForm *form; // @synthesize form=_form;
- (void).cxx_destruct;
- (void)tfn_keyboardDismissModalAction;
- (_Bool)tfn_canKeyboardDismissModal;
- (void)_learnMoreTapped;
- (void)_cancelTapped;
- (void)_discoverabilityOptionsTapped;
- (void)_handleAddEmailError;
- (void)_handleAddEmailSuccess;
- (void)attributedTextView:(id)arg1 didTapRange:(id)arg2 rect:(struct CGRect)arg3;
- (_Bool)includesSubmitButtonAsItem;
- (id)doneBarButtonItem;
- (id)footerItems;
- (void)submitForm;
- (id)submitButton;
- (id)scribeSection;
- (id)scribe;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (id)initWithForm:(id)arg1 appearance:(id)arg2;
- (id)initWithAccount:(id)arg1 currentEmail:(id)arg2 correctedEmail:(id)arg3 scribePage:(id)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

