//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <T1Twitter/NSObject-Protocol.h>

@class TFNBugReport, TFNBugReporter;

@protocol TFNBugReporterDelegate <NSObject>

@optional
- (void)bugReporter:(TFNBugReporter *)arg1 sendBugReport:(TFNBugReport *)arg2 didCompleteWithResult:(long long)arg3;
- (void)bugReporter:(TFNBugReporter *)arg1 didTriggerBugReport:(TFNBugReport *)arg2;
- (id)contextForBugReporter:(TFNBugReporter *)arg1;
@end

