//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <TFSUtilities/TFSConcurrentOperation.h>

#import <T1Twitter/TFNDirectMessageBulkDecryptOperationDelegate-Protocol.h>
#import <T1Twitter/TFNDirectMessageFetchConversationPageOperationDelegate-Protocol.h>

@class NSOperation, NSOperationQueue, TFNDirectMessageBulkDecryptOperation, TFNDirectMessageConversation, TFNDirectMessageFetchConversationPageOperation, TFNDirectMessageModel, TFNDirectMessageProcessConversationPageResponseOperation;

@interface TFNDirectMessageConversationPageOperation : TFSConcurrentOperation <TFNDirectMessageBulkDecryptOperationDelegate, TFNDirectMessageFetchConversationPageOperationDelegate>
{
    TFNDirectMessageConversation *_conversation;
    TFNDirectMessageModel *_model;
    long long _maxEventID;
    CDUnknownBlockType _paginationCompletionBlock;
    NSOperationQueue *_queue;
    TFNDirectMessageFetchConversationPageOperation *_fetchOperation;
    TFNDirectMessageBulkDecryptOperation *_bulkDecryptOperation;
    TFNDirectMessageProcessConversationPageResponseOperation *_processResponseOperation;
    NSOperation *_markCompletedOperation;
}

@property(retain, nonatomic) NSOperation *markCompletedOperation; // @synthesize markCompletedOperation=_markCompletedOperation;
@property(readonly, nonatomic) TFNDirectMessageProcessConversationPageResponseOperation *processResponseOperation; // @synthesize processResponseOperation=_processResponseOperation;
@property(retain, nonatomic) TFNDirectMessageBulkDecryptOperation *bulkDecryptOperation; // @synthesize bulkDecryptOperation=_bulkDecryptOperation;
@property(retain, nonatomic) TFNDirectMessageFetchConversationPageOperation *fetchOperation; // @synthesize fetchOperation=_fetchOperation;
@property(retain) NSOperationQueue *queue; // @synthesize queue=_queue;
@property(copy, nonatomic) CDUnknownBlockType paginationCompletionBlock; // @synthesize paginationCompletionBlock=_paginationCompletionBlock;
@property(readonly, nonatomic) long long maxEventID; // @synthesize maxEventID=_maxEventID;
@property(readonly, nonatomic) TFNDirectMessageModel *model; // @synthesize model=_model;
@property(readonly, nonatomic) TFNDirectMessageConversation *conversation; // @synthesize conversation=_conversation;
- (void).cxx_destruct;
- (void)bulkDecryptOperation:(id)arg1 didFailWithErrors:(id)arg2;
- (void)bulkDecryptOperationDidSucceed:(id)arg1;
- (void)fetchConversationPageOperation:(id)arg1 didFailWithError:(id)arg2;
- (void)fetchConversationPageOperation:(id)arg1 didSucceedWithResponse:(id)arg2;
- (void)run;
- (void)completeOperation;
- (void)cancel;
- (id)initWithConversation:(id)arg1 model:(id)arg2 maxEventID:(long long)arg3 cryptographyService:(id)arg4 completion:(CDUnknownBlockType)arg5;

@end

