//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <TFSUtilities/TFSConcurrentOperation.h>

@class NSArray, NSDictionary, TFNDirectMessageCryptographyService;
@protocol TFNDirectMessageBulkDecryptOperationDelegate;

@interface TFNDirectMessageBulkDecryptOperation : TFSConcurrentOperation
{
    NSDictionary *_outgoingPlaintextByEncryptedText;
    NSArray *_messages;
    TFNDirectMessageCryptographyService *_cryptographyService;
    id <TFNDirectMessageBulkDecryptOperationDelegate> _delegate;
}

@property __weak id <TFNDirectMessageBulkDecryptOperationDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) TFNDirectMessageCryptographyService *cryptographyService; // @synthesize cryptographyService=_cryptographyService;
@property(copy) NSArray *messages; // @synthesize messages=_messages;
@property(copy) NSDictionary *outgoingPlaintextByEncryptedText; // @synthesize outgoingPlaintextByEncryptedText=_outgoingPlaintextByEncryptedText;
- (void).cxx_destruct;
- (void)run;
- (id)initWithCryptographyService:(id)arg1;

@end

