//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <T1Twitter/NSCoding-Protocol.h>
#import <T1Twitter/TFNDirectMessageConversation-Protocol.h>
#import <T1Twitter/TFNDirectMessageConversationActions-Protocol.h>

@class NSArray, NSDate, NSMutableArray, NSMutableOrderedSet, NSOperationQueue, NSString, TFNDirectMessageComposition, TFNDirectMessageContext, TFNDirectMessageConversationIdentifier, TFNDirectMessageConversationPageOperation, TFNDirectMessageConversationParticipant, TFNDirectMessageFetchConversationMetadataOperation, TFNDirectMessageInbox, TFNDirectMessageMarkConversationAsReadOperation, TFNDirectMessageModel, TFNDirectMessageRenameConversationOperation, TFNDirectMessageUpdateGroupAvatarOperation, TFNDirectMessageUpdateMentionNotificationsSettingOperation, TFNDirectMessageUpdateMuteSettingsOperation, TFNTwitterEntityImageInfo;
@protocol TFNDirectMessageConversation, TFNDirectMessageConversationEntry, TFNDirectMessageConversationParticipant, TFNDirectMessageUser;

@interface TFNDirectMessageConversation : NSObject <NSCoding, TFNDirectMessageConversation, TFNDirectMessageConversationActions>
{
    _Bool _trusted;
    _Bool _notificationsDisabled;
    _Bool _mentionNotificationsDisabled;
    _Bool _trustedPending;
    _Bool _hasMoreEntries;
    _Bool _readOnly;
    _Bool _partial;
    _Bool _participantsNeedSorting;
    _Bool _hasPendingAvatarInfo;
    _Bool _hasPendingConversationName;
    _Bool _hasPendingMentionNotificationsDisabled;
    _Bool _pendingMentionNotificationsDisabled;
    _Bool _hasPendingNotificationsDisabled;
    _Bool _pendingNotificationsDisabled;
    TFNTwitterEntityImageInfo *_avatarInfo;
    TFNDirectMessageContext *_context;
    NSString *_conversationName;
    NSDate *_muteExpirationTime;
    long long _lastReadEventID;
    TFNDirectMessageModel *_directMessageModel;
    TFNDirectMessageInbox *_inbox;
    long long _minEntryID;
    TFNDirectMessageComposition *_composition;
    long long _creatorID;
    NSDate *_latestUpdateTime;
    NSString *_initialMessageRequestID;
    NSOperationQueue *_directMessageOperationQueue;
    TFNDirectMessageConversationIdentifier *_identifier;
    NSDate *_createTime;
    NSMutableArray *_entryList;
    NSMutableOrderedSet *_participantsSet;
    long long _sortEventID;
    NSString *_trustedDeviceID;
    NSString *_trustedIdentityKey;
    TFNDirectMessageFetchConversationMetadataOperation *_currentRefreshOperation;
    TFNDirectMessageRenameConversationOperation *_currentRenameOperation;
    TFNDirectMessageUpdateGroupAvatarOperation *_currentUpdateGroupAvatarOperation;
    TFNDirectMessageUpdateMentionNotificationsSettingOperation *_currentUpdateMentionNotificationsSettingOperation;
    TFNDirectMessageUpdateMuteSettingsOperation *_currentUpdateDisableNotificationsOperation;
    TFNDirectMessageMarkConversationAsReadOperation *_currentMarkConversationAsReadOperation;
    TFNDirectMessageConversationPageOperation *_currentPageOperation;
    TFNTwitterEntityImageInfo *_pendingAvatarInfo;
    NSString *_pendingConversationName;
    long long _pendingLastReadEventID;
    NSDate *_pendingMuteExpirationTime;
}

+ (unsigned long long)maximumConversationNameLength;
@property(retain, nonatomic) NSDate *pendingMuteExpirationTime; // @synthesize pendingMuteExpirationTime=_pendingMuteExpirationTime;
@property(nonatomic, getter=isPendingNotificationsDisabled) _Bool pendingNotificationsDisabled; // @synthesize pendingNotificationsDisabled=_pendingNotificationsDisabled;
@property(nonatomic) _Bool hasPendingNotificationsDisabled; // @synthesize hasPendingNotificationsDisabled=_hasPendingNotificationsDisabled;
@property(nonatomic, getter=isPendingMentionNotificationsDisabled) _Bool pendingMentionNotificationsDisabled; // @synthesize pendingMentionNotificationsDisabled=_pendingMentionNotificationsDisabled;
@property(nonatomic) _Bool hasPendingMentionNotificationsDisabled; // @synthesize hasPendingMentionNotificationsDisabled=_hasPendingMentionNotificationsDisabled;
@property(nonatomic) long long pendingLastReadEventID; // @synthesize pendingLastReadEventID=_pendingLastReadEventID;
@property(copy, nonatomic) NSString *pendingConversationName; // @synthesize pendingConversationName=_pendingConversationName;
@property(nonatomic) _Bool hasPendingConversationName; // @synthesize hasPendingConversationName=_hasPendingConversationName;
@property(retain, nonatomic) TFNTwitterEntityImageInfo *pendingAvatarInfo; // @synthesize pendingAvatarInfo=_pendingAvatarInfo;
@property(nonatomic) _Bool hasPendingAvatarInfo; // @synthesize hasPendingAvatarInfo=_hasPendingAvatarInfo;
@property(nonatomic) __weak TFNDirectMessageConversationPageOperation *currentPageOperation; // @synthesize currentPageOperation=_currentPageOperation;
@property(nonatomic) __weak TFNDirectMessageMarkConversationAsReadOperation *currentMarkConversationAsReadOperation; // @synthesize currentMarkConversationAsReadOperation=_currentMarkConversationAsReadOperation;
@property(nonatomic) __weak TFNDirectMessageUpdateMuteSettingsOperation *currentUpdateDisableNotificationsOperation; // @synthesize currentUpdateDisableNotificationsOperation=_currentUpdateDisableNotificationsOperation;
@property(nonatomic) __weak TFNDirectMessageUpdateMentionNotificationsSettingOperation *currentUpdateMentionNotificationsSettingOperation; // @synthesize currentUpdateMentionNotificationsSettingOperation=_currentUpdateMentionNotificationsSettingOperation;
@property(nonatomic) __weak TFNDirectMessageUpdateGroupAvatarOperation *currentUpdateGroupAvatarOperation; // @synthesize currentUpdateGroupAvatarOperation=_currentUpdateGroupAvatarOperation;
@property(nonatomic) __weak TFNDirectMessageRenameConversationOperation *currentRenameOperation; // @synthesize currentRenameOperation=_currentRenameOperation;
@property(nonatomic) __weak TFNDirectMessageFetchConversationMetadataOperation *currentRefreshOperation; // @synthesize currentRefreshOperation=_currentRefreshOperation;
@property(copy, nonatomic) NSString *trustedIdentityKey; // @synthesize trustedIdentityKey=_trustedIdentityKey;
@property(copy, nonatomic) NSString *trustedDeviceID; // @synthesize trustedDeviceID=_trustedDeviceID;
@property(nonatomic) long long sortEventID; // @synthesize sortEventID=_sortEventID;
@property(readonly, nonatomic) NSMutableOrderedSet *participantsSet; // @synthesize participantsSet=_participantsSet;
@property(nonatomic) _Bool participantsNeedSorting; // @synthesize participantsNeedSorting=_participantsNeedSorting;
@property(readonly, nonatomic) NSMutableArray *entryList; // @synthesize entryList=_entryList;
@property(retain, nonatomic) NSDate *createTime; // @synthesize createTime=_createTime;
@property(retain, nonatomic) TFNDirectMessageConversationIdentifier *identifier; // @synthesize identifier=_identifier;
@property(readonly, nonatomic) NSOperationQueue *directMessageOperationQueue; // @synthesize directMessageOperationQueue=_directMessageOperationQueue;
@property(copy, nonatomic) NSString *initialMessageRequestID; // @synthesize initialMessageRequestID=_initialMessageRequestID;
@property(nonatomic, getter=isPartial) _Bool partial; // @synthesize partial=_partial;
@property(retain, nonatomic) NSDate *latestUpdateTime; // @synthesize latestUpdateTime=_latestUpdateTime;
@property(nonatomic) long long creatorID; // @synthesize creatorID=_creatorID;
@property(nonatomic, getter=isReadOnly) _Bool readOnly; // @synthesize readOnly=_readOnly;
@property(nonatomic) _Bool hasMoreEntries; // @synthesize hasMoreEntries=_hasMoreEntries;
@property(retain, nonatomic) TFNDirectMessageComposition *composition; // @synthesize composition=_composition;
@property(nonatomic) _Bool trustedPending; // @synthesize trustedPending=_trustedPending;
@property(nonatomic) long long minEntryID; // @synthesize minEntryID=_minEntryID;
@property(nonatomic) __weak TFNDirectMessageInbox *inbox; // @synthesize inbox=_inbox;
@property(retain, nonatomic) TFNDirectMessageModel *directMessageModel; // @synthesize directMessageModel=_directMessageModel;
@property(readonly, nonatomic) TFNDirectMessageContext *context; // @synthesize context=_context;
- (void).cxx_destruct;
- (void)_enqueueMetadataUpdateNotification;
- (void)_enqueueTimelineUpdateNotification;
- (void)_notifyIfRecipientIdentityTrustedChanges:(CDUnknownBlockType)arg1;
- (void)_didAttemptToLoadTrustedIdentityWithSuccess:(_Bool)arg1 deviceID:(id)arg2 identityKey:(id)arg3 error:(id)arg4;
- (void)_attemptToLoadTrustedIdentity;
- (void)_attemptToSaveRecipientDeviceID:(id)arg1 identityKey:(id)arg2 asTrustedIdentity:(_Bool)arg3;
- (void)_synchronizeRecipientIdentity;
- (void)_sortParticipantsIfNeeded;
- (_Bool)_shouldAssimilateConversation:(id)arg1;
- (void)removeEntriesThroughID:(long long)arg1;
- (void)removeEntry:(id)arg1;
- (void)addWelcomeMessage:(id)arg1;
- (void)assimilateConversationMetadata:(id)arg1;
- (void)assimilateCursor:(id)arg1;
- (void)assimilateConversation:(id)arg1;
- (void)_postTrustStateChanged;
@property(nonatomic, getter=isTrusted) _Bool trusted; // @synthesize trusted=_trusted;
- (void)removeGroupAvatar;
- (void)rename:(id)arg1;
- (void)removeParticipants:(id)arg1;
- (void)removeParticipant:(id)arg1;
- (void)addParticipants:(id)arg1;
- (void)didBecomeDefinitive;
- (void)loadOneToOneParticipantsFromUserCache:(id)arg1;
- (void)removeUsers:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)addUsers:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)addEntry:(id)arg1 replacingEntry:(id)arg2;
- (void)addEntry:(id)arg1 replacingLocalEntryWithIdentifier:(id)arg2;
- (void)addEntry:(id)arg1;
- (void)_sendLastReadEventID:(long long)arg1;
- (void)_scheduleMentionsNotificationOperation:(id)arg1;
- (void)_scheduleNotificationOperation:(id)arg1;
- (void)_scheduleGroupAvatarOperation:(id)arg1;
- (void)_sendMarkAsReadIfPending;
- (void)refreshWithCompletion:(CDUnknownBlockType)arg1;
- (void)loadMetadataIfNeededWithCompletion:(CDUnknownBlockType)arg1;
- (void)refresh;
@property(readonly, nonatomic, getter=isRecipientIdentityTrusted) _Bool recipientIdentityTrusted;
- (void)setRecipientDeviceID:(id)arg1 recipientIdentityKey:(id)arg2 source:(unsigned long long)arg3;
@property(readonly, copy, nonatomic) NSString *recipientIdentityKey;
@property(readonly, copy, nonatomic) NSString *recipientDeviceID;
- (void)unmarkEntryAsSpam:(id)arg1;
- (void)markEntryAsSpam:(id)arg1;
- (void)markEntryAsAbuse:(id)arg1;
@property(readonly, nonatomic) NSDate *muteExpirationTime; // @synthesize muteExpirationTime=_muteExpirationTime;
@property(readonly, nonatomic) _Bool notificationsDisabled; // @synthesize notificationsDisabled=_notificationsDisabled;
- (void)revertPendingNotificationsDisabled;
- (void)setNotificationsDisabled:(_Bool)arg1 expirationTime:(id)arg2 source:(unsigned long long)arg3;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, nonatomic) CDStruct_778018ce nextEntrySortKey;
@property(readonly, nonatomic) unsigned long long entryCount;
- (id)admin;
- (id)recipient;
@property(readonly, nonatomic) TFNDirectMessageConversationParticipant *recipientParticipant;
@property(readonly, nonatomic) id <TFNDirectMessageUser> perspectivalUser;
@property(readonly, nonatomic) id <TFNDirectMessageConversationParticipant> perspectivalParticipant;
@property(readonly, nonatomic) NSArray *participantsExcludingPerspectivalUser;
@property(copy, nonatomic) NSArray *participants;
- (void)setLastReadEventID:(long long)arg1 source:(unsigned long long)arg2;
@property(readonly, nonatomic) long long lastReadEventID; // @synthesize lastReadEventID=_lastReadEventID;
@property(readonly, nonatomic) CDStruct_912cb5d2 readState;
@property(readonly, nonatomic) _Bool isIdentifiable;
@property(readonly, nonatomic, getter=isEmpty) _Bool empty;
@property(readonly, nonatomic) _Bool unread;
- (void)revertPendingMentionNotificationsDisabled;
- (void)setMentionNotificationsDisabled:(_Bool)arg1 source:(unsigned long long)arg2;
@property(readonly, nonatomic) _Bool mentionNotificationsDisabled; // @synthesize mentionNotificationsDisabled=_mentionNotificationsDisabled;
@property(readonly, copy, nonatomic) NSString *conversationName; // @synthesize conversationName=_conversationName;
- (void)revertPendingConversationName;
- (void)setConversationName:(id)arg1 source:(unsigned long long)arg2;
@property(readonly, nonatomic) TFNTwitterEntityImageInfo *avatarInfo; // @synthesize avatarInfo=_avatarInfo;
- (void)revertPendingAvatarInfo;
- (void)setAvatarInfo:(id)arg1 source:(unsigned long long)arg2;
@property(readonly, nonatomic, getter=isDraft) _Bool draft;
@property(readonly, nonatomic) _Bool isSelfConversation;
@property(readonly, nonatomic, getter=isEncrypted) _Bool encrypted;
@property(readonly, nonatomic) long long conversationType;
@property(readonly, copy, nonatomic) NSString *requestID;
@property(readonly, copy, nonatomic) NSString *conversationID;
- (_Bool)validateConversationName:(id)arg1;
- (void)markRecipientIdentityAsTrusted;
- (void)lookupFingerprintWithCompletion:(CDUnknownBlockType)arg1;
- (long long)compare:(id)arg1;
- (void)pruneOldEntriesToCount:(unsigned long long)arg1 preservingUnreadConversations:(_Bool)arg2;
- (void)pruneOldEntries;
- (void)updateReadOnlyState:(_Bool)arg1;
- (void)updateGroupAvatarWithAsset:(id)arg1 localURL:(id)arg2;
- (void)sendMessage:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)markAsRead;
- (void)loadMoreEntriesWithCompletion:(CDUnknownBlockType)arg1;
- (void)cancelDraftMessage:(id)arg1;
- (void)deleteMessage:(id)arg1;
- (void)deleteConversation;
- (void)accept;
- (void)resetComposition;
- (id)latestEntryOfType:(unsigned long long)arg1;
@property(readonly, nonatomic) id <TFNDirectMessageConversationEntry> latestEntry;
- (id)entryAtIndex:(unsigned long long)arg1;
- (void)disableMentionNotifications;
- (void)enableMentionNotifications;
- (void)disableNotificationsForDuration:(unsigned long long)arg1;
- (void)enableNotifications;
@property(readonly, nonatomic) id <TFNDirectMessageConversation> conversation;
@property(readonly, nonatomic) NSArray *allEntries;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
@property(readonly) unsigned long long hash;
- (_Bool)isEqual:(id)arg1;
- (id)initWithIdentifier:(id)arg1 context:(id)arg2;
- (id)initWithConversationID:(id)arg1 requestID:(id)arg2 context:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *description;
@property(readonly) Class superclass;

@end

