//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <TFSUtilities/TFSConcurrentOperation.h>

@class NSArray, NSDictionary, TFNDirectMessageCryptographyService;

@interface TFNDirectMessagePreprocessDecryptionEventsOperation : TFSConcurrentOperation
{
    NSArray *_events;
    NSDictionary *_outgoingPlaintextByEncryptedText;
    TFNDirectMessageCryptographyService *_cryptographyService;
}

@property(readonly, nonatomic) TFNDirectMessageCryptographyService *cryptographyService; // @synthesize cryptographyService=_cryptographyService;
@property(copy) NSDictionary *outgoingPlaintextByEncryptedText; // @synthesize outgoingPlaintextByEncryptedText=_outgoingPlaintextByEncryptedText;
@property(copy) NSArray *events; // @synthesize events=_events;
- (void).cxx_destruct;
- (void)private_preprocessNextEvent:(id)arg1 cryptographyService:(id)arg2 outgoingPlaintextByEncryptedText:(id)arg3;
- (void)run;
- (id)initWithCryptographyService:(id)arg1;

@end

