//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, TFNDirectMessageActivityLog, TFNDirectMessageContext, TFNDirectMessageContextState, TFNDirectMessageModel, TFNTwitterAccountModel;
@protocol OS_dispatch_queue, TFNDirectMessageInboxActions, TFNDirectMessageServiceRefreshObserver;

@interface TFNDirectMessageService : NSObject
{
    TFNDirectMessageContextState *_stagedModelContextState;
    TFNDirectMessageContext *_context;
    TFNDirectMessageModel *_model;
    id <TFNDirectMessageServiceRefreshObserver> _refreshObserver;
    NSString *_accountID;
    long long _authenticatedUserID;
    TFNTwitterAccountModel *_accountModel;
    NSObject<OS_dispatch_queue> *_modelDiskLoadQueue;
}

+ (void)private_reportErrorWhileDeleting:(id)arg1;
+ (void)invalidateWithAccountID:(id)arg1 completion:(CDUnknownBlockType)arg2;
+ (void)purgeAllCaches;
+ (id)registeredServices;
+ (id)sharedDirectMessageServiceForAccount:(id)arg1;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *modelDiskLoadQueue; // @synthesize modelDiskLoadQueue=_modelDiskLoadQueue;
@property(readonly, nonatomic) TFNTwitterAccountModel *accountModel; // @synthesize accountModel=_accountModel;
@property(readonly, nonatomic) long long authenticatedUserID; // @synthesize authenticatedUserID=_authenticatedUserID;
@property(readonly, copy, nonatomic) NSString *accountID; // @synthesize accountID=_accountID;
@property(nonatomic) __weak id <TFNDirectMessageServiceRefreshObserver> refreshObserver; // @synthesize refreshObserver=_refreshObserver;
- (void).cxx_destruct;
- (void)private_finishAsynchronousModelLoad;
- (id)private_consumeStagedModelContextState;
- (void)saveToDisk;
- (void)loadFromDiskSynchronously:(_Bool)arg1;
@property(readonly, nonatomic) TFNDirectMessageActivityLog *activityLog;
- (id)conversationActionsWithSelectedUsers:(id)arg1;
- (id)conversationActionsWithRecipientUserID:(long long)arg1;
- (id)conversationActionsWithIdentifier:(id)arg1;
- (id)userForUserID:(long long)arg1;
- (void)reset;
- (id)initWithAccountID:(id)arg1 authenticatedUserID:(long long)arg2 accountModel:(id)arg3;
- (id)init;
- (id)debugDescription;
- (id)description;
@property(readonly, nonatomic) id <TFNDirectMessageInboxActions> inboxActions;
@property(readonly, nonatomic) TFNDirectMessageContext *context; // @synthesize context=_context;
@property(retain, nonatomic) TFNDirectMessageModel *model; // @synthesize model=_model;

@end

