//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <T1Twitter/TFNDirectMessageAPICommandOperation.h>

@class NSDictionary, NSNumber, NSString;
@protocol TFNDirectMessagePublishEncryptionKeysOperationDelegate;

@interface TFNDirectMessagePublishEncryptionKeysOperation : TFNDirectMessageAPICommandOperation
{
    NSString *_accountID;
    id <TFNDirectMessagePublishEncryptionKeysOperationDelegate> _delegate;
    NSString *_identityKey;
    NSNumber *_signedPreKeyID;
    NSString *_signedPreKey;
    NSString *_signedPreKeySignature;
    NSDictionary *_preKeys;
}

@property(copy) NSDictionary *preKeys; // @synthesize preKeys=_preKeys;
@property(copy) NSString *signedPreKeySignature; // @synthesize signedPreKeySignature=_signedPreKeySignature;
@property(copy) NSString *signedPreKey; // @synthesize signedPreKey=_signedPreKey;
@property(retain) NSNumber *signedPreKeyID; // @synthesize signedPreKeyID=_signedPreKeyID;
@property(copy) NSString *identityKey; // @synthesize identityKey=_identityKey;
@property __weak id <TFNDirectMessagePublishEncryptionKeysOperationDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, copy, nonatomic) NSString *accountID; // @synthesize accountID=_accountID;
- (void).cxx_destruct;
- (void)failedWithError:(id)arg1;
- (void)succeededWithObject:(id)arg1;
- (id)makeCommandWithCompletion:(CDUnknownBlockType)arg1;
- (id)initWithAccountID:(id)arg1;

@end

