//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <TFSUtilities/TFSConcurrentOperation.h>

#import <T1Twitter/TFNDirectMessageBulkDecryptOperationDelegate-Protocol.h>
#import <T1Twitter/TFNDirectMessageFetchInboxPageOperationDelegate-Protocol.h>

@class NSOperation, NSOperationQueue, NSString, TFNDirectMessageBulkDecryptOperation, TFNDirectMessageFetchInboxPageOperation, TFNDirectMessageInboxTimeline, TFNDirectMessageModel, TFNDirectMessageProcessEntriesResponseOperation;

@interface TFNDirectMessageInboxPageOperation : TFSConcurrentOperation <TFNDirectMessageBulkDecryptOperationDelegate, TFNDirectMessageFetchInboxPageOperationDelegate>
{
    NSString *_accountID;
    TFNDirectMessageInboxTimeline *_timeline;
    long long _maxEntryID;
    NSOperationQueue *_queue;
    TFNDirectMessageModel *_model;
    TFNDirectMessageFetchInboxPageOperation *_fetchOperation;
    TFNDirectMessageBulkDecryptOperation *_bulkDecryptOperation;
    TFNDirectMessageProcessEntriesResponseOperation *_processEntriesOperation;
    NSOperation *_completionOperation;
}

@property(retain, nonatomic) NSOperation *completionOperation; // @synthesize completionOperation=_completionOperation;
@property(retain, nonatomic) TFNDirectMessageProcessEntriesResponseOperation *processEntriesOperation; // @synthesize processEntriesOperation=_processEntriesOperation;
@property(retain, nonatomic) TFNDirectMessageBulkDecryptOperation *bulkDecryptOperation; // @synthesize bulkDecryptOperation=_bulkDecryptOperation;
@property(retain, nonatomic) TFNDirectMessageFetchInboxPageOperation *fetchOperation; // @synthesize fetchOperation=_fetchOperation;
@property(retain, nonatomic) TFNDirectMessageModel *model; // @synthesize model=_model;
@property(retain) NSOperationQueue *queue; // @synthesize queue=_queue;
@property(readonly, nonatomic) long long maxEntryID; // @synthesize maxEntryID=_maxEntryID;
@property(readonly, nonatomic) TFNDirectMessageInboxTimeline *timeline; // @synthesize timeline=_timeline;
@property(readonly, copy, nonatomic) NSString *accountID; // @synthesize accountID=_accountID;
- (void).cxx_destruct;
- (void)bulkDecryptOperation:(id)arg1 didFailWithErrors:(id)arg2;
- (void)bulkDecryptOperationDidSucceed:(id)arg1;
- (void)fetchInboxPageOperation:(id)arg1 didFailWithError:(id)arg2;
- (void)fetchInboxPageOperation:(id)arg1 didSucceedWithResponse:(id)arg2;
- (void)run;
- (void)cancel;
- (id)initWithAccountID:(id)arg1 timeline:(id)arg2 maxEntryID:(long long)arg3 model:(id)arg4 filterLowQuality:(id)arg5 cryptographyService:(id)arg6;
- (id)init;

@end

