//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface TFNKeyboardMonitor : NSObject
{
    _Bool _monitoringKeyboardNotifications;
    _Bool _keyboardActive;
    _Bool _localKeyboard;
    long long _keyboardVisibility;
    struct CGRect _keyboardFrame;
    struct CGRect _keyboardFrameEnd;
}

+ (struct CGRect)_visibleKeyboardFrameFromKeyboardFrame:(struct CGRect)arg1;
+ (id)sharedMonitor;
@property(readonly, nonatomic) long long keyboardVisibility; // @synthesize keyboardVisibility=_keyboardVisibility;
@property(nonatomic) struct CGRect keyboardFrameEnd; // @synthesize keyboardFrameEnd=_keyboardFrameEnd;
@property(nonatomic) struct CGRect keyboardFrame; // @synthesize keyboardFrame=_keyboardFrame;
@property(nonatomic, getter=isLocalKeyboard) _Bool localKeyboard; // @synthesize localKeyboard=_localKeyboard;
@property(nonatomic, getter=isKeyboardActive) _Bool keyboardActive; // @synthesize keyboardActive=_keyboardActive;
@property(nonatomic, getter=isMonitoringKeyboardNotifications) _Bool monitoringKeyboardNotifications; // @synthesize monitoringKeyboardNotifications=_monitoringKeyboardNotifications;
- (id)description;
- (void)_postNotification:(id)arg1;
- (void)_postNotificationWithName:(id)arg1 userInfo:(id)arg2;
- (void)_repostSystemNotification:(id)arg1 withName:(id)arg2;
@property(readonly, nonatomic) struct CGRect visibleKeyboardFrameEnd;
@property(readonly, nonatomic) struct CGRect visibleKeyboardFrame;
- (void)_resetState;
- (void)_updateStateFromKeyboardPostNotification:(id)arg1;
- (void)_updateStateFromKeyboardPreNotification:(id)arg1;
- (id)_systemKeyboardNotificationUserInfoWithFrame:(struct CGRect)arg1 isLocal:(_Bool)arg2;
- (id)_keyboardWindow;
- (void)_applicationDidBecomeActive;
- (void)_currentInputModeDidChange:(id)arg1;
- (void)_keyboardDidChangeFrame:(id)arg1;
- (void)_keyboardWillChangeFrame:(id)arg1;
- (void)_keyboardDidHide:(id)arg1;
- (void)_keyboardWillHide:(id)arg1;
- (void)_keyboardDidShow:(id)arg1;
- (void)_keyboardWillShow:(id)arg1;
- (void)_unregisterForKeyboardNotifications;
- (void)_registerForKeyboardNotifications;
- (void)endMonitoringKeyboardNotifications;
- (void)beginMonitoringKeyboardNotifications;
- (id)init;

@end

