//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <MapKit/MKMapSnapshotter.h>

@class UIImage;
@protocol TFNMapSnapshotterDelegate;

@interface TFNMapSnapshotter : MKMapSnapshotter
{
    UIImage *_mapPinImage;
    id <TFNMapSnapshotterDelegate> _delegate;
}

+ (id)snapshotterForMapView:(id)arg1;
@property(nonatomic) __weak id <TFNMapSnapshotterDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) UIImage *mapPinImage; // @synthesize mapPinImage=_mapPinImage;
- (void).cxx_destruct;
- (void)_takeSnapshot:(id)arg1 withError:(id)arg2;
- (void)takeSnapshot;
- (void)dealloc;

@end

