//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <T1Twitter/TFNOnboardingSubtask.h>

@class NSString, TFNOnboardingNavigationLink, TFNOnboardingRichText;

@interface TFNOnboardingEnterTextSubtask : TFNOnboardingSubtask
{
    _Bool _multiline;
    TFNOnboardingRichText *_primaryText;
    TFNOnboardingRichText *_secondaryText;
    NSString *_hintText;
    NSString *_defaultText;
    NSString *_defaultSuggestionID;
    long long _maxLength;
    long long _keyboardType;
    TFNOnboardingNavigationLink *_nextLink;
    TFNOnboardingNavigationLink *_skipLink;
    long long _suggestionType;
}

+ (long long)version;
+ (id)typeNames;
@property(readonly, nonatomic) long long suggestionType; // @synthesize suggestionType=_suggestionType;
@property(readonly, nonatomic) TFNOnboardingNavigationLink *skipLink; // @synthesize skipLink=_skipLink;
@property(readonly, nonatomic) TFNOnboardingNavigationLink *nextLink; // @synthesize nextLink=_nextLink;
@property(readonly, nonatomic) long long keyboardType; // @synthesize keyboardType=_keyboardType;
@property(readonly, nonatomic) _Bool multiline; // @synthesize multiline=_multiline;
@property(readonly, nonatomic) long long maxLength; // @synthesize maxLength=_maxLength;
@property(readonly, nonatomic) NSString *defaultSuggestionID; // @synthesize defaultSuggestionID=_defaultSuggestionID;
@property(readonly, nonatomic) NSString *defaultText; // @synthesize defaultText=_defaultText;
@property(readonly, nonatomic) NSString *hintText; // @synthesize hintText=_hintText;
@property(readonly, nonatomic) TFNOnboardingRichText *secondaryText; // @synthesize secondaryText=_secondaryText;
@property(readonly, nonatomic) TFNOnboardingRichText *primaryText; // @synthesize primaryText=_primaryText;
- (void).cxx_destruct;
- (id)initWithJSONDictionary:(id)arg1 subtaskID:(id)arg2 typeName:(id)arg3 backNavigationType:(long long)arg4 error:(id *)arg5;

@end

