//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIActivity.h>

@class NSURL, TFNTwitterAccount, TFSTwitterScribeContext;

@interface TFNOpenInChromeActivity : UIActivity
{
    NSURL *_url;
    TFNTwitterAccount *_account;
    TFSTwitterScribeContext *_scribeContext;
}

@property(readonly, copy, nonatomic) TFSTwitterScribeContext *scribeContext; // @synthesize scribeContext=_scribeContext;
@property(readonly, nonatomic) TFNTwitterAccount *account; // @synthesize account=_account;
@property(copy, nonatomic) NSURL *url; // @synthesize url=_url;
- (void).cxx_destruct;
- (void)performActivity;
- (_Bool)canPerformWithActivityItems:(id)arg1;
- (id)activityType;
- (id)activityImage;
- (id)activityTitle;
- (id)init;
- (id)initWithAccount:(id)arg1 scribeContext:(id)arg2;

@end

