//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface TFNPrefetchingViewInitializer : NSObject
{
    CDUnknownBlockType _modelIdentifier;
    CDUnknownBlockType _viewIdentifier;
    CDUnknownBlockType _initializeView;
    CDUnknownBlockType _prepareView;
}

@property(readonly, copy, nonatomic) CDUnknownBlockType prepareView; // @synthesize prepareView=_prepareView;
@property(readonly, copy, nonatomic) CDUnknownBlockType initializeView; // @synthesize initializeView=_initializeView;
@property(readonly, copy, nonatomic) CDUnknownBlockType viewIdentifier; // @synthesize viewIdentifier=_viewIdentifier;
@property(readonly, copy, nonatomic) CDUnknownBlockType modelIdentifier; // @synthesize modelIdentifier=_modelIdentifier;
- (void).cxx_destruct;
- (void)recycleView:(id)arg1 withCache:(id)arg2;
- (id)prepareViewWithCache:(id)arg1;
- (id)initializeViewWithCache:(id)arg1;
- (id)initWithModelIdentifier:(CDUnknownBlockType)arg1 viewIdentifier:(CDUnknownBlockType)arg2 initializeView:(CDUnknownBlockType)arg3 prepareView:(CDUnknownBlockType)arg4;
- (id)init;
- (id)initWithViewAdapter:(id)arg1 viewModel:(id)arg2;

@end

