//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <StoreKit/SKStoreProductViewController.h>

#import <T1Twitter/SKStoreProductViewControllerDelegate-Protocol.h>

@class NSNumber, NSString;

@interface TFNStoreProductViewController : SKStoreProductViewController <SKStoreProductViewControllerDelegate>
{
    unsigned long long _allowedInterfaceOrientations;
    NSNumber *_itunesID;
    CDUnknownBlockType _loadCompletion;
}

@property(copy, nonatomic) CDUnknownBlockType loadCompletion; // @synthesize loadCompletion=_loadCompletion;
@property(retain, nonatomic) NSNumber *itunesID; // @synthesize itunesID=_itunesID;
@property(nonatomic) unsigned long long allowedInterfaceOrientations; // @synthesize allowedInterfaceOrientations=_allowedInterfaceOrientations;
- (void).cxx_destruct;
- (void)_tfn_deliverStatus:(long long)arg1;
- (void)productViewControllerDidFinish:(id)arg1;
- (unsigned long long)supportedInterfaceOrientations;
- (id)initWithItunesIdentifier:(id)arg1 loadCompletion:(CDUnknownBlockType)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

