//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <T1Twitter/NSObject-Protocol.h>

@class NSArray, TFNTwitterStatus;
@protocol TFNTwitterHomeStreamPruningParameters, TFNTwitterScribeImpressionCache, TFNTwitterTimelineObject;

@protocol TFNTwitterDynamicTimelineManager <NSObject>
+ (_Bool)hasSeenStatus:(TFNTwitterStatus *)arg1 inImpressionCache:(id <TFNTwitterScribeImpressionCache>)arg2 withMinImpressionDuration:(unsigned long long)arg3;
- (void)replacePrunedItem:(id <TFNTwitterTimelineObject>)arg1 withItem:(id <TFNTwitterTimelineObject>)arg2;
- (void)streamDidLoadBottom:(NSArray *)arg1;
- (void)streamDidAddItemsInRange:(struct _NSRange)arg1;
- (NSArray *)applyModificationsToStreamObjects:(NSArray *)arg1;
- (_Bool)hasPrunedItems;
- (_Bool)pruneSeenItemsFromStreamObjects:(NSArray *)arg1 currentStreamOrdering:(NSArray *)arg2;
- (void)setParametersAndPostPruningOption:(id <TFNTwitterHomeStreamPruningParameters>)arg1;
@end

