//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <T1Twitter/NSCopying-Protocol.h>
#import <T1Twitter/NSMutableCopying-Protocol.h>

@class TIPImagePipeline;
@protocol NSCoding><NSCopying;

@interface TFNTwitterMediaAssetRenderingOptions : NSObject <NSCopying, NSMutableCopying>
{
    TIPImagePipeline *_imagePipeline;
    NSObject<NSCoding><NSCopying> *_editParameters;
    CDUnknownBlockType _progressHandler;
    _Bool _videoExportSessionVideoCompositionDisabled;
}

@property(readonly, nonatomic, getter=isVideoExportSessionVideoCompositionDisabled) _Bool videoExportSessionVideoCompositionDisabled; // @synthesize videoExportSessionVideoCompositionDisabled=_videoExportSessionVideoCompositionDisabled;
@property(readonly, copy, nonatomic) CDUnknownBlockType progressHandler; // @synthesize progressHandler=_progressHandler;
@property(readonly, copy, nonatomic) NSObject<NSCoding><NSCopying> *editParameters; // @synthesize editParameters=_editParameters;
@property(readonly, nonatomic) TIPImagePipeline *imagePipeline; // @synthesize imagePipeline=_imagePipeline;
- (void).cxx_destruct;
- (id)mutableCopyWithZone:(struct _NSZone *)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithOptions:(id)arg1;
- (id)initWithImagePipeline:(id)arg1;
- (id)init;
- (id)initWithImagePipeline:(id)arg1 editParameters:(id)arg2 progressHandler:(CDUnknownBlockType)arg3 videoExportSessionVideoCompositionDisabled:(_Bool)arg4;

@end

