//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <T1Twitter/TFSPlistSerialization-Protocol.h>

@class NSArray, NSString, NSURL;

@interface TFNTwitterTimelineMessageEntryAction : NSObject <TFSPlistSerialization>
{
    _Bool _dismiss;
    NSString *_text;
    NSURL *_url;
    NSArray *_callbackEndpoints;
}

@property(readonly, nonatomic) NSArray *callbackEndpoints; // @synthesize callbackEndpoints=_callbackEndpoints;
@property(readonly, nonatomic) NSURL *url; // @synthesize url=_url;
@property(readonly, nonatomic) NSString *text; // @synthesize text=_text;
@property(readonly, nonatomic, getter=isDismissAction) _Bool dismiss; // @synthesize dismiss=_dismiss;
- (void).cxx_destruct;
- (id)plistDictionaryValue;
- (id)initWithPlistDictionary:(id)arg1;
- (id)action;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

