//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <T1Twitter/TFNTwitterInterest-Protocol.h>

@class NSDictionary, NSString;

@interface TFNTwitterTTTInterest : NSObject <TFNTwitterInterest>
{
    NSString *_interestId;
}

@property(readonly, nonatomic) NSString *interestId; // @synthesize interestId=_interestId;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSDictionary *jsonDictionary;
- (id)init;
- (id)initWithInterestId:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

