//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class TFSLRUDictionary;
@protocol OS_dispatch_queue;

@interface TFNTwitterCardStateManager : NSObject
{
    TFSLRUDictionary *_cardStateCache;
    NSObject<OS_dispatch_queue> *_cacheSerialQueue;
}

+ (id)sharedManager;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *cacheSerialQueue; // @synthesize cacheSerialQueue=_cacheSerialQueue;
@property(retain, nonatomic) TFSLRUDictionary *cardStateCache; // @synthesize cardStateCache=_cardStateCache;
- (void).cxx_destruct;
- (id)_cardStateIdForCardContext:(id)arg1;
- (void)_didReceiveMemoryWarning:(id)arg1;
- (id)objectForKey:(id)arg1 withCardContext:(id)arg2;
- (void)setObject:(id)arg1 forKey:(id)arg2 withCardContext:(id)arg3;
- (void)clearAll;
- (id)init;

@end

