//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <T1Twitter/TFSTwitterScribableItem-Protocol.h>

@class NSDictionary, NSNumber, NSString, TAVAnalyticsMediaIdentifier, TFNTwitterMediaInfo, TFNTwitterPromotedContent, TFNTwitterStatus;
@protocol TFNTwitterCardDataSource;

@protocol TFNTwitterAVPlayerSessionSource <TFSTwitterScribableItem>
@property(readonly, copy, nonatomic) TAVAnalyticsMediaIdentifier *contentMediaIdentifier;
@property(readonly, nonatomic) TFNTwitterPromotedContent *promotedContent;
@property(readonly, nonatomic) TFNTwitterStatus *playerStatus;
@property(readonly, nonatomic) NSNumber *playerStatusID;
@property(readonly, nonatomic) _Bool allowDynamicAd;
@property(readonly, nonatomic) id <TFNTwitterCardDataSource> cardDataSource;
@property(readonly, nonatomic) NSString *mediaScribeContentID;
@property(readonly, nonatomic) NSNumber *mediaScribePublisherID;
@property(readonly, nonatomic) NSDictionary *scribeParameters;
@property(readonly, nonatomic) _Bool isPlayable;
@property(readonly, nonatomic) _Bool isBroadcast;
@property(readonly, nonatomic) _Bool isLiveEvent;
@property(readonly, nonatomic) _Bool isThreeSixtyVideo;
@property(readonly, nonatomic) _Bool isAmplifyCardVideo;
@property(readonly, nonatomic) _Bool isPeriscope;
@property(readonly, nonatomic) _Bool isAdsVideoCard;
@property(readonly, nonatomic) _Bool isGIF;
@property(readonly, nonatomic) _Bool isVine;
@property(readonly, nonatomic) _Bool isMediaEntityVideo;
@property(readonly, nonatomic) TFNTwitterMediaInfo *primaryMediaInfo;
@property(readonly, nonatomic) NSString *mediaPlaylistUrl;
@property(readonly, nonatomic) long long fromUserID;
@end

