//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <T1Twitter/TFSPlistSerialization-Protocol.h>

@class NSArray, NSString, TFNTwitterCardData, TFNTwitterGeotag, TFNTwitterMediaInfo, TFNTwitterStatusTextRangeSet, TFSTwitterEntitySet, TFSTwitterEntityURL;

@interface TFNTwitterDisplayTextModelConfiguration : NSObject <TFSPlistSerialization>
{
    _Bool _isReply;
    _Bool _hasAttachment;
    NSString *_text;
    NSString *_fromUserName;
    long long _authenticatedUserID;
    NSString *_inReplyToUserName;
    TFSTwitterEntitySet *_entities;
    NSArray *_hitHighlights;
    TFNTwitterStatusTextRangeSet *_textRangeSet;
    TFNTwitterMediaInfo *_primaryMediaInfo;
    TFNTwitterGeotag *_geotag;
    TFSTwitterEntityURL *_trailingEntityURL;
    TFNTwitterCardData *_cardData;
    TFSTwitterEntityURL *_quotedStatusPermalinkEntity;
    NSString *_displayText;
    unsigned long long _displayTextOffset;
}

@property(readonly, nonatomic) unsigned long long displayTextOffset; // @synthesize displayTextOffset=_displayTextOffset;
@property(readonly, nonatomic) NSString *displayText; // @synthesize displayText=_displayText;
@property(readonly, nonatomic) TFSTwitterEntityURL *quotedStatusPermalinkEntity; // @synthesize quotedStatusPermalinkEntity=_quotedStatusPermalinkEntity;
@property(readonly, nonatomic) TFNTwitterCardData *cardData; // @synthesize cardData=_cardData;
@property(readonly, nonatomic) TFSTwitterEntityURL *trailingEntityURL; // @synthesize trailingEntityURL=_trailingEntityURL;
@property(readonly, nonatomic) TFNTwitterGeotag *geotag; // @synthesize geotag=_geotag;
@property(readonly, nonatomic) TFNTwitterMediaInfo *primaryMediaInfo; // @synthesize primaryMediaInfo=_primaryMediaInfo;
@property(readonly, nonatomic) TFNTwitterStatusTextRangeSet *textRangeSet; // @synthesize textRangeSet=_textRangeSet;
@property(readonly, nonatomic) NSArray *hitHighlights; // @synthesize hitHighlights=_hitHighlights;
@property(readonly, nonatomic) _Bool hasAttachment; // @synthesize hasAttachment=_hasAttachment;
@property(readonly, nonatomic) TFSTwitterEntitySet *entities; // @synthesize entities=_entities;
@property(readonly, nonatomic) NSString *inReplyToUserName; // @synthesize inReplyToUserName=_inReplyToUserName;
@property(readonly, nonatomic) _Bool isReply; // @synthesize isReply=_isReply;
@property(readonly, nonatomic) long long authenticatedUserID; // @synthesize authenticatedUserID=_authenticatedUserID;
@property(readonly, nonatomic) NSString *fromUserName; // @synthesize fromUserName=_fromUserName;
@property(readonly, nonatomic) NSString *text; // @synthesize text=_text;
- (void).cxx_destruct;
- (id)plistDictionaryValue;
- (id)initWithPlistDictionary:(id)arg1;
- (unsigned long long)maxLinesForOptions:(unsigned long long)arg1;
- (_Bool)isEqual:(id)arg1;
@property(readonly) unsigned long long hash;
- (id)initWithText:(id)arg1 fromUserName:(id)arg2 authenticatedUserID:(long long)arg3 isReply:(_Bool)arg4 inReplyToUsername:(id)arg5 entities:(id)arg6 hasAttachment:(_Bool)arg7 hitHighlights:(id)arg8 textRangeSet:(id)arg9 primaryMediaInfo:(id)arg10 geotag:(id)arg11 trailingEntityURL:(id)arg12 displayTextOffset:(unsigned long long)arg13 cardData:(id)arg14 quotedStatusPermalinkEntity:(id)arg15;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) Class superclass;

@end

