//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <T1Twitter/TFSPlistSerialization-Protocol.h>

@class NSMutableDictionary, NSString, TFNTwitterDisplayTextModelConfiguration, TFNTwitterStatusDisplayTextCache;

@interface TFNTwitterDisplayTextModel : NSObject <TFSPlistSerialization>
{
    TFNTwitterDisplayTextModelConfiguration *_configuration;
    TFNTwitterStatusDisplayTextCache *_defaultDisplayTextCache;
    NSMutableDictionary *_displayTextCacheDictionary;
    unsigned long long _bidiAdjustedDisplayTextOffset;
}

+ (long long)_displayTextHeightCacheSeedWithFontSize:(double)arg1 width:(unsigned long long)arg2;
+ (struct _NSRange)_wrappedRangeOfDirectionMarksWithText:(id)arg1 range:(struct _NSRange)arg2;
@property(nonatomic) unsigned long long bidiAdjustedDisplayTextOffset; // @synthesize bidiAdjustedDisplayTextOffset=_bidiAdjustedDisplayTextOffset;
@property(retain, nonatomic) NSMutableDictionary *displayTextCacheDictionary; // @synthesize displayTextCacheDictionary=_displayTextCacheDictionary;
@property(retain, nonatomic) TFNTwitterStatusDisplayTextCache *defaultDisplayTextCache; // @synthesize defaultDisplayTextCache=_defaultDisplayTextCache;
@property(readonly, nonatomic) TFNTwitterDisplayTextModelConfiguration *configuration; // @synthesize configuration=_configuration;
- (void).cxx_destruct;
- (_Bool)isEqual:(id)arg1;
@property(readonly) unsigned long long hash;
- (id)plistDictionaryValue;
- (id)initWithPlistDictionary:(id)arg1;
- (id)_canonicalTextForRange:(struct _NSRange)arg1;
- (struct _NSRange)displayTextRange;
- (_Bool)isReply;
- (id)displayText;
- (id)text;
- (_Bool)_shouldBeRenderedFromRight;
- (void)_updateDisplayTextCache:(id)arg1 displayText:(id)arg2 displayTextRanges:(id)arg3 trailingURLEntity:(id)arg4;
- (void)_updateDisplayTextCache:(id)arg1 displayText:(id)arg2 displayTextRanges:(id)arg3 quotedStatusPermalinkEntity:(id)arg4;
- (id)_encodedDisplayText;
- (id)_displayTextCacheForOptions:(unsigned long long)arg1 createIfNeeded:(_Bool)arg2;
- (id)_displayTextCacheForOptions:(unsigned long long)arg1;
- (id)_displayTextForOptions:(unsigned long long)arg1;
- (id)_statusTagsForText:(id)arg1 options:(unsigned long long)arg2;
- (id)_attributedSuffixString:(id)arg1 withFont:(id)arg2 lineHeight:(double)arg3 linkTextColor:(id)arg4;
- (id)_tfn_attributedStringForOptions:(unsigned long long)arg1 withFont:(id)arg2 boldFont:(id)arg3 lineHeight:(double)arg4 darkBackground:(_Bool)arg5 defaultTextColor:(id)arg6 linkTextColor:(id)arg7 highlighted:(_Bool)arg8;
- (void)_prepareDisplayTextCacheWithPOITagsForOptions:(unsigned long long)arg1;
- (void)_prepareSimpleDisplayTextCacheWithLastOption:(unsigned long long)arg1 options:(unsigned long long)arg2;
- (void)_prepareHashflagsDisplayTextCacheForOptions:(unsigned long long)arg1;
- (void)_prepareStrippedLeadingMentionsDisplayTextCacheForOptions:(unsigned long long)arg1;
- (void)_prepareNoLinksDisplayTextCacheForOptions:(unsigned long long)arg1;
- (void)_prepareShortenedDisplayTextCacheForOptions:(unsigned long long)arg1;
- (void)_prepareQuotedStatusPermalinkDisplayTextCacheForOptions:(unsigned long long)arg1;
- (void)_tfn_prepareBaseDisplayTextCache;
- (void)_prepareDisplayTextCacheForOptions:(unsigned long long)arg1;
- (id)_geotag;
- (id)_primaryMediaInfo;
- (id)_textRangeSet;
- (id)_hitHighlights;
- (unsigned long long)_displayTextOffset;
- (id)_entities;
- (id)_inReplyToUserName;
- (id)_fromUserName;
- (long long)_authenticatedUserID;
- (id)_text;
- (id)attributedTextModelForOptions:(unsigned long long)arg1 withFont:(id)arg2 boldFont:(id)arg3 lineHeight:(double)arg4 darkBackground:(_Bool)arg5 defaultTextColor:(id)arg6 linkTextColor:(id)arg7 highlighted:(_Bool)arg8 truncationString:(id)arg9 cachingEnabled:(_Bool)arg10;
- (long long)attributedDisplayTextHeightForOptions:(unsigned long long)arg1 withWidth:(double)arg2 font:(id)arg3 boldFont:(id)arg4 lineHeight:(double)arg5 darkBackground:(_Bool)arg6 defaultTextColor:(id)arg7 linkTextColor:(id)arg8 truncationString:(id)arg9 cachingEnabled:(_Bool)arg10 isTextTruncated:(out _Bool *)arg11;
- (id)displayTextPlaceRangesForOptions:(unsigned long long)arg1;
- (_Bool)displayTextMayHaveUndetectedHashflagsForOptions:(unsigned long long)arg1;
- (id)displayTextHashflagsForOptions:(unsigned long long)arg1;
- (id)displayTextURLRangesForOptions:(unsigned long long)arg1;
- (id)displayTextRangesForOptions:(unsigned long long)arg1;
- (id)displayTextForOptions:(unsigned long long)arg1;
- (id)accessibilityTextForOptions:(unsigned long long)arg1;
- (void)setConfiguration:(id)arg1;
- (id)initWithConfiguration:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) Class superclass;

@end

