//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface TFNTwitterRichTimelineParser : NSObject
{
}

- (id)_parseTweetEntryWithResponse:(id)arg1 jsonEntry:(id)arg2;
- (id)_parseMessageEntryWithJsonEntry:(id)arg1;
- (id)_parseConversationEntryWithResponse:(id)arg1 account:(id)arg2 jsonEntry:(id)arg3;
- (id)richTimelineChunkWithTimelineResponse:(id)arg1 account:(id)arg2;
- (void)parseTimelineObjectsFromDictionary:(id)arg1 account:(id)arg2 completion:(CDUnknownBlockType)arg3;

@end

