//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <T1Twitter/TFNUIConfiguration-Protocol.h>

@class NSString;
@protocol TFNFontGroup;

@interface TFNTwitterUIConfiguration : NSObject <TFNUIConfiguration>
{
    _Bool _isSmartInvertColorsEnabled;
    _Bool _isNestedActionButtonEnabled;
    _Bool _isLargeScreenLayoutSpecializationEnabled;
    _Bool _isLevelAAColorsEnabled;
    long long _engagementAnimationType;
}

@property(nonatomic) _Bool isLevelAAColorsEnabled; // @synthesize isLevelAAColorsEnabled=_isLevelAAColorsEnabled;
@property(readonly, nonatomic) _Bool isLargeScreenLayoutSpecializationEnabled; // @synthesize isLargeScreenLayoutSpecializationEnabled=_isLargeScreenLayoutSpecializationEnabled;
@property(readonly, nonatomic) _Bool isNestedActionButtonEnabled; // @synthesize isNestedActionButtonEnabled=_isNestedActionButtonEnabled;
@property(readonly, nonatomic) _Bool isSmartInvertColorsEnabled; // @synthesize isSmartInvertColorsEnabled=_isSmartInvertColorsEnabled;
@property(readonly, nonatomic) _Bool isReduceMotionSettingEnabled;
- (void)_tfn_updateFeatureSwitchValues;
@property(readonly, nonatomic) id <TFNFontGroup> fontGroup;
@property(readonly, nonatomic) long long engagementAnimationType; // @synthesize engagementAnimationType=_engagementAnimationType;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

