//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, TSPContext;
@protocol OS_dispatch_queue;

@interface TSPSession : NSObject
{
    _Bool _contextQueue_hasLoadedContext;
    NSString *_identifier;
    NSObject<OS_dispatch_queue> *_contextQueue;
    TSPContext *_contextQueue_context;
}

+ (void)private_performWithSessionRegistryAccess:(CDUnknownBlockType)arg1;
+ (_Bool)destroySessionWithIdentifier:(id)arg1 error:(out id *)arg2;
+ (id)sessionWithIdentifier:(id)arg1;
+ (void)discardSessions;
+ (id)testSessionWithIdentifier:(id)arg1;
@property(nonatomic) _Bool contextQueue_hasLoadedContext; // @synthesize contextQueue_hasLoadedContext=_contextQueue_hasLoadedContext;
@property(retain, nonatomic) TSPContext *contextQueue_context; // @synthesize contextQueue_context=_contextQueue_context;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *contextQueue; // @synthesize contextQueue=_contextQueue;
@property(readonly, copy, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
- (void).cxx_destruct;
- (id)contextQueue_loadContext;
- (void)private_asyncWithContext:(CDUnknownBlockType)arg1;
- (void)processPreKeyBundle:(id)arg1 forAddress:(id)arg2 completionQueue:(id)arg3 completionBlock:(CDUnknownBlockType)arg4;
- (void)checkSessionExistsForAddress:(id)arg1 completionQueue:(id)arg2 completionBlock:(CDUnknownBlockType)arg3;
- (void)deleteAllMessagesAndKeysWithCompletionQueue:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (void)deleteMessagesWithConversationID:(id)arg1 completionQueue:(id)arg2 completionBlock:(CDUnknownBlockType)arg3;
- (void)deleteMessageWithMessageID:(long long)arg1 conversationID:(id)arg2 completionQueue:(id)arg3 completionBlock:(CDUnknownBlockType)arg4;
- (void)storeMessage:(id)arg1 withMessageID:(long long)arg2 conversationID:(id)arg3 completionQueue:(id)arg4 completionBlock:(CDUnknownBlockType)arg5;
- (void)decrypt:(id)arg1 withMessageID:(long long)arg2 from:(id)arg3 completionQueue:(id)arg4 completionBlock:(CDUnknownBlockType)arg5;
- (void)encrypt:(id)arg1 for:(id)arg2 completionQueue:(id)arg3 completionBlock:(CDUnknownBlockType)arg4;
- (void)commitPreKeys:(id)arg1 completionQueue:(id)arg2 completionBlock:(CDUnknownBlockType)arg3;
- (void)generatePreKeysWithCount:(unsigned long long)arg1 completionQueue:(id)arg2 completionBlock:(CDUnknownBlockType)arg3;
- (void)commitSignedPreKey:(id)arg1 completionQueue:(id)arg2 completionBlock:(CDUnknownBlockType)arg3;
- (void)generateSignedPreKeyWithCompletionQueue:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (void)loadFingerprintForConversationID:(id)arg1 localStableIdentifier:(id)arg2 recipientStableIdentifier:(id)arg3 recipientDeviceID:(id)arg4 recipientIdentityKey:(id)arg5 completionQueue:(id)arg6 completionBlock:(CDUnknownBlockType)arg7;
- (void)storeDeviceID:(id)arg1 identityKey:(id)arg2 forConversationID:(id)arg3 asTrustedIdentity:(_Bool)arg4 completionQueue:(id)arg5 completionBlock:(CDUnknownBlockType)arg6;
- (void)loadTrustedIdentityForConversationID:(id)arg1 completionQueue:(id)arg2 completionBlock:(CDUnknownBlockType)arg3;
- (void)loadRegistrationDataWithCompletionQueue:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (void)invalidate;
- (id)init;
- (id)initWithIdentifier:(id)arg1 context:(id)arg2 enforceUniqueness:(_Bool)arg3;
- (id)initWithIdentifier:(id)arg1;

@end

