//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@interface UIViewController (TFNTwitterStatusActionItems)
- (id)t1_showHiddenTweetsActionItemForStatus:(id)arg1 account:(id)arg2 scribeContext:(id)arg3;
- (id)t1_unhideTweetActionItemForStatus:(id)arg1 account:(id)arg2 scribeContext:(id)arg3;
- (id)t1_hideTweetActionItemForStatus:(id)arg1 account:(id)arg2 scribeContext:(id)arg3;
- (id)t1_reportTweetActionItemForStatus:(id)arg1 account:(id)arg2 scribeContext:(id)arg3;
- (id)t1_deleteTweetActionItemForStatus:(id)arg1 account:(id)arg2 isInlineSource:(_Bool)arg3 scribeContext:(id)arg4;
- (id)t1_muteConversationActionItemForStatus:(id)arg1 account:(id)arg2 scribeContext:(id)arg3;
- (id)t1_taggingRemoveMeActionItemForStatus:(id)arg1 account:(id)arg2;
- (id)t1_sendViaDirectMessageActionItemForStatus:(id)arg1 account:(id)arg2 title:(id)arg3 source:(id)arg4 scribeContext:(id)arg5;
- (id)t1_shareWithRecentDMConversationActionItemForStatus:(id)arg1 account:(id)arg2 conversation:(id)arg3 source:(id)arg4 scribeContext:(id)arg5;
- (id)t1_bookmarksActionItemForStatus:(id)arg1 account:(id)arg2 shouldReplaceAddWithRemoveBookmark:(_Bool)arg3 scribeContext:(id)arg4;
@end

