//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@interface UIViewController (T1HiddenReplies)
- (void)_t1_hideStatus:(id)arg1 fromAccount:(id)arg2;
- (void)_t1_displayMessage:(id)arg1 errorMessage:(id)arg2 success:(_Bool)arg3;
- (void)hiddenRepliesEducationTakeoverViewControllerDidTapCancel:(id)arg1;
- (void)hiddenRepliesEducationTakeoverViewController:(id)arg1 didTapHideReply:(id)arg2;
- (void)showHiddenRepliesConsumptionEducationWithAccount:(id)arg1;
- (void)showHiddenRepliesForStatus:(id)arg1 account:(id)arg2 fromViewController:(id)arg3 scribeContext:(id)arg4;
- (void)unhideStatus:(id)arg1 account:(id)arg2 scribeContext:(id)arg3;
- (void)hideStatus:(id)arg1 account:(id)arg2 scribeContext:(id)arg3;
@end

