//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@interface UIViewController (T1Scribe)
- (id)scribeImpressionCache;
- (id)scribeAssociations;
- (id)scribeElementForIndexPath:(id)arg1;
- (id)scribeElement;
- (id)scribeComponentForIndexPath:(id)arg1;
- (id)scribeComponent;
- (id)scribeSectionForIndexPath:(id)arg1;
- (id)scribeSection;
- (id)scribePage;
- (id)scribeSourceContext;
- (id)scribeContextForIndexPath:(id)arg1;
- (id)scribeContext;
- (unsigned long long)minImpressionDuration;
- (id)scribeImpressionParametersForIndexPath:(id)arg1;
- (id)scribeItemForIndexPath:(id)arg1;
- (id)scribeImpressionParameters;
- (id)scribeParameters;
- (id)scribe;
- (void)scribeViewImpressionWithParameters:(id)arg1;
@end

