//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@interface UIViewController (TFNLayoutGuides)
- (id)_tfn_layoutGuidesState;
- (void)setLayoutGuidesSource:(id)arg1;
- (id)layoutGuidesSource;
- (void)sendLayoutGuidesDidChange:(long long)arg1;
- (double)lengthOfLayoutGuide:(long long)arg1 forEnvironment:(id)arg2;
- (double)_tfn_defaultLengthForLayoutGuide:(long long)arg1;
- (double)_tfn_lengthForLayoutGuide:(long long)arg1;
- (id)_tfn_layoutSupportForLayoutGuide:(long long)arg1;
- (double)systemSafeAreaInsetForLayoutGuide:(long long)arg1;
- (void)layoutGuidesDidChange:(long long)arg1;
- (id)bottomVisibleLayoutGuide;
- (id)topVisibleLayoutGuide;
- (id)bottomFixedLayoutGuide;
- (id)topFixedLayoutGuide;
@end

