//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@interface UIViewController (TFNTwitterStatusConversationContext)
+ (id)t1_controllerToPresentForConversationContext:(id)arg1 hostViewController:(id)arg2 sourceView:(id)arg3 sourceRect:(struct CGRect)arg4 profileHeaderButtonGroup:(long long)arg5 account:(id)arg6 previewing:(_Bool)arg7;
- (void)t1_presentControllerForConversationContext:(id)arg1 sourceView:(id)arg2 sourceRect:(struct CGRect)arg3 profileHeaderButtonGroup:(long long)arg4 account:(id)arg5 sourceScribeContext:(id)arg6;
@end

