//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import <T1Twitter/T1ListsOwnerDelegate-Protocol.h>

@class NSString;

@interface UIViewController (T1ListsOwnerDelegate) <T1ListsOwnerDelegate>
- (void)listsFollowsViewControllerDidCancel:(id)arg1;
- (void)listsFollowsViewController:(id)arg1 didAddToLists:(id)arg2 andRemovedFromLists:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@end

