//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

__attribute__((visibility("hidden")))
@interface _TtC9T1Twitter34SingleAutoplayableManagerDebugView : UIView
{
    // Error parsing type: , name: insetBoundsView.storage
    // Error parsing type: , name: targetXView.storage
    // Error parsing type: , name: targetYView.storage
    // Error parsing type: , name: autoplayableFrameViews.storage
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

