//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@interface _TtC9T1Twitter25URTRelatedArticlesContext : _TtCs12_SwiftObject
{
    // Error parsing type: , name: startDate
    // Error parsing type: , name: articleInjectionHandler
    // Error parsing type: , name: lastResignedActiveAt
    // Error parsing type: , name: totalTimeSpentInactive
    // Error parsing type: , name: minimumWebContentLingerTimeSeconds
}

- (void)didReceiveAppDidBecomeActiveWithNotification:(id)arg1;
- (void)didReceiveAppDidResignActiveWithNotification:(id)arg1;

@end

