//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <T1Twitter/T1CardView.h>

@class TIPImagePipeline;

__attribute__((visibility("hidden")))
@interface _TtC9T1Twitter22GuideLiveEventCardView : T1CardView
{
    // Error parsing type: , name: viewModel
    // Error parsing type: , name: bodyStackView
    // Error parsing type: , name: textVerticalStackView
    // Error parsing type: , name: headerView
    // Error parsing type: , name: titleLabel
    // Error parsing type: , name: thumbnailImageView.storage
    // Error parsing type: , name: highlightView.storage
    // Error parsing type: , name: thumbnailSize
}

- (void).cxx_destruct;
- (id)previewingViewControllerForLocation:(struct CGPoint)arg1 outSourceRect:(struct CGRect *)arg2;
- (void)didTapHighlightViewWithSender:(id)arg1;
- (void)fetchImages;
- (id)imageFetchingViews;
- (void)cardContextDidUpdate;
- (void)prepareForReuse;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic, retain) TIPImagePipeline *imagePipeline;

@end

