//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <T1Twitter/TFNTwitterSuggestModuleWhoToFollowBlender-Protocol.h>

@interface _TtC9T1TwitterP33_E169501C817ABC3EF830DA8FB687545735URTWhoToFollowSuggestsModuleBlender : NSObject <TFNTwitterSuggestModuleWhoToFollowBlender>
{
    // Error parsing type: , name: urtWhoToFollowBlender
}

- (void).cxx_destruct;
- (id)init;
- (void)reactToFollowingUser:(id)arg1 inSuggestsModule:(id)arg2;

@end

