//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <T1Twitter/_TtC9T1Twitter22URTMomentCoverCardView.h>

@interface _TtC9T1Twitter22URTMomentCoverCardView (T1Twitter2)
- (void)sportEventsDataManager:(id)arg1 didUpdateEvent:(id)arg2;
@end

