//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <T1Twitter/TFNFormViewController.h>

@class NSString, T1AddPhoneNumberForm, T1PhoneNumberFormatter, T1SignUpFormFooterView, T1VerifyPhoneNumberDelegate, TFNTwitterAccount, UITextField;
@protocol T1AddPhoneNumberDelegate;

@interface T1AddPhoneNumberViewController : TFNFormViewController
{
    _Bool _useCancelAndFinishActions;
    _Bool _implicitSMSOptInAllowed;
    T1SignUpFormFooterView *_legalFooterView;
    TFNTwitterAccount *_account;
    id <T1AddPhoneNumberDelegate> _delegate;
    NSString *_scribePage;
    NSString *_suppressRestartToken;
    UITextField *_hiddenTextField;
    T1PhoneNumberFormatter *_phoneNumberFormatter;
    unsigned long long _mode;
    NSString *_suppliedPhoneNumber;
    T1VerifyPhoneNumberDelegate *_phoneNumberDelegate;
}

+ (void)registerPhoneNumber:(id)arg1 account:(id)arg2 disableNotification:(_Bool)arg3 updatePhone:(_Bool)arg4 completion:(CDUnknownBlockType)arg5;
@property(retain, nonatomic) T1VerifyPhoneNumberDelegate *phoneNumberDelegate; // @synthesize phoneNumberDelegate=_phoneNumberDelegate;
@property(copy, nonatomic) NSString *suppliedPhoneNumber; // @synthesize suppliedPhoneNumber=_suppliedPhoneNumber;
@property(readonly, nonatomic) unsigned long long mode; // @synthesize mode=_mode;
@property(readonly, nonatomic) T1PhoneNumberFormatter *phoneNumberFormatter; // @synthesize phoneNumberFormatter=_phoneNumberFormatter;
@property(retain, nonatomic) UITextField *hiddenTextField; // @synthesize hiddenTextField=_hiddenTextField;
@property(copy, nonatomic) NSString *suppressRestartToken; // @synthesize suppressRestartToken=_suppressRestartToken;
@property(copy, nonatomic) NSString *scribePage; // @synthesize scribePage=_scribePage;
@property(nonatomic) _Bool implicitSMSOptInAllowed; // @synthesize implicitSMSOptInAllowed=_implicitSMSOptInAllowed;
@property(nonatomic) _Bool useCancelAndFinishActions; // @synthesize useCancelAndFinishActions=_useCancelAndFinishActions;
@property(nonatomic) __weak id <T1AddPhoneNumberDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) TFNTwitterAccount *account; // @synthesize account=_account;
- (void).cxx_destruct;
- (void)tfn_keyboardDismissModalAction;
- (_Bool)tfn_canKeyboardDismissModal;
- (void)_handleSmsError:(id)arg1;
- (void)_continueVerificationForDeviceRegistration:(id)arg1;
- (void)_skipTapped;
- (void)_discoverabilityOptionsTapped;
- (void)_addPhoneTapped;
- (unsigned long long)inputRequiredBehavior;
- (void)submitForm;
- (id)footerItems;
- (struct CGRect)additionalGutterFrame;
- (id)toolbarItems;
- (id)doneBarButtonItem;
- (_Bool)addsDoneBarButtonButtonItemToNavigationBar;
- (_Bool)includesSubmitButtonAsItem;
@property(readonly, nonatomic) T1SignUpFormFooterView *legalFooterView; // @synthesize legalFooterView=_legalFooterView;
@property(retain, nonatomic) NSString *headerMessage;
- (void)setCurrentPhoneNumber:(id)arg1;
@property(readonly, nonatomic) T1AddPhoneNumberForm *addPhoneNumberForm;
- (void)viewDidLayoutSubviews;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithForm:(id)arg1 appearance:(id)arg2;
- (id)initWithAccount:(id)arg1 mode:(unsigned long long)arg2;
- (id)initWithAccount:(id)arg1 phoneNumber:(id)arg2;
- (id)initWithAccount:(id)arg1;

@end

