//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <TFNUI/TFNViewController.h>

#import <T1Twitter/T1PickAndFilterPhotoFlowControllerDelegate-Protocol.h>
#import <T1Twitter/T1UserProfileExampleViewDelegate-Protocol.h>

@class NSString, T1OnboardingHeaderView, T1PickAndFilterPhotoFlowController, T1UserProfileExampleView, TFNTwitterAccount, UIImage;
@protocol T1AddBannerViewControllerDelegate;

@interface T1AddBannerViewController : TFNViewController <T1PickAndFilterPhotoFlowControllerDelegate, T1UserProfileExampleViewDelegate>
{
    _Bool _animateAvatar;
    _Bool _requireBanner;
    _Bool _showCurrentBanner;
    NSString *_title;
    NSString *_subtitle;
    NSString *_nextLabel;
    NSString *_skipLabel;
    _Bool _navigationPushTransition;
    TFNTwitterAccount *_account;
    T1OnboardingHeaderView *_headerView;
    T1UserProfileExampleView *_userProfileView;
    T1PickAndFilterPhotoFlowController *_photoPicker;
    UIImage *_avatarImage;
    UIImage *_bannerImage;
    id <T1AddBannerViewControllerDelegate> _delegate;
}

@property(readonly, nonatomic) __weak id <T1AddBannerViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) _Bool navigationPushTransition; // @synthesize navigationPushTransition=_navigationPushTransition;
@property(retain, nonatomic) UIImage *bannerImage; // @synthesize bannerImage=_bannerImage;
@property(retain, nonatomic) UIImage *avatarImage; // @synthesize avatarImage=_avatarImage;
@property(retain, nonatomic) T1PickAndFilterPhotoFlowController *photoPicker; // @synthesize photoPicker=_photoPicker;
@property(readonly, nonatomic) T1UserProfileExampleView *userProfileView; // @synthesize userProfileView=_userProfileView;
@property(readonly, nonatomic) T1OnboardingHeaderView *headerView; // @synthesize headerView=_headerView;
@property(readonly, nonatomic) TFNTwitterAccount *account; // @synthesize account=_account;
- (void).cxx_destruct;
- (void)private_updateContinueButton;
- (void)scribeAction:(id)arg1 inComponent:(id)arg2 parameters:(id)arg3;
- (id)scribeSection;
- (id)scribePage;
- (void)pickAndFilterPhotoFlowController:(id)arg1 removePhotoType:(long long)arg2;
- (void)pickAndFilterPhotoFlowController:(id)arg1 userDidCancelPhotoType:(long long)arg2;
- (void)pickAndFilterPhotoFlowController:(id)arg1 userDidSelectImage:(id)arg2 type:(long long)arg3;
- (void)_selectPhotoFromView:(id)arg1;
- (void)_nextTapped;
- (void)_skipTapped;
- (void)didTapChangeBanner:(id)arg1;
- (id)navigationControllerTransitionForOperation:(long long)arg1 fromViewController:(id)arg2 toViewController:(id)arg3;
- (_Bool)tfn_logoTitleViewShown;
- (_Bool)tfn_prefersNavigationBarShadowHidden;
- (long long)tfn_preferredToolbarVisibility;
- (void)viewWillAppear:(_Bool)arg1;
- (void)_setupConstraints;
- (void)tfn_addDirectlyOwnedViewControllersToMutableArray:(id)arg1;
- (void)viewDidLoad;
- (id)initWithAccount:(id)arg1 title:(id)arg2 subtitle:(id)arg3 nextLabel:(id)arg4 skipLabel:(id)arg5 delegate:(id)arg6 requireBanner:(_Bool)arg7 showCurrentBanner:(_Bool)arg8 animateAvatar:(_Bool)arg9 forcedAvatarImage:(id)arg10;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

