//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <T1Twitter/TFNAdaptiveWizardStep.h>

#import <T1Twitter/T1AddLocationViewControllerDelegate-Protocol.h>

@interface T1AdaptiveWizardAddLocationStep : TFNAdaptiveWizardStep <T1AddLocationViewControllerDelegate>
{
}

- (void)addLocationViewControllerDidTapSkip:(id)arg1;
- (void)addLocationViewController:(id)arg1 didTapNextWithLocation:(id)arg2 placeID:(id)arg3;
- (void)evaluateWithController:(id)arg1;

@end

