//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <T1Twitter/TFNAdaptiveWizardStep.h>

#import <T1Twitter/T1AddBioViewControllerDelegate-Protocol.h>

@interface T1AdaptiveWizardAddBioStep : TFNAdaptiveWizardStep <T1AddBioViewControllerDelegate>
{
}

- (void)addBioViewControllerDidTapSkip:(id)arg1;
- (void)addBioViewController:(id)arg1 didTapNextWithText:(id)arg2;
- (void)evaluateWithController:(id)arg1;

@end

