//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <TFNUI/TFNBarButtonItem.h>

@interface T1CameraRotatingBarButtonItem : TFNBarButtonItem
{
    long long _lockOrientation;
}

- (void)_updateOrientationAnimated:(_Bool)arg1;
- (void)_deviceOrientationDidChange:(id)arg1;
- (void)unlockOrientation;
- (void)lockOrientation:(long long)arg1;
- (void)setEnabled:(_Bool)arg1 animated:(_Bool)arg2;
- (void)setEnabled:(_Bool)arg1;
- (void)dealloc;
- (id)init;

@end

