//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSString, T1AvatarImageView, TFNTwitterUser, UIImageView;

@interface T1ConversationConnectorView : UIView
{
    long long _terminals;
    TFNTwitterUser *_user;
    NSString *_accountID;
    UIImageView *_imageView;
    T1AvatarImageView *_avatarImageView;
}

+ (double)connectorAvatarBottomPadding;
+ (double)connectorAvatarHeightForLayoutMetrics:(id)arg1;
+ (id)_t1_conversationConnectorImage;
+ (id)_t1_conversationConnectorImageWithEllipsis;
+ (id)conversationConnectorViewWithAvatarForUser:(id)arg1 accountID:(id)arg2;
+ (id)conversationConnectorViewWithTerminals:(long long)arg1;
+ (id)conversationConnectorView;
@property(retain, nonatomic) T1AvatarImageView *avatarImageView; // @synthesize avatarImageView=_avatarImageView;
@property(readonly, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
@property(copy, nonatomic) NSString *accountID; // @synthesize accountID=_accountID;
@property(retain, nonatomic) TFNTwitterUser *user; // @synthesize user=_user;
@property(nonatomic) long long terminals; // @synthesize terminals=_terminals;
- (void).cxx_destruct;
- (void)_t1_initializeAvatarView;
- (struct CGSize)intrinsicContentSize;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1 forUser:(id)arg2 accountID:(id)arg3;
- (id)initWithFrame:(struct CGRect)arg1 terminals:(long long)arg2;

@end

