//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <TFNUI/TFNViewController.h>

@class TFNTwitterAccount;

@interface T1ConversationContainerViewController : TFNViewController
{
    TFNTwitterAccount *_account;
    long long _statusID;
}

@property(nonatomic) long long statusID; // @synthesize statusID=_statusID;
@property(retain, nonatomic) TFNTwitterAccount *account; // @synthesize account=_account;
- (void).cxx_destruct;
- (void)viewDidLoad;
- (id)initWithAccount:(id)arg1 statusID:(long long)arg2;

@end

