//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <TFNUI/TFNViewController.h>

#import <T1Twitter/T1MediaChooserCustomEditor-Protocol.h>

@class NSString, T1PhotoEditView, UIImage, UIToolbar, UIView;
@protocol T1MediaChooserCustomEditorDelegate;

@interface T1CustomPhotoEditViewController : TFNViewController <T1MediaChooserCustomEditor>
{
    T1PhotoEditView *_editView;
    UIImage *_originalImage;
    id <T1MediaChooserCustomEditorDelegate> _delegate;
    unsigned long long _purpose;
    UIView *_customToolbarWrapper;
    UIToolbar *_customToolbar;
    double _aspectRatio;
    NSString *_saveButtonText;
}

@property(readonly, nonatomic) NSString *saveButtonText; // @synthesize saveButtonText=_saveButtonText;
@property(nonatomic) double aspectRatio; // @synthesize aspectRatio=_aspectRatio;
@property(retain, nonatomic) UIToolbar *customToolbar; // @synthesize customToolbar=_customToolbar;
@property(retain, nonatomic) UIView *customToolbarWrapper; // @synthesize customToolbarWrapper=_customToolbarWrapper;
@property(readonly, nonatomic) unsigned long long purpose; // @synthesize purpose=_purpose;
@property(nonatomic) __weak id <T1MediaChooserCustomEditorDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) UIImage *originalImage; // @synthesize originalImage=_originalImage;
- (void).cxx_destruct;
- (void)_updateEditView;
- (void)imageToEdit:(id)arg1;
- (struct CGSize)_previewCropSize;
- (void)cancel;
- (void)save;
- (struct CGSize)preferredContentSize;
- (unsigned long long)supportedInterfaceOrientations;
- (_Bool)prefersStatusBarHidden;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)initWithAspectRatio:(double)arg1 purpose:(unsigned long long)arg2 saveButtonText:(id)arg3;
- (id)initWithAspectRatio:(double)arg1 purpose:(unsigned long long)arg2;
- (id)initWithCoder:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

