//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <T1Twitter/NSObject-Protocol.h>

@class T1DashNewsCameraViewController, T1DashSplitViewController, T1DashViewController, UITouch, UIViewController;

@protocol T1DashSplitViewControllerDelegate <NSObject>

@optional
- (_Bool)dashSplitViewController:(T1DashSplitViewController *)arg1 shouldReceiveTouch:(UITouch *)arg2;
- (_Bool)dashSplitViewController:(T1DashSplitViewController *)arg1 canDismissNewsCameraViewController:(T1DashNewsCameraViewController *)arg2;
- (_Bool)dashSplitViewController:(T1DashSplitViewController *)arg1 canPresentNewsCameraFromViewController:(UIViewController *)arg2;
- (_Bool)dashSplitViewController:(T1DashSplitViewController *)arg1 canDismissDashViewController:(T1DashViewController *)arg2;
- (_Bool)dashSplitViewController:(T1DashSplitViewController *)arg1 canPresentDashFromViewController:(UIViewController *)arg2;
- (UIViewController *)contentPresentingViewControllerForDashSplitViewController:(T1DashSplitViewController *)arg1;
- (UIViewController *)dashPresentingViewControllerForDashSplitViewController:(T1DashSplitViewController *)arg1;
- (void)dashSplitViewControllerDashOpenPercentDidChange:(T1DashSplitViewController *)arg1;
- (void)dashSplitViewControllerSplitModeDidChange:(T1DashSplitViewController *)arg1;
@end

