//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <T1Twitter/T1DirectMessageAbstractConversationEntryCell.h>

@class CALayer, T1DirectMessageConversationLastReadMarkerEntryViewModel, TFNAttributedTextView;

@interface T1DirectMessageConversationLastReadMarkerEntryCell : T1DirectMessageAbstractConversationEntryCell
{
    TFNAttributedTextView *_textLabel;
    CALayer *_leftDividerLine;
    CALayer *_rightDividerLine;
}

@property(readonly, nonatomic) CALayer *rightDividerLine; // @synthesize rightDividerLine=_rightDividerLine;
@property(readonly, nonatomic) CALayer *leftDividerLine; // @synthesize leftDividerLine=_leftDividerLine;
@property(readonly, nonatomic) TFNAttributedTextView *textLabel; // @synthesize textLabel=_textLabel;
- (void).cxx_destruct;
- (struct CGRect)_frameForDividerLineWithOriginX:(double)arg1;
- (void)layoutSubviews;
- (void)setEntryViewModel:(id)arg1;
@property(readonly, nonatomic) T1DirectMessageConversationLastReadMarkerEntryViewModel *lastReadMarkerEntryViewModel;
- (id)initWithFrame:(struct CGRect)arg1;

@end

