//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <T1Twitter/T1DefaultUserViewLayoutDelegate.h>

@interface T1LargeProfileCardUserViewLayoutDelegate : T1DefaultUserViewLayoutDelegate
{
}

+ (double)userNameToBioGap;
+ (id)sharedLayoutDelegate;
- (id)layoutStateForUserView:(id)arg1;
- (struct CGRect)layoutAvatarWithLayoutMetrics:(id)arg1 userView:(id)arg2;
- (id)adjustedLayoutMetricsForLayoutMetrics:(id)arg1;
- (struct CGRect)layoutActionControlWithContentRect:(struct CGRect)arg1 layoutState:(id)arg2 userView:(id)arg3;
- (double)_additionalTopInsetForLayoutMetrics:(id)arg1;

@end

