//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <TFNUI/TFNTappableHighlightView.h>

@class UIImageView, UILabel, UIView;

@interface T1ModuleFooterView : TFNTappableHighlightView
{
    UILabel *_titleLabel;
    UIImageView *_imageView;
    UIView *_topSeparator;
    UIView *_bottomSeparator;
}

+ (double)height;
@property(readonly, nonatomic) UIView *bottomSeparator; // @synthesize bottomSeparator=_bottomSeparator;
@property(readonly, nonatomic) UIView *topSeparator; // @synthesize topSeparator=_topSeparator;
@property(readonly, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
@property(readonly, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

