//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <T1Twitter/NSObject-Protocol.h>

@class T1NewsCameraCapsuleViewController, T1NewsCameraCarouselView, UIViewController;

@protocol T1NewsCameraCarouselViewDataSource <NSObject>
- (UIViewController *)parentViewControllerForCarouselView:(T1NewsCameraCarouselView *)arg1;
- (long long)carouselView:(T1NewsCameraCarouselView *)arg1 indexForViewController:(T1NewsCameraCapsuleViewController *)arg2;
- (T1NewsCameraCapsuleViewController *)carouselView:(T1NewsCameraCarouselView *)arg1 viewControllerAfterViewController:(T1NewsCameraCapsuleViewController *)arg2;
- (T1NewsCameraCapsuleViewController *)carouselView:(T1NewsCameraCarouselView *)arg1 viewControllerBeforeViewController:(T1NewsCameraCapsuleViewController *)arg2;
@end

