//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class TFNTwitterAccount, TFNTwitterNewsCameraThread;
@protocol T1NewsCameraThreadObserverDelegate;

@interface T1NewsCameraThreadObserver : NSObject
{
    _Bool _disabled;
    id <T1NewsCameraThreadObserverDelegate> _delegate;
    TFNTwitterAccount *_account;
    TFNTwitterNewsCameraThread *_latestThread;
}

@property(retain, nonatomic) TFNTwitterNewsCameraThread *latestThread; // @synthesize latestThread=_latestThread;
@property(nonatomic, getter=isDisabled) _Bool disabled; // @synthesize disabled=_disabled;
@property(readonly, nonatomic) TFNTwitterAccount *account; // @synthesize account=_account;
@property(nonatomic) __weak id <T1NewsCameraThreadObserverDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)_t1_main_updateLatestThread;
- (void)_t1_notification_newsCameraMomentsDidChange:(id)arg1;
- (id)initWithAccount:(id)arg1;
- (id)init;

@end

