//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <T1Twitter/T1TombstoneContainerItem-Protocol.h>

@class NSString, TFSURTRichText;

@interface T1NonPolicyCompliantTweetInterstitialItem : NSObject <T1TombstoneContainerItem>
{
    TFSURTRichText *_tombstoneText;
}

@property(readonly, nonatomic) TFSURTRichText *tombstoneText; // @synthesize tombstoneText=_tombstoneText;
- (void).cxx_destruct;
- (id)initWithTombstoneText:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

