//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <T1Twitter/T1OnboardingSubtaskController.h>

#import <T1Twitter/T1DiscoverabilityOptionsProvider-Protocol.h>

@class NSString, T1DiscoverabilityOptionsViewController, TFNOnboardingPrivacyOptionsSubtask, TFNOnboardingPrivacyOptionsSubtaskState, TFNOnboardingRichText;
@protocol T1OnboardingSubtaskControllerDelegate;

@interface T1OnboardingPrivacyOptionsSubtaskController : T1OnboardingSubtaskController <T1DiscoverabilityOptionsProvider>
{
    TFNOnboardingPrivacyOptionsSubtask *_subtask;
    TFNOnboardingPrivacyOptionsSubtaskState *_state;
    id <T1OnboardingSubtaskControllerDelegate> _delegate;
    T1DiscoverabilityOptionsViewController *_viewController;
    TFNOnboardingRichText *_expandedDiscoverableByEmailDetailText;
    TFNOnboardingRichText *_expandedDiscoverableByPhoneDetailText;
}

- (void).cxx_destruct;
- (id)private_settingsDescriptionItemCallsToActionForEntities:(id)arg1;
- (id)discoverableByPhoneDescriptionCallsToAction;
- (id)discoverableByPhoneDescriptionText;
- (id)discoverableByEmailDescriptionCallsToAction;
- (id)discoverableByEmailDescriptionText;
- (id)discoverableByPhoneLabel;
- (id)discoverableByEmailLabel;
- (id)discoverabilitySectionLabel;
- (id)discoverabilityOptionsTitle;
- (void)setDiscoverableByPhone:(_Bool)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (void)setDiscoverableByEmail:(_Bool)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (_Bool)discoverableByPhone;
- (_Bool)discoverableByEmail;
- (id)discoverabilityDoneButtonLabel;
- (CDUnknownBlockType)discoverabilityDoneButtonAction;
- (void)startWithNavigationContext:(id)arg1 navigationLink:(id)arg2;
- (id)initWithSubtask:(id)arg1 delegate:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

