//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface T1PhotoEditGuideView : UIView
{
    _Bool _useCircularCrop;
    struct CGSize _previewCropSize;
}

@property(nonatomic) _Bool useCircularCrop; // @synthesize useCircularCrop=_useCircularCrop;
@property(nonatomic) struct CGSize previewCropSize; // @synthesize previewCropSize=_previewCropSize;
- (void)drawRect:(struct CGRect)arg1;

@end

