//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary, NSMutableDictionary, NSString, UIView;
@protocol T1BasicStatusView;

@interface T1StatusViewEvent : NSObject
{
    NSString *_type;
    UIView<T1BasicStatusView> *_statusView;
    NSMutableDictionary *_innerState;
}

@property(retain, nonatomic) NSMutableDictionary *innerState; // @synthesize innerState=_innerState;
@property(readonly, nonatomic) UIView<T1BasicStatusView> *statusView; // @synthesize statusView=_statusView;
@property(readonly, nonatomic) NSString *type; // @synthesize type=_type;
- (void).cxx_destruct;
- (void)setStateValue:(id)arg1 forKey:(id)arg2;
@property(readonly, nonatomic) NSDictionary *state;
- (id)initWithEventType:(id)arg1 statusView:(id)arg2;

@end

