//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import <T1Twitter/TFNAttributedTextViewDelegate-Protocol.h>

@class NSString, TFNAttributedTextView, TFNButton, TFNSolidColorView, TFSTwitterEntitySet;
@protocol T1StatusViewModel, T1StatusWithheldInCountryViewDelegate;

@interface T1StatusWithheldInCountryView : UIView <TFNAttributedTextViewDelegate>
{
    _Bool _showsUndoButton;
    id <T1StatusViewModel> _viewModel;
    id <T1StatusWithheldInCountryViewDelegate> _delegate;
    TFNSolidColorView *_borderView;
    TFNSolidColorView *_backgroundView;
    TFNAttributedTextView *_textView;
    NSString *_displayText;
    TFSTwitterEntitySet *_entities;
    TFNButton *_undoButton;
}

+ (id)_t1_attributedTextModelForStatusViewModel:(id)arg1;
+ (struct UIEdgeInsets)_t1_innerContentInsetsForMetrics:(id)arg1;
+ (double)heightForStatusViewModel:(id)arg1 width:(double)arg2 layoutMetrics:(id)arg3 showsUndoButton:(_Bool)arg4;
@property(retain, nonatomic) TFNButton *undoButton; // @synthesize undoButton=_undoButton;
@property(retain, nonatomic) TFSTwitterEntitySet *entities; // @synthesize entities=_entities;
@property(retain, nonatomic) NSString *displayText; // @synthesize displayText=_displayText;
@property(retain, nonatomic) TFNAttributedTextView *textView; // @synthesize textView=_textView;
@property(retain, nonatomic) TFNSolidColorView *backgroundView; // @synthesize backgroundView=_backgroundView;
@property(retain, nonatomic) TFNSolidColorView *borderView; // @synthesize borderView=_borderView;
@property(nonatomic) __weak id <T1StatusWithheldInCountryViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) id <T1StatusViewModel> viewModel; // @synthesize viewModel=_viewModel;
@property(nonatomic) _Bool showsUndoButton; // @synthesize showsUndoButton=_showsUndoButton;
- (void).cxx_destruct;
- (id)_t1_currentViewController;
- (void)_t1_didTapUndoButton:(id)arg1;
- (void)attributedTextView:(id)arg1 didTapRange:(id)arg2 rect:(struct CGRect)arg3;
- (void)layoutSubviews;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

