//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <T1Twitter/NSObject-Protocol.h>
#import <T1Twitter/T1StatusViewModelCardAdditions-Protocol.h>
#import <T1Twitter/T1StatusViewModelExperimentAdditions-Protocol.h>
#import <T1Twitter/T1StatusViewModelPromotedLoggingAdditions-Protocol.h>
#import <T1Twitter/TFNTwitterCardDataSourceProvider-Protocol.h>
#import <T1Twitter/TFNTwitterDismissibleItem-Protocol.h>
#import <T1Twitter/TFSTwitterScribableItem-Protocol.h>

@class NSArray, NSDate, NSDictionary, NSString, TFNAttributedTextModel, TFNTwitterCampaignMetadata, TFNTwitterCardData, TFNTwitterFeedbackInfo, TFNTwitterGeotag, TFNTwitterMediaInfo, TFNTwitterStatus, TFNTwitterStatusConversationContext, TFSTwitterCameraMoment, TFSTwitterEntitySet, TFSURTRichText, UIColor, UIFont;
@protocol T1PlayerFactoryIdentifiable, T1StatusViewModel, TFNTwitterAVPlayerSessionSource;

@protocol T1StatusViewModel <NSObject, TFSTwitterScribableItem, TFNTwitterDismissibleItem, T1StatusViewModelExperimentAdditions, T1StatusViewModelCardAdditions, T1StatusViewModelPromotedLoggingAdditions, TFNTwitterCardDataSourceProvider>
@property(readonly, nonatomic) _Bool shouldOmitCardLink;
@property(readonly, nonatomic) _Bool shouldOmitCollectionLink;
@property(readonly, nonatomic) _Bool shouldShowCollectionCarousel;
@property(readonly, nonatomic, getter=isRecommendedByMagicRecs) _Bool recommendedByMagicRecs;
@property(readonly, nonatomic, getter=isFillerTweet) _Bool fillerTweet;
@property(readonly, nonatomic) long long draftTweetID;
@property(readonly, nonatomic, getter=isAdPreviewTweet) _Bool adPreviewTweet;
@property(readonly, nonatomic) NSString *designatorUrl;
@property(readonly, nonatomic) unsigned long long designatorLabelType;
@property(readonly, nonatomic) unsigned long long designatorIconType;
@property(readonly, nonatomic) NSString *designatorImageUrl;
@property(readonly, nonatomic) NSString *designatorString;
@property(readonly, nonatomic) double score;
@property(readonly, nonatomic) id <T1PlayerFactoryIdentifiable> playerFactoryIdentifiable;
@property(readonly, nonatomic) id <TFNTwitterAVPlayerSessionSource> playerSessionSource;
@property(readonly, nonatomic) _Bool isTweetedByAuthenticatedAccount;
@property(readonly, nonatomic) _Bool isFromUserUsernameless;
@property(readonly, nonatomic) _Bool isFromUserAffiliated;
@property(readonly, nonatomic) _Bool isFromUserVerified;
@property(readonly, nonatomic) _Bool isFromUserProtected;
@property(readonly, nonatomic) _Bool isIncompleteQuotedStatus;
@property(readonly, nonatomic) TFSURTRichText *outerTombstoneRichRevealText;
@property(readonly, nonatomic) TFSURTRichText *outerTombstoneRichText;
@property(readonly, nonatomic, getter=isOuterTombstoneDismissed) _Bool outerTombstoneDismissed;
@property(readonly, nonatomic) TFSURTRichText *innerTombstoneRichRevealText;
@property(readonly, nonatomic) TFSURTRichText *innerTombstoneRichText;
@property(readonly, nonatomic, getter=isInnerTombstoneDismissed) _Bool innerTombstoneDismissed;
@property(readonly, nonatomic) NSString *conversationSection;
@property(readonly, nonatomic) _Bool isConversationSingleBranchedReplyStatus;
@property(readonly, nonatomic) long long selfThreadID;
@property(readonly, nonatomic) _Bool isSelfThreadStatus;
@property(readonly, nonatomic, getter=displayAsSelfThreadTweet) _Bool selfThreadTweet;
@property(readonly, nonatomic) _Bool isConversationPrecededByAncestor;
@property(readonly, nonatomic) _Bool isConversationRoot;
@property(readonly, nonatomic) _Bool isConversationAncestor;
@property(readonly, nonatomic) _Bool isConversationStatus;
@property(readonly, nonatomic) TFNTwitterStatusConversationContext *conversationContext;
@property(readonly, nonatomic) __weak id <T1StatusViewModel> outerCollectionStatus;
@property(readonly, nonatomic) _Bool hasCollectionItems;
@property(readonly, nonatomic) NSArray *collectionCardDataItems;
@property(readonly, nonatomic) NSArray *collectionStatuses;
@property(readonly, nonatomic) NSString *collectionURL;
@property(readonly, nonatomic) long long collectionID;
@property(readonly, nonatomic) _Bool displayAsFavorited;
@property(readonly, nonatomic) _Bool displayAsRetweeted;
@property(readonly, nonatomic) NSDictionary *scribeParameters;
@property(readonly, nonatomic) NSString *scribeComponent;
@property(readonly, nonatomic) NSString *scribeElement;
@property(readonly, nonatomic) unsigned long long autoExpandMode;
@property(readonly, nonatomic) _Bool displayAsFollowForwardTweet;
@property(readonly, nonatomic) _Bool displayAsMomentTimelineTweet;
@property(readonly, nonatomic) _Bool displayAsMomentTweet;
@property(readonly, nonatomic) _Bool isRTBCreative;
@property(readonly, nonatomic) _Bool isIssueAd;
@property(readonly, nonatomic) _Bool isPoliticalAd;
@property(readonly, nonatomic) NSString *advertiserName;
@property(readonly, nonatomic) _Bool isPromoted;
@property(readonly, nonatomic) TFSTwitterCameraMoment *cameraMoment;
@property(readonly, nonatomic) NSString *composerSource;
@property(readonly, nonatomic) TFNTwitterGeotag *geotag;
@property(readonly, nonatomic) TFNTwitterGeotag *representedGeotag;
@property(readonly, nonatomic) _Bool primaryMediaRequiresAttribution;
@property(readonly, nonatomic) _Bool isMediaEntityVideo;
@property(readonly, nonatomic) _Bool isAudio;
@property(readonly, nonatomic) _Bool isReply;
@property(readonly, nonatomic) long long primaryCardType;
@property(readonly, nonatomic) unsigned long long primaryMediaType;
@property(readonly, nonatomic) TFNTwitterMediaInfo *primaryMediaInfo;
@property(readonly, nonatomic) NSArray *inlineMediaInfos;
@property(readonly, nonatomic) TFNTwitterCampaignMetadata *campaignMetadata;
@property(readonly, nonatomic) TFNTwitterFeedbackInfo *feedbackInfo;
@property(readonly, nonatomic) TFNTwitterCardData *representedCardData;
@property(readonly, nonatomic) TFNTwitterCardData *cardData;
@property(readonly, nonatomic) _Bool isQuoted;
@property(readonly, nonatomic) _Bool isQuoteStatus;
@property(readonly, nonatomic) id <T1StatusViewModel> mediaForwardViewModel;
@property(readonly, nonatomic) id <T1StatusViewModel> quotedStatusViewModel;
@property(readonly, nonatomic) NSString *retweetedByAccessibilityLabel;
@property(readonly, nonatomic) _Bool isRetweet;
@property(readonly, nonatomic) long long lastDisplayReplyCount;
@property(readonly, nonatomic) long long lastDisplayRetweetCount;
@property(readonly, nonatomic) long long lastDisplayFavoriteCount;
@property(readonly, nonatomic) long long displayReplyCount;
@property(readonly, nonatomic) long long displayRetweetCount;
@property(readonly, nonatomic) long long displayFavoriteCount;
@property(readonly, nonatomic) NSString *withheldScope;
@property(readonly, nonatomic) _Bool displayAsNewsCameraTweet;
@property(readonly, nonatomic) _Bool displayAsWithheld;
@property(readonly, nonatomic) _Bool hasModeratedReplies;
@property(readonly, nonatomic) UIColor *replyBadgeBackgroundColor;
@property(readonly, copy, nonatomic) NSString *replyBadgeText;
@property(readonly, nonatomic) _Bool hasReplyBadge;
@property(readonly, nonatomic) _Bool isPinned;
@property(readonly, nonatomic) _Bool isLifelineAlert;
@property(readonly, nonatomic) _Bool isNonPolicyCompliantTweetViewModel;
@property(readonly, nonatomic) _Bool isPossiblySensitiveViewModel;
@property(readonly, nonatomic) NSArray *hiddenURLEntities;
@property(readonly, nonatomic) NSArray *hiddenMentionEntities;
@property(readonly, nonatomic) TFSTwitterEntitySet *entities;
@property(readonly, copy, nonatomic) NSString *momentID;
@property(readonly, nonatomic) NSString *text;
@property(readonly, nonatomic) long long representedStatusID;
@property(readonly, nonatomic) long long representedFromUserID;
@property(readonly, nonatomic) NSString *representedFromUserName;
@property(readonly, nonatomic) long long fromUserID;
@property(readonly, nonatomic) NSString *fromUserName;
@property(readonly, nonatomic) NSString *fromUserFullName;
@property(readonly, nonatomic) NSDate *displayDate;
@property(readonly, nonatomic) long long statusID;
@property(readonly, nonatomic) NSString *unifiedID;
@property(readonly, nonatomic) NSString *statusItemViewModelDidUpdateNotificationName;
@property(readonly, nonatomic) TFNTwitterStatus *legacyStatus;
- (NSDictionary *)updatedScribeParameters:(NSDictionary *)arg1;
- (_Bool)hasTwitterMediaIncludingPartners:(unsigned long long)arg1;
- (_Bool)isAttachmentTypePhotoOrVideo:(unsigned long long)arg1;
- (TFNAttributedTextModel *)attributedTextModelForOptions:(unsigned long long)arg1 withFont:(UIFont *)arg2 boldFont:(UIFont *)arg3 lineHeight:(double)arg4 darkBackground:(_Bool)arg5 defaultTextColor:(UIColor *)arg6 linkTextColor:(UIColor *)arg7 highlighted:(_Bool)arg8 truncationString:(NSString *)arg9 cachingEnabled:(_Bool)arg10;
- (long long)attributedDisplayTextHeightForOptions:(unsigned long long)arg1 withWidth:(double)arg2 font:(UIFont *)arg3 boldFont:(UIFont *)arg4 lineHeight:(double)arg5 darkBackground:(_Bool)arg6 defaultTextColor:(UIColor *)arg7 linkTextColor:(UIColor *)arg8 truncationString:(NSString *)arg9 cachingEnabled:(_Bool)arg10 isTextTruncated:(out _Bool *)arg11;
- (NSArray *)displayTextPlaceRangesForOptions:(unsigned long long)arg1;
- (_Bool)displayTextMayHaveUndetectedHashflagsForOptions:(unsigned long long)arg1;
- (NSArray *)displayTextHashflagsForOptions:(unsigned long long)arg1;
- (NSArray *)displayTextURLRangesForOptions:(unsigned long long)arg1;
- (NSArray *)displayTextRangesForOptions:(unsigned long long)arg1;
- (NSString *)displayTextForOptions:(unsigned long long)arg1;
- (NSString *)accessibilityTextForOptions:(unsigned long long)arg1;
- (NSString *)socialContextURL;
- (NSString *)socialBadgeName;
- (NSString *)socialText;
- (void)syncLastDisplayCounts;
@end

