//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class NSArray, NSString, TFSURTUrl;

@protocol T1TwitterSocialContext
@property(readonly, copy, nonatomic) TFSURTUrl *landingURL;
@property(readonly, copy, nonatomic) NSArray *allUserReferences;
@property(readonly, copy, nonatomic) NSString *socialBadgeName;
@property(readonly, copy, nonatomic) NSString *socialText;
@property(readonly, copy, nonatomic) NSString *socialContextScribePage;
@property(readonly, copy, nonatomic) NSString *socialContextScribeElement;
@property(readonly, copy, nonatomic) NSString *activityTitle;
@end

