//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIImageView, UILabel;

@interface T1UnifiedCardCarouselPageIndicatorView : UIView
{
    unsigned long long _currentPageNumber;
    UILabel *_indicator;
    UIImageView *_icon;
    unsigned long long _totalPages;
}

@property(readonly, nonatomic) unsigned long long totalPages; // @synthesize totalPages=_totalPages;
@property(retain, nonatomic) UIImageView *icon; // @synthesize icon=_icon;
@property(retain, nonatomic) UILabel *indicator; // @synthesize indicator=_indicator;
@property(nonatomic) unsigned long long currentPageNumber; // @synthesize currentPageNumber=_currentPageNumber;
- (void).cxx_destruct;
- (void)_t1_updateLabel;
- (void)sizeToFit;
- (void)layoutSubviews;
- (struct CGSize)intrinsicContentSize;
- (id)backgroundColor;
- (void)setBackgroundColor:(id)arg1;
- (void)setTotalPages:(unsigned long long)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)init;
- (id)initWithFrame:(struct CGRect)arg1 totalPages:(unsigned long long)arg2;

@end

