//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <T1Twitter/T1AccessibilityCustomActionsProtocol-Protocol.h>

@class TFNTwitterUnifiedCard, TIPImagePipeline, UIView;
@protocol T1UnifiedCardComponentViewEventDelegate, T1UnifiedCardComponentViewLayoutDelegate, TFNTwitterUnifiedCardComponentModel;

@protocol T1UnifiedCardComponentView <T1AccessibilityCustomActionsProtocol>
+ (id <T1UnifiedCardComponentViewLayoutDelegate>)sharedLayoutDelegate;
@property(readonly, nonatomic) _Bool shouldDelayContainerTouchDownHighlighting;
@property(readonly, nonatomic) UIView *autoplayableContainerView;
@property(retain, nonatomic) TIPImagePipeline *imagePipeline;
@property(nonatomic) __weak id <T1UnifiedCardComponentViewEventDelegate> eventDelegate;
@property(retain, nonatomic) id <TFNTwitterUnifiedCardComponentModel> component;
@property(retain, nonatomic) TFNTwitterUnifiedCard *unifiedCard;
- (void)prepareForReuse;
- (void)setupActions;
@end

