//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSError, NSString;

@interface TFNDirectMessageLookupConversationFingerprintResult : NSObject
{
    _Bool _success;
    NSString *_fingerprint;
    NSError *_error;
}

@property(readonly, nonatomic) NSError *error; // @synthesize error=_error;
@property(readonly, copy, nonatomic) NSString *fingerprint; // @synthesize fingerprint=_fingerprint;
@property(readonly, nonatomic) _Bool success; // @synthesize success=_success;
- (void).cxx_destruct;
- (id)initWithSuccess:(_Bool)arg1 fingerprint:(id)arg2 error:(id)arg3;

@end

