//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface TFNDirectMessageKeyRegistryUserDefaults : NSObject
{
}

+ (id)private_makeUserDefaultsKey:(id)arg1 accountID:(id)arg2;
+ (void)setKeyRegistryState:(long long)arg1 accountID:(id)arg2;
+ (void)setActivationPromptDidComplete:(_Bool)arg1 accountID:(id)arg2;
+ (void)setDeviceHasBeenActive:(_Bool)arg1 accountID:(id)arg2;
+ (long long)lookupKeyRegistryStateForAccountID:(id)arg1;
+ (_Bool)lookupActivationPromptDidCompleteForAccountID:(id)arg1;
+ (_Bool)lookupDeviceHasBeenActiveForAccountID:(id)arg1;

@end

