//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <T1Twitter/NSObject-Protocol.h>

@class NSDate, NSString;
@protocol TFNDirectMessageConversation, TFNDirectMessageConversationParticipant, TFNDirectMessageUser;

@protocol TFNDirectMessageConversationParticipant <NSObject>
@property(nonatomic, readonly) NSString *identityKey;
@property(nonatomic, readonly) NSString *deviceID;
@property(nonatomic, readonly) _Bool isAdmin;
@property(nonatomic, readonly) id <TFNDirectMessageConversation> conversation;
@property(nonatomic, readonly) NSDate *joinDate;
@property(nonatomic, readonly) id <TFNDirectMessageUser> participatingUser;
- (long long)compare:(id <TFNDirectMessageConversationParticipant>)arg1;
@end

