//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <T1Twitter/TFNOnboardingSubtask.h>

@class NSString, TFNOnboardingNavigationLink, TFNOnboardingRichText;

@interface TFNOnboardingPrivacyOptionsSubtask : TFNOnboardingSubtask
{
    _Bool _discoverableByEmail;
    _Bool _discoverableByPhone;
    NSString *_primaryText;
    NSString *_secondaryText;
    NSString *_discoverableByEmailLabel;
    TFNOnboardingRichText *_discoverableByEmailDetailText;
    NSString *_discoverableByPhoneLabel;
    TFNOnboardingRichText *_discoverableByPhoneDetailText;
    TFNOnboardingNavigationLink *_nextLink;
}

+ (id)typeNames;
@property(readonly, nonatomic) TFNOnboardingNavigationLink *nextLink; // @synthesize nextLink=_nextLink;
@property(readonly, nonatomic) TFNOnboardingRichText *discoverableByPhoneDetailText; // @synthesize discoverableByPhoneDetailText=_discoverableByPhoneDetailText;
@property(readonly, nonatomic) NSString *discoverableByPhoneLabel; // @synthesize discoverableByPhoneLabel=_discoverableByPhoneLabel;
@property(readonly, nonatomic) _Bool discoverableByPhone; // @synthesize discoverableByPhone=_discoverableByPhone;
@property(readonly, nonatomic) TFNOnboardingRichText *discoverableByEmailDetailText; // @synthesize discoverableByEmailDetailText=_discoverableByEmailDetailText;
@property(readonly, nonatomic) NSString *discoverableByEmailLabel; // @synthesize discoverableByEmailLabel=_discoverableByEmailLabel;
@property(readonly, nonatomic) _Bool discoverableByEmail; // @synthesize discoverableByEmail=_discoverableByEmail;
@property(readonly, nonatomic) NSString *secondaryText; // @synthesize secondaryText=_secondaryText;
@property(readonly, nonatomic) NSString *primaryText; // @synthesize primaryText=_primaryText;
- (void).cxx_destruct;
- (id)initWithJSONDictionary:(id)arg1 subtaskID:(id)arg2 typeName:(id)arg3 backNavigationType:(long long)arg4 error:(id *)arg5;

@end

