//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIControl.h>

@class NSArray, TFNSegmentedControlItem, TFNSegmentedControlItemView, UIColor, UIFont;

@interface TFNSegmentedControl : UIControl
{
    NSArray *_itemViews;
    TFNSegmentedControlItem *_moreItem;
    _Bool _shouldResetItemViews;
    TFNSegmentedControlItemView *_moreItemView;
    _Bool _moreItemVisible;
    _Bool _subtitlesVisible;
    NSArray *_items;
    NSArray *_overflowItems;
    long long _moreItemIndex;
    unsigned long long _selectedItemIndex;
    UIFont *_titleFont;
    UIFont *_subtitleFont;
    UIColor *_strokeColor;
    UIColor *_fillColor;
    double _subtitleAlpha;
}

@property(nonatomic, getter=areSubtitlesVisible) _Bool subtitlesVisible; // @synthesize subtitlesVisible=_subtitlesVisible;
@property(nonatomic) double subtitleAlpha; // @synthesize subtitleAlpha=_subtitleAlpha;
@property(retain, nonatomic) UIColor *fillColor; // @synthesize fillColor=_fillColor;
@property(retain, nonatomic) UIColor *strokeColor; // @synthesize strokeColor=_strokeColor;
@property(retain, nonatomic) UIFont *subtitleFont; // @synthesize subtitleFont=_subtitleFont;
@property(retain, nonatomic) UIFont *titleFont; // @synthesize titleFont=_titleFont;
@property(nonatomic) unsigned long long selectedItemIndex; // @synthesize selectedItemIndex=_selectedItemIndex;
@property(readonly, nonatomic) long long moreItemIndex; // @synthesize moreItemIndex=_moreItemIndex;
@property(readonly, nonatomic, getter=isMoreItemVisible) _Bool moreItemVisible; // @synthesize moreItemVisible=_moreItemVisible;
@property(readonly, nonatomic) NSArray *overflowItems; // @synthesize overflowItems=_overflowItems;
@property(copy, nonatomic) NSArray *items; // @synthesize items=_items;
- (void).cxx_destruct;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)layoutSubviews;
- (id)_itemViewWithItem:(id)arg1 type:(unsigned long long)arg2;
@property(readonly, nonatomic) TFNSegmentedControlItemView *moreItemView;
- (id)moreItem;
- (void)_setupItemViewsIfNeeded;
- (void)setFrame:(struct CGRect)arg1;
- (id)initWithItems:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

