//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSDictionary, NSString, TFNTwitterLiveEventCarousel, TFNTwitterLiveEventScore, TFNTwitterTimelineCursor, TFNTwitterTimelineReplaceEntries;

@interface TFNTwitterRichTimelineResponse : NSObject
{
    NSDictionary *_statusesDictionary;
    NSDictionary *_usersDictionary;
    NSArray *_timelineArray;
    NSDictionary *_momentsDictionary;
    NSDictionary *_liveEventsDictionary;
    TFNTwitterLiveEventCarousel *_liveEventCarousel;
    TFNTwitterLiveEventScore *_liveEventScore;
    TFNTwitterTimelineCursor *_cursor;
    NSArray *_updateDisplayActionNotifications;
    TFNTwitterTimelineReplaceEntries *_replaceEntries;
    NSDictionary *_reactiveBlendingMetadata;
    NSDictionary *_pinnedEntryDictionary;
    double _pollingInterval;
    NSString *_timelineID;
}

+ (id)richTimelineResponseWithJSONData:(id)arg1 error:(id *)arg2;
@property(readonly, nonatomic) NSString *timelineID; // @synthesize timelineID=_timelineID;
@property(readonly, nonatomic) double pollingInterval; // @synthesize pollingInterval=_pollingInterval;
@property(readonly, nonatomic) NSDictionary *pinnedEntryDictionary; // @synthesize pinnedEntryDictionary=_pinnedEntryDictionary;
@property(readonly, nonatomic) NSDictionary *reactiveBlendingMetadata; // @synthesize reactiveBlendingMetadata=_reactiveBlendingMetadata;
@property(readonly, nonatomic) TFNTwitterTimelineReplaceEntries *replaceEntries; // @synthesize replaceEntries=_replaceEntries;
@property(readonly, nonatomic) NSArray *updateDisplayActionNotifications; // @synthesize updateDisplayActionNotifications=_updateDisplayActionNotifications;
@property(readonly, nonatomic) TFNTwitterTimelineCursor *cursor; // @synthesize cursor=_cursor;
@property(readonly, nonatomic) TFNTwitterLiveEventScore *liveEventScore; // @synthesize liveEventScore=_liveEventScore;
@property(readonly, nonatomic) TFNTwitterLiveEventCarousel *liveEventCarousel; // @synthesize liveEventCarousel=_liveEventCarousel;
@property(readonly, nonatomic) NSDictionary *liveEventsDictionary; // @synthesize liveEventsDictionary=_liveEventsDictionary;
@property(readonly, nonatomic) NSDictionary *momentsDictionary; // @synthesize momentsDictionary=_momentsDictionary;
@property(readonly, nonatomic) NSArray *timelineArray; // @synthesize timelineArray=_timelineArray;
@property(readonly, nonatomic) NSDictionary *usersDictionary; // @synthesize usersDictionary=_usersDictionary;
@property(readonly, nonatomic) NSDictionary *statusesDictionary; // @synthesize statusesDictionary=_statusesDictionary;
- (void).cxx_destruct;
- (id)richTimelineResponseByReplacingStatusesDictionary:(id)arg1 usersDictionary:(id)arg2;
- (id)initWithJSONDictionary:(id)arg1;
- (id)initWithStatusesDictionary:(id)arg1 usersDictionary:(id)arg2 timelineArray:(id)arg3 momentsDictionary:(id)arg4 liveEventsDictionary:(id)arg5 liveEventCarousel:(id)arg6 liveEventScore:(id)arg7 cursor:(id)arg8 updateDisplayActionNotifications:(id)arg9 reactiveBlendingMetadata:(id)arg10 pollingInterval:(double)arg11 timelineID:(id)arg12 replaceEntries:(id)arg13 pinnedEntryDictionary:(id)arg14;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

