//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <T1Twitter/TFNTwitterStatusSocialContext-Protocol.h>

@class NSArray, NSString;

@interface TFNTwitterStatusMagicRecsSocialContext : NSObject <TFNTwitterStatusSocialContext>
{
    long long _type;
    NSArray *_sourceUserReferences;
}

@property(readonly, nonatomic) NSArray *sourceUserReferences; // @synthesize sourceUserReferences=_sourceUserReferences;
@property(readonly, nonatomic) long long type; // @synthesize type=_type;
- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)timelinePlistDictionaryValue;
- (id)initWithPlistDictionary:(id)arg1;
- (id)initWithTimelinePlistDictionary:(id)arg1;
- (id)plistDictionaryValueForTimeline:(_Bool)arg1;
- (id)landingURL;
- (long long)contextType;
- (id)activityPage;
- (id)activityTitle;
- (_Bool)socialTextIsActivityCount;
- (id)plistDictionaryValue;
- (id)activityName;
- (id)allUserReferences;
- (id)_socialTextForFollowed;
- (id)_socialTextForRetweeted;
- (id)_socialTextForFavorited;
- (id)socialText;
- (id)sourcesUserIDs;
- (id)initWithMagicRecType:(long long)arg1 sources:(id)arg2;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

