//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <T1Twitter/TFSPlistSerialization-Protocol.h>

@class NSString;

@interface TFNTwitterMomentPremadeMomentData : NSObject <TFSPlistSerialization>
{
    _Bool _momentViewedByUser;
}

@property(readonly, nonatomic) _Bool momentViewedByUser; // @synthesize momentViewedByUser=_momentViewedByUser;
- (_Bool)isEqual:(id)arg1;
@property(readonly, copy) NSString *description;
- (id)_initWithDictionary:(id)arg1 plistSerialization:(_Bool)arg2;
- (id)plistDictionaryValue;
- (id)initWithPlistDictionary:(id)arg1;
- (id)initWithJSONDictionary:(id)arg1;
- (id)initWithMomentViewedByUser:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

