//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <T1Twitter/TFSPlistSerialization-Protocol.h>

@class NSString, TFNTwitterMomentCapsuleBadge;

@interface TFNTwitterMomentCapsuleCTA : NSObject <TFSPlistSerialization>
{
    NSString *_text;
    NSString *_uri;
    TFNTwitterMomentCapsuleBadge *_badge;
}

@property(readonly, nonatomic) TFNTwitterMomentCapsuleBadge *badge; // @synthesize badge=_badge;
@property(readonly, nonatomic) NSString *uri; // @synthesize uri=_uri;
@property(readonly, nonatomic) NSString *text; // @synthesize text=_text;
- (void).cxx_destruct;
- (_Bool)isEqual:(id)arg1;
@property(readonly) unsigned long long hash;
@property(readonly, copy) NSString *description;
- (id)plistDictionaryValue;
- (id)initWithPlistDictionary:(id)arg1;
- (id)initWithJSONDictionary:(id)arg1;
- (id)initWithText:(id)arg1 uri:(id)arg2 badge:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) Class superclass;

@end

