//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <T1Twitter/TFNTwitterHomeTimelineConfiguration-Protocol.h>

@class NSArray, NSString;
@protocol TFNTwitterDynamicTimelineConfiguration, TNUNetworkQualityProvider;

@interface TFNTwitterSuggestsConfiguration : NSObject <TFNTwitterHomeTimelineConfiguration>
{
    _Bool _progressiveAPIEnabled;
    _Bool _dedupingStatusIDsEnabled;
    _Bool _isClientDedupingUsingImpressionCacheEnabled;
    _Bool _isLatestHomeTimelineOptionAvailable;
    unsigned long long _streamOptions;
    NSArray *_streamObjectsFilters;
    long long _userID;
    NSString *_username;
    unsigned long long _homeRequestMaxSeenIDs;
    long long _progressiveAPISegmentSize;
    unsigned long long _clientDedupingMaxRecentCacheEntries;
    NSArray *_clientDedupingSuggestTypesToRemove;
    NSArray *_clientDedupingSuggestTypesToKeep;
    unsigned long long _clientDedupingMinimumModuleSize;
    id <TNUNetworkQualityProvider> _networkQualityProvider;
    id <TFNTwitterDynamicTimelineConfiguration> _dynamicTimelineConfiguration;
    double _homeTimelineBackgroundFetchUILaunchDelay;
}

+ (unsigned long long)_setupStreamOptionsForAccount:(id)arg1;
+ (_Bool)_streamObjectIsMomentRelated:(id)arg1;
+ (id)suggestsConfigurationForAccount:(id)arg1 configType:(long long)arg2;
+ (id)suggestsConfigurationForAccount:(id)arg1;
@property(readonly, nonatomic) _Bool isLatestHomeTimelineOptionAvailable; // @synthesize isLatestHomeTimelineOptionAvailable=_isLatestHomeTimelineOptionAvailable;
@property(readonly, nonatomic) double homeTimelineBackgroundFetchUILaunchDelay; // @synthesize homeTimelineBackgroundFetchUILaunchDelay=_homeTimelineBackgroundFetchUILaunchDelay;
@property(readonly, nonatomic) id <TFNTwitterDynamicTimelineConfiguration> dynamicTimelineConfiguration; // @synthesize dynamicTimelineConfiguration=_dynamicTimelineConfiguration;
@property(readonly, nonatomic) id <TNUNetworkQualityProvider> networkQualityProvider; // @synthesize networkQualityProvider=_networkQualityProvider;
@property(readonly, nonatomic) unsigned long long clientDedupingMinimumModuleSize; // @synthesize clientDedupingMinimumModuleSize=_clientDedupingMinimumModuleSize;
@property(readonly, nonatomic) NSArray *clientDedupingSuggestTypesToKeep; // @synthesize clientDedupingSuggestTypesToKeep=_clientDedupingSuggestTypesToKeep;
@property(readonly, nonatomic) NSArray *clientDedupingSuggestTypesToRemove; // @synthesize clientDedupingSuggestTypesToRemove=_clientDedupingSuggestTypesToRemove;
@property(readonly, nonatomic) unsigned long long clientDedupingMaxRecentCacheEntries; // @synthesize clientDedupingMaxRecentCacheEntries=_clientDedupingMaxRecentCacheEntries;
@property(readonly, nonatomic) _Bool isClientDedupingUsingImpressionCacheEnabled; // @synthesize isClientDedupingUsingImpressionCacheEnabled=_isClientDedupingUsingImpressionCacheEnabled;
@property(readonly, nonatomic, getter=isDedupingStatusIDsEnabled) _Bool dedupingStatusIDsEnabled; // @synthesize dedupingStatusIDsEnabled=_dedupingStatusIDsEnabled;
@property(readonly, nonatomic) long long progressiveAPISegmentSize; // @synthesize progressiveAPISegmentSize=_progressiveAPISegmentSize;
@property(readonly, nonatomic, getter=isProgressiveAPIEnabled) _Bool progressiveAPIEnabled; // @synthesize progressiveAPIEnabled=_progressiveAPIEnabled;
@property(readonly, nonatomic) unsigned long long homeRequestMaxSeenIDs; // @synthesize homeRequestMaxSeenIDs=_homeRequestMaxSeenIDs;
@property(readonly, nonatomic) NSString *username; // @synthesize username=_username;
@property(readonly, nonatomic) long long userID; // @synthesize userID=_userID;
@property(readonly, nonatomic) NSArray *streamObjectsFilters; // @synthesize streamObjectsFilters=_streamObjectsFilters;
@property(readonly, nonatomic) unsigned long long streamOptions; // @synthesize streamOptions=_streamOptions;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSString *scribePage;
@property(readonly, nonatomic) BOOL URTIntegrationMode;
@property(readonly, nonatomic) _Bool enableHomeTimelineRequestWithSeenIDs;
@property(readonly, nonatomic) _Bool validateCachedStreamObjects;
@property(readonly, nonatomic) _Bool cacheStreamObjects;
@property(readonly, nonatomic) _Bool enableRecommendedHomeTimeline;
@property(readonly, nonatomic) _Bool enableLatestTweetsTimeline;
@property(readonly, nonatomic) _Bool enableReactiveArticleBlending;
@property(readonly, nonatomic) _Bool includeBlockingInfo;
@property(readonly, nonatomic) _Bool enableAutoplay;
- (id)initWithStreamOptions:(unsigned long long)arg1 streamObjectsFilters:(id)arg2 userID:(long long)arg3 username:(id)arg4 featureSwitchParameters:(id)arg5 networkQualityProvider:(id)arg6 dynamicTimelineConfiguration:(id)arg7;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

