//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <T1Twitter/NSObject-Protocol.h>

@protocol TFNTwitterMediaUploadConfiguration <NSObject>
@property(readonly, nonatomic) double mediaAsyncUploadMaxGifSize;
@property(readonly, nonatomic) double mediaAsyncUploadMaxVideoDuration;
@property(readonly, nonatomic) long long mediaUploadGroupPolicy;
@property(readonly, nonatomic, getter=isVideoUploadSegmentSizeBasedOnNetworkQualityEnabled) _Bool videoUploadSegmentSizeBasedOnNetworkQualityEnabled;
@property(readonly, nonatomic) long long videosSegmentedUploadMaxiumRetryPerRequest;
@property(readonly, nonatomic) long long videosSegmentedUploadMinimumSegmentSize;
@property(readonly, nonatomic) long long videosSegmentedUploadSegmentSizeForGreatNetwork;
@property(readonly, nonatomic) long long videosSegmentedUploadSegmentSizeForGoodNetwork;
@property(readonly, nonatomic) long long videosSegmentedUploadSegmentSizeForPoorNetwork;
@property(readonly, nonatomic) long long videosSegmentedUploadSegmentSizeForCellular;
@property(readonly, nonatomic) long long videosSegmentedUploadSegmentSizeForWiFi;
@property(readonly, nonatomic, getter=isVideosSegmentedUploadSegmentSizeBackoffPolicyEnabled) _Bool videosSegmentedUploadSegmentSizeBackoffPolicyEnabled;
@property(readonly, nonatomic, getter=isPhotoUploadSegmentSizeBasedOnNetworkQualityEnabled) _Bool photoUploadSegmentSizeBasedOnNetworkQualityEnabled;
@property(readonly, nonatomic) double photoLowBandwidthUploadResolution;
@property(readonly, nonatomic) double photoMediumBandwidthUploadResolution;
@property(readonly, nonatomic) double photoHighBandwidthUploadResolution;
@property(readonly, nonatomic) long long photosSegmentedUploadMaxiumRetryPerRequest;
@property(readonly, nonatomic) long long photosSegmentedUploadMinimumSegmentSize;
@property(readonly, nonatomic) long long photosSegmentedUploadSegmentSizeForGreatNetwork;
@property(readonly, nonatomic) long long photosSegmentedUploadSegmentSizeForGoodNetwork;
@property(readonly, nonatomic) long long photosSegmentedUploadSegmentSizeForPoorNetwork;
@property(readonly, nonatomic) long long photosSegmentedUploadSegmentSizeForCellular;
@property(readonly, nonatomic) long long photosSegmentedUploadSegmentSizeForWiFi;
@property(readonly, nonatomic, getter=isPhotosSegmentedUploadSegmentSizeBackoffPolicyEnabled) _Bool photosSegmentedUploadSegmentSizeBackoffPolicyEnabled;
@end

