//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class TFNTwitterTimelineCursor;

@interface TFNTwitterTimelineCursorState : NSObject
{
    TFNTwitterTimelineCursor *_topCursor;
    TFNTwitterTimelineCursor *_bottomCursor;
}

+ (id)cursorStateWithTopCursor:(id)arg1 bottomCursor:(id)arg2;
@property(readonly, nonatomic) TFNTwitterTimelineCursor *bottomCursor; // @synthesize bottomCursor=_bottomCursor;
@property(readonly, nonatomic) TFNTwitterTimelineCursor *topCursor; // @synthesize topCursor=_topCursor;
- (void).cxx_destruct;
- (id)initWithTopCursor:(id)arg1 bottomCursor:(id)arg2;

@end

