//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <T1Twitter/TFNTwitterStatusCardDataSource-Protocol.h>

@class NSDictionary, NSString, TFNTwitterCardData, TFNTwitterPromotedContent;
@protocol TFNTwitterCanonicalTimelineStatus, TFNTwitterCardDataSourceObject;

@interface TFNTwitterStatusCardDataSource : NSObject <TFNTwitterStatusCardDataSource>
{
    TFNTwitterCardData *_cardData;
    NSDictionary *_cardEvent;
    TFNTwitterPromotedContent *_promotedContent;
    NSDictionary *_scribeItem;
    id <TFNTwitterCanonicalTimelineStatus> _status;
}

+ (id)cardDataForStatus:(id)arg1;
@property(readonly, nonatomic) id <TFNTwitterCanonicalTimelineStatus> status; // @synthesize status=_status;
@property(readonly, nonatomic) NSDictionary *scribeItem; // @synthesize scribeItem=_scribeItem;
@property(readonly, nonatomic) TFNTwitterPromotedContent *promotedContent; // @synthesize promotedContent=_promotedContent;
@property(readonly, nonatomic) TFNTwitterCardData *cardData; // @synthesize cardData=_cardData;
- (void).cxx_destruct;
- (_Bool)isEqual:(id)arg1;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) __weak id <TFNTwitterCardDataSourceObject> sourceObject;
- (id)entityForURL:(id)arg1;
@property(readonly, nonatomic) NSDictionary *cardEvent; // @synthesize cardEvent=_cardEvent;
- (long long)sourceID;
- (id)initWithStatus:(id)arg1 promotedContent:(id)arg2 cardData:(id)arg3 scribeItem:(id)arg4;
- (id)initWithStatus:(id)arg1 promotedContent:(id)arg2 scribeItem:(id)arg3;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) Class superclass;

@end

