//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class TFNTwitterAccount, TNUTransactionMetrics;

@interface TFNTwitterCompositionUploadContext : NSObject
{
    _Bool _shouldDowngradeImageAttachments;
    TFNTwitterAccount *_account;
    TNUTransactionMetrics *_networkTransactionMetrics;
    double _retryTimeout;
    long long _source;
}

@property(readonly, nonatomic) long long source; // @synthesize source=_source;
@property(readonly, nonatomic) _Bool shouldDowngradeImageAttachments; // @synthesize shouldDowngradeImageAttachments=_shouldDowngradeImageAttachments;
@property(readonly, nonatomic) double retryTimeout; // @synthesize retryTimeout=_retryTimeout;
@property(readonly, nonatomic) TNUTransactionMetrics *networkTransactionMetrics; // @synthesize networkTransactionMetrics=_networkTransactionMetrics;
@property(readonly, nonatomic) TFNTwitterAccount *account; // @synthesize account=_account;
- (void).cxx_destruct;
- (id)initWithAccount:(id)arg1 networkTransactionMetrics:(id)arg2 shouldDowngradeImageAttachments:(_Bool)arg3 source:(long long)arg4;
- (id)init;

@end

