//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <T1Twitter/TFSPlistSerialization-Protocol.h>

@class NSString;

@interface TFNTwitterMomentLinkTitleCard : NSObject <TFSPlistSerialization>
{
    NSString *_url;
    NSString *_title;
    NSString *_displayURL;
    NSString *_vanitySource;
}

@property(readonly, nonatomic) NSString *vanitySource; // @synthesize vanitySource=_vanitySource;
@property(readonly, nonatomic) NSString *displayURL; // @synthesize displayURL=_displayURL;
@property(readonly, nonatomic) NSString *title; // @synthesize title=_title;
@property(readonly, nonatomic) NSString *url; // @synthesize url=_url;
- (void).cxx_destruct;
@property(readonly, copy) NSString *description;
- (_Bool)isEqual:(id)arg1;
@property(readonly) unsigned long long hash;
- (id)plistDictionaryValue;
- (id)initWithPlistDictionary:(id)arg1;
- (id)initWithURL:(id)arg1 title:(id)arg2 displayURL:(id)arg3 vanitySource:(id)arg4;
- (id)initWithJSONDictionary:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) Class superclass;

@end

