//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <T1Twitter/TFSScribeEventSerializer-Protocol.h>

@class NSDictionary, NSString, TFNTwitterScribeErrorHandler;

@interface TFNTwitterScribeEventJSONSerializer : NSObject <TFSScribeEventSerializer>
{
    NSDictionary *_dictionary;
    NSString *_group;
    NSDictionary *_metadata;
    TFNTwitterScribeErrorHandler *_errorHandler;
}

@property(retain, nonatomic) TFNTwitterScribeErrorHandler *errorHandler; // @synthesize errorHandler=_errorHandler;
@property(copy, nonatomic) NSDictionary *metadata; // @synthesize metadata=_metadata;
@property(copy, nonatomic) NSString *group; // @synthesize group=_group;
@property(copy, nonatomic) NSDictionary *dictionary; // @synthesize dictionary=_dictionary;
- (void).cxx_destruct;
- (id)data;
- (id)dictionaryRepresentation;
- (id)init;
- (id)initWithDictionary:(id)arg1 userID:(id)arg2;
- (id)initWithDictionary:(id)arg1 group:(id)arg2;
- (id)initWithDictionary:(id)arg1 group:(id)arg2 metadata:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

