//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <T1Twitter/TSPKeyValueStore-Protocol.h>

@class NSMutableOrderedSet, NSString, NSURL, TSPFileManager;

@interface TSPFilesystemStore : NSObject <TSPKeyValueStore>
{
    _Bool _directoryIsKnownToExist;
    NSMutableOrderedSet *_sortedKeyIndex;
    NSURL *_directoryURL;
    TSPFileManager *_fileManager;
    unsigned long long _limit;
}

+ (id)private_loadKeyIndexForDirectoryURL:(id)arg1 fileManager:(id)arg2 error:(out id *)arg3;
@property(readonly, nonatomic) unsigned long long limit; // @synthesize limit=_limit;
@property(readonly, nonatomic) TSPFileManager *fileManager; // @synthesize fileManager=_fileManager;
@property(readonly, copy, nonatomic) NSURL *directoryURL; // @synthesize directoryURL=_directoryURL;
- (void).cxx_destruct;
- (_Bool)private_verifyDirectoryExistsWithError:(out id *)arg1;
- (id)private_sortedKeyIndexWithError:(out id *)arg1;
- (id)_updateSortedKeyIndex:(id)arg1 insertingKey:(id)arg2;
- (id)_fileURLForKey:(id)arg1;
- (_Bool)tsp_removeAllObjectsWithError:(out id *)arg1;
- (_Bool)tsp_removeObjectForKey:(id)arg1 error:(out id *)arg2;
- (_Bool)tsp_containsObjectForKey:(id)arg1 result:(out _Bool *)arg2 error:(id *)arg3;
- (_Bool)tsp_storeObject:(id)arg1 forKey:(id)arg2 error:(out id *)arg3;
- (_Bool)tsp_loadObject:(out id *)arg1 forKey:(id)arg2 error:(out id *)arg3;
- (id)initWithDirectoryURL:(id)arg1 fileManager:(id)arg2 limit:(unsigned long long)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

