//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSNumber, NSString, TSPPublicKey;

@interface TSPPreKeyBundle : NSObject
{
    NSNumber *_registrationID;
    TSPPublicKey *_identityKey;
    NSNumber *_signedPreKeyID;
    TSPPublicKey *_signedPreKey;
    NSString *_signedPreKeySignature;
    NSNumber *_preKeyID;
    TSPPublicKey *_preKey;
}

@property(readonly, nonatomic) TSPPublicKey *preKey; // @synthesize preKey=_preKey;
@property(readonly, nonatomic) NSNumber *preKeyID; // @synthesize preKeyID=_preKeyID;
@property(readonly, copy, nonatomic) NSString *signedPreKeySignature; // @synthesize signedPreKeySignature=_signedPreKeySignature;
@property(readonly, nonatomic) TSPPublicKey *signedPreKey; // @synthesize signedPreKey=_signedPreKey;
@property(readonly, nonatomic) NSNumber *signedPreKeyID; // @synthesize signedPreKeyID=_signedPreKeyID;
@property(readonly, nonatomic) TSPPublicKey *identityKey; // @synthesize identityKey=_identityKey;
@property(readonly, nonatomic) NSNumber *registrationID; // @synthesize registrationID=_registrationID;
- (void).cxx_destruct;
- (id)init;
- (id)initWithRegistrationID:(id)arg1 identityKey:(id)arg2 signedPreKeyID:(id)arg3 signedPreKey:(id)arg4 signedPreKeySignature:(id)arg5 preKeyID:(id)arg6 preKey:(id)arg7;

@end

