//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIScrollView.h>

@interface UIScrollView (TFNScrolling)
- (void)_tfn_scrollAnimationWillDisplay;
- (void)_tfn_animateToDestination:(CDUnknownBlockType)arg1 completion:(CDUnknownBlockType)arg2;
- (void)_tfn_jumpToDestination:(CDUnknownBlockType)arg1;
@end

