//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@protocol T1TabBarIntegration;

@interface UIViewController (T1TabBarIntegration)
- (void)tfn_setNeedsTabBarShadowHiddenUpdate;
@property(readonly, nonatomic) _Bool tfn_prefersTabBarShadowHidden;
@property(readonly, nonatomic) id <T1TabBarIntegration> t1_tabBarIntegration;
@end

