//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@interface UIViewController (TFNTwitterStatus)
- (id)_t1_togglePinnedTweetActionItemWithStatus:(id)arg1 account:(id)arg2 scribePage:(id)arg3 scribeSection:(id)arg4 scribeComponent:(id)arg5;
- (id)_t1_adsInfoActionItem:(id)arg1 account:(id)arg2;
- (id)_t1_copyLinkToTweetActionItem:(id)arg1 account:(id)arg2;
- (id)_t1_mailTweetActionItem:(id)arg1 account:(id)arg2 scribeComponent:(id)arg3;
- (id)_t1_shareTweetActionItemsForStatus:(id)arg1 account:(id)arg2;
- (id)_t1_cardEntityUrlFromStatus:(id)arg1;
- (void)_t1_cardLogAppDownloadWithStatus:(id)arg1 account:(id)arg2 scribeAction:(id)arg3 page:(id)arg4 section:(id)arg5 component:(id)arg6 parameters:(id)arg7;
- (id)_t1_activityViewControllerActivitiesForEntityURL:(id)arg1 account:(id)arg2 scribeContext:(id)arg3;
- (id)t1_activityViewControllerActivitiesFromActionItems:(id)arg1;
- (id)_t1_mediaActivityViewActionItemsForStatus:(id)arg1 account:(id)arg2 image:(id)arg3;
- (id)_t1_activityViewControllerForStatus:(id)arg1 account:(id)arg2 actionItems:(id)arg3 image:(id)arg4 entityURL:(id)arg5 type:(long long)arg6 source:(id)arg7 scribeContext:(id)arg8 doneBlock:(CDUnknownBlockType)arg9;
- (id)t1_actionItemsForActivityViewController:(id)arg1;
- (id)t1_actionItemsForStatus:(id)arg1 account:(id)arg2 source:(id)arg3 options:(unsigned long long)arg4;
- (id)t1_activityViewControllerForStatus:(id)arg1 account:(id)arg2 actionItems:(id)arg3 image:(id)arg4 URL:(id)arg5 type:(long long)arg6 source:(id)arg7 scribeContext:(id)arg8 doneBlock:(CDUnknownBlockType)arg9;
- (CDUnknownBlockType)t1_shareViaActionBlockForStatus:(id)arg1 account:(id)arg2 actionItems:(id)arg3 urlString:(id)arg4 type:(long long)arg5 source:(id)arg6 scribeComponent:(id)arg7;
- (id)_t1_shareViaActionItemForStatus:(id)arg1 account:(id)arg2 actionItems:(id)arg3 urlString:(id)arg4 type:(long long)arg5 source:(id)arg6 scribeComponent:(id)arg7;
- (id)_t1_negativeFeedbackActionsForStatus:(id)arg1 account:(id)arg2;
- (id)t1_mediaActivityViewControllerForStatus:(id)arg1 account:(id)arg2 image:(id)arg3 URL:(id)arg4 type:(long long)arg5 source:(id)arg6 scribeContext:(id)arg7 doneBlock:(CDUnknownBlockType)arg8;
- (id)_t1_actionItemsForStatus:(id)arg1 account:(id)arg2 entityURL:(id)arg3 source:(id)arg4 options:(unsigned long long)arg5 scribeComponent:(id)arg6 doneBlock:(inout CDUnknownBlockType *)arg7;
- (id)t1_activityActionItemsForStatus:(id)arg1 account:(id)arg2 entityURL:(id)arg3 source:(id)arg4 scribeComponent:(id)arg5;
- (id)t1_activityViewControllerForLiveEvent:(id)arg1 account:(id)arg2 source:(id)arg3 scribeContext:(id)arg4 doneBlock:(CDUnknownBlockType)arg5;
- (id)t1_activityViewControllerForMoment:(id)arg1 account:(id)arg2 source:(id)arg3 scribeContext:(id)arg4 doneBlock:(CDUnknownBlockType)arg5;
- (id)t1_activityViewControllerForStatus:(id)arg1 account:(id)arg2 entityURL:(id)arg3 source:(id)arg4 scribeContext:(id)arg5 doneBlock:(CDUnknownBlockType)arg6;
- (id)t1_activityViewControllerForAccount:(id)arg1 entityURL:(id)arg2 source:(id)arg3 scribeContext:(id)arg4 doneBlock:(CDUnknownBlockType)arg5;
- (id)t1_menuSheetForStatus:(id)arg1 account:(id)arg2 source:(id)arg3 options:(unsigned long long)arg4 doneBlock:(CDUnknownBlockType)arg5;
- (id)t1_menuSheetForStatus:(id)arg1 account:(id)arg2 source:(id)arg3 doneBlock:(CDUnknownBlockType)arg4;
- (id)t1_actionSheetForStatus:(id)arg1 account:(id)arg2 source:(id)arg3 options:(unsigned long long)arg4 doneBlock:(CDUnknownBlockType)arg5;
- (id)t1_actionSheetForStatus:(id)arg1 account:(id)arg2 source:(id)arg3 doneBlock:(CDUnknownBlockType)arg4;
- (id)_t1_dismissMultiActionItemsForStatus:(id)arg1 inCarousel:(id)arg2 account:(id)arg3 source:(id)arg4 options:(unsigned long long)arg5 dismissingBlock:(CDUnknownBlockType)arg6;
- (id)t1_dismissMultiMenuSheetForStatus:(id)arg1 inCarousel:(id)arg2 account:(id)arg3 source:(id)arg4 options:(unsigned long long)arg5 dismissingBlock:(CDUnknownBlockType)arg6;
- (id)t1_dismissMultiActionSheetForStatus:(id)arg1 inCarousel:(id)arg2 account:(id)arg3 source:(id)arg4 options:(unsigned long long)arg5 dismissingBlock:(CDUnknownBlockType)arg6;
- (id)t1_bookmarksActionItemsForStatus:(id)arg1 account:(id)arg2 source:(id)arg3 options:(unsigned long long)arg4 scribeParameters:(id)arg5 doneBlock:(CDUnknownBlockType)arg6;
- (id)t1_bookmarksMenuSheetForStatus:(id)arg1 account:(id)arg2 source:(id)arg3 options:(unsigned long long)arg4 scribeParameters:(id)arg5 doneBlock:(CDUnknownBlockType)arg6;
- (id)t1_undoRetweetMenuSheetForStatus:(id)arg1 account:(id)arg2 source:(id)arg3 scribeParameters:(id)arg4 undoRetweetBlock:(CDUnknownBlockType)arg5 doneBlock:(CDUnknownBlockType)arg6;
- (id)t1_undoRetweetMenuSheetForStatus:(id)arg1 account:(id)arg2 source:(id)arg3 doneBlock:(CDUnknownBlockType)arg4;
- (id)t1_undoRetweetMenuSheetForStatus:(id)arg1 account:(id)arg2 source:(id)arg3 undoRetweetBlock:(CDUnknownBlockType)arg4;
- (CDUnknownBlockType)_t1_undoRetweetActionForStatus:(id)arg1 account:(id)arg2 scribeSection:(id)arg3 scribeComponent:(id)arg4 scribeElement:(id)arg5 parameters:(id)arg6 undoRetweetBlock:(CDUnknownBlockType)arg7;
- (id)t1_undoRetweetActionSheetForStatus:(id)arg1 account:(id)arg2 source:(id)arg3 scribeParameters:(id)arg4 undoRetweetBlock:(CDUnknownBlockType)arg5 doneBlock:(CDUnknownBlockType)arg6;
- (id)t1_undoRetweetActionSheetForStatus:(id)arg1 account:(id)arg2 source:(id)arg3 doneBlock:(CDUnknownBlockType)arg4;
- (id)t1_undoRetweetActionSheetForStatus:(id)arg1 account:(id)arg2 source:(id)arg3 undoRetweetBlock:(CDUnknownBlockType)arg4;
- (id)t1_retweetMenuSheetForStatus:(id)arg1 account:(id)arg2 source:(id)arg3 scribeParameters:(id)arg4 willQuoteRetweetBlock:(CDUnknownBlockType)arg5 doneBlock:(CDUnknownBlockType)arg6;
- (id)t1_retweetMenuSheetForStatus:(id)arg1 account:(id)arg2 source:(id)arg3 doneBlock:(CDUnknownBlockType)arg4;
- (CDUnknownBlockType)_t1_retweetWithCommentActionForStatus:(id)arg1 account:(id)arg2 scribePage:(id)arg3 scribeSection:(id)arg4 scribeComponent:(id)arg5 scribeElement:(id)arg6 parameters:(id)arg7 willQuoteRetweetBlock:(CDUnknownBlockType)arg8;
- (CDUnknownBlockType)_t1_retweetActionForStatus:(id)arg1 account:(id)arg2 scribePage:(id)arg3 scribeSection:(id)arg4 scribeComponent:(id)arg5 scribeElement:(id)arg6 parameters:(id)arg7;
- (id)t1_retweetActionSheetForStatus:(id)arg1 account:(id)arg2 source:(id)arg3 scribeParameters:(id)arg4 willQuoteRetweetBlock:(CDUnknownBlockType)arg5 doneBlock:(CDUnknownBlockType)arg6;
- (id)t1_retweetActionSheetForStatus:(id)arg1 account:(id)arg2 source:(id)arg3 doneBlock:(CDUnknownBlockType)arg4;
- (void)_t1_scribeAction:(id)arg1 forStatus:(id)arg2 scribeSection:(id)arg3 element:(id)arg4 impressionParameters:(id)arg5 cardEvent:(id)arg6 account:(id)arg7;
- (void)_t1_scribeProfileClickForStatus:(id)arg1 scribeSection:(id)arg2 element:(id)arg3 impressionParameters:(id)arg4 cardEvent:(id)arg5 account:(id)arg6;
- (void)t1_scribeUserRecommendationTapForStatus:(id)arg1 scribeSection:(id)arg2 scribeAction:(id)arg3 impressionParameters:(id)arg4 cardEvent:(id)arg5 account:(id)arg6;
- (void)t1_scribeNameTapForStatus:(id)arg1 scribeSection:(id)arg2 impressionParameters:(id)arg3 account:(id)arg4;
- (void)t1_scribeAvatarTapForStatus:(id)arg1 scribeSection:(id)arg2 impressionParameters:(id)arg3 account:(id)arg4;
- (void)_t1_handlePromotedEventForActiveRange:(id)arg1 inStatus:(id)arg2 account:(id)arg3;
- (id)t1_didSelectActiveRange:(id)arg1 inStatus:(id)arg2 account:(id)arg3 isPreview:(_Bool)arg4;
- (id)t1_didSelectActiveRange:(id)arg1 inStatus:(id)arg2 account:(id)arg3;
- (id)t1_actionItemsForActiveRange:(id)arg1 inStatus:(id)arg2 source:(id)arg3 account:(id)arg4;
- (id)t1_activityViewControllerForActiveRange:(id)arg1 inStatus:(id)arg2 source:(id)arg3 account:(id)arg4;
@end

