//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@interface UIViewController (T1TwitterURLHandling)
- (id)_profileViewControllerForUserReference:(id)arg1 account:(id)arg2 willNavigateInExistingViewController:(out _Bool *)arg3 tabNavigationBlock:(CDUnknownBlockType)arg4;
- (void)_sendTalonRequestForAnalytics:(id)arg1;
- (id)_t1_sharelessWebviewControllerWithTitle:(id)arg1 URL:(id)arg2 account:(id)arg3;
- (id)t1_openURLParserResult:(id)arg1 account:(id)arg2 scribeContext:(id)arg3 willNavigateInExistingViewController:(out _Bool *)arg4;
- (long long)_t1_mediaInfoIndexForStatus:(id)arg1 URL:(id)arg2 account:(id)arg3;
- (id)_t1_openURL:(id)arg1 expandedURL:(id)arg2 account:(id)arg3 scribeContext:(id)arg4 forceAuthenticateWebViewController:(_Bool)arg5 webviewFactory:(CDUnknownBlockType)arg6;
- (id)_t1_openURL:(id)arg1 expandedURL:(id)arg2 account:(id)arg3 scribeContext:(id)arg4 forceAuthenticateWebViewController:(_Bool)arg5;
- (id)_t1_openURL:(id)arg1 account:(id)arg2 scribeContext:(id)arg3 fromSourceStatus:(id)arg4 forceAuthenticateWebViewController:(_Bool)arg5;
- (id)t1_openURL:(id)arg1 account:(id)arg2 scribeContext:(id)arg3 fromCardDataSource:(id)arg4;
- (id)t1_openURL:(id)arg1 account:(id)arg2 scribeContext:(id)arg3 fromSourceDirectMessageEntry:(id)arg4;
- (id)t1_openURL:(id)arg1 account:(id)arg2 scribeContext:(id)arg3 fromSourceUser:(id)arg4;
- (id)t1_openURL:(id)arg1 account:(id)arg2 scribeContext:(id)arg3 fromSourceStatus:(id)arg4 forceAuthenticateWebViewController:(_Bool)arg5;
- (id)t1_openURL:(id)arg1 account:(id)arg2 scribeContext:(id)arg3 fromSourceStatus:(id)arg4;
- (id)t1_openURL:(id)arg1 account:(id)arg2 scribeContext:(id)arg3 forceAuthenticateWebViewController:(_Bool)arg4;
- (id)t1_openURL:(id)arg1 account:(id)arg2 scribeContext:(id)arg3 expandedURL:(id)arg4;
- (id)t1_openURL:(id)arg1 account:(id)arg2 scribeContext:(id)arg3;
- (id)t1_openURL:(id)arg1 account:(id)arg2;
@end

