//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <TFNUI/TFNCollectionViewCell.h>

@class UIView;

@interface TFNViewHostCollectionViewCell : TFNCollectionViewCell
{
    _Bool _clearsHostedViewOnReuse;
    UIView *_hostedView;
}

@property(nonatomic) _Bool clearsHostedViewOnReuse; // @synthesize clearsHostedViewOnReuse=_clearsHostedViewOnReuse;
@property(retain, nonatomic) UIView *hostedView; // @synthesize hostedView=_hostedView;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)cleanup;
- (id)initWithFrame:(struct CGRect)arg1;

@end

