//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIImage.h>

@interface UIImage (TFNVectorImage)
+ (void)_tfn_vectorImageClearCachedDocuments;
+ (void)_tfn_vectorImageSetCachedDocument:(id)arg1 named:(id)arg2;
+ (id)_tfn_vectorImageCachedDocumentNamed:(id)arg1;
+ (id)_tfn_vectorImageDocumentCache;
+ (id)_tfn_vectorImageDocumentCacheQueue;
+ (id)_tfn_vectorImageNamed:(id)arg1 highContrastVariantNamed:(id)arg2 fitsSize:(struct CGSize)arg3 fillColor:(id)arg4 useHighContrast:(_Bool)arg5 addDynamicColorInfo:(_Bool)arg6;
+ (id)_tfn_vectorImageNamed:(id)arg1 highContrastVariantNamed:(id)arg2 fitsSize:(struct CGSize)arg3 fillColor:(id)arg4 addDynamicColorInfo:(_Bool)arg5;
+ (id)_tfn_vectorImageDocumentNamed:(id)arg1;
+ (_Bool)tfn_vectorImageExistsNamed:(id)arg1 fitsSize:(struct CGSize)arg2 size:(out struct CGSize *)arg3;
+ (id)tfn_vectorImageNamed:(id)arg1 fitsSize:(struct CGSize)arg2 fixedFillColor:(id)arg3;
+ (id)tfn_vectorImageNamed:(id)arg1 highContrastVariantNamed:(id)arg2 fitsSize:(struct CGSize)arg3 fillColor:(id)arg4;
+ (id)tfn_vectorImageNamed:(id)arg1 fitsSize:(struct CGSize)arg2 fillColor:(id)arg3;
+ (id)tfn_vectorImageNamed:(id)arg1 highContrastVariantNamed:(id)arg2 height:(double)arg3 fillColor:(id)arg4;
+ (id)tfn_vectorImageNamed:(id)arg1 height:(double)arg2 fillColor:(id)arg3;
+ (void)tfn_vectorImageSetOverrideContainerName:(id)arg1;
+ (id)tfn_vectorImageOverrideContainerName;
+ (void)tfn_vectorImageSetOverrideContainersDirectoryURL:(id)arg1;
+ (id)tfn_vectorImageOverrideContainersDirectoryURL;
+ (void)tfn_vectorImageSetSearchDirectoryURLs:(id)arg1;
+ (id)tfn_vectorImageSearchDirectoryURLs;
@end

