//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@interface UIViewController (TFNNavigationControllerAdditions)
- (void)tfn_navigationControllerDidLayoutBarItems;
- (void)tfn_setNeedsNavigationBarExpansionUpdate;
@property(readonly, nonatomic, getter=tfn_isContentScrolledToBottom) _Bool tfn_contentScrolledToBottom;
@property(readonly, nonatomic) _Bool tfn_prefersNavigationBarExpandedWhenScrolledToBottom;
@property(readonly, nonatomic) _Bool tfn_supportsNavigationBarCollapsing;
@property(readonly, nonatomic) long long tfn_navigationBarMatchingStatusBarStyle;
- (void)tfn_setNeedsLogoTitleViewShownUpdate;
@property(readonly, nonatomic) _Bool tfn_logoTitleViewShown;
- (void)tfn_setNeedsToolbarVisibilityUpdate;
@property(readonly, nonatomic) long long tfn_preferredToolbarVisibility;
- (void)tfn_setNeedsNavigationBarShadowHiddenUpdate;
@property(readonly, nonatomic) _Bool tfn_prefersNavigationBarShadowHidden;
- (void)tfn_setNeedsNavigationBarHiddenUpdate;
@property(readonly, nonatomic) _Bool tfn_prefersNavigationBarHidden;
- (id)_tfnNavigationController;
@end

